### ISSUE TITLE
Rocket Chat client 2.9.0 under Ubuntu x64 17.10 does not show any UI after restart

### ISSUE THREAD

**Issue by obfuscoder** [RocketChat/Rocket.Chat.Electron#636] opened 2017-12-14 15:25 UTC
## My Setup
- Operating System: Ubuntu x64 17.10
- App Version: 2.9.0 amd 64

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After downloading ans installation of rocketchat_2.9.0_amd64.deb on Ubuntu x64 17.10 I could start the application and see the UI. Then I restarted my PC and started the applicaiton after login again. There was no UI shown. The application was still running yet no window was shown. The application only appears in the applications bar on the left side for a split second then it disappears again. htop/ps show the process still running. Notifications do not appear. I don't know if I am connected to the chat server or not.

**Comment by DK-Stern** [comment] 2017-12-21 22:55
I have the same problem and the same setup like you.

**Comment by SDAdham** [comment] 2017-12-26 15:39
same here as well

**Comment by Snom** [comment] 2018-01-03 09:42
I got the same issue... is it possible to debug the client to see some logs while starting ?

**Comment by matrottier** [comment] 2018-01-03 14:41
same here

**Comment by samiball** [comment] 2018-01-04 08:28
same here

**Comment by cries** [comment] 2018-01-08 10:11
Same here

**Comment by Snom** [comment] 2018-01-08 10:56
The installation of the latest version: [2.10.1 ](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.10.1) fixed my problem.

**Comment by hprem** [comment] 2018-01-11 17:55
I too have the same issue and upgrade to 2.10.1 hasn't fixed it for me

**Comment by samiball** [comment] 2018-01-12 08:07
@hprem You should try to uninstall rather than update the application. Before reinstalling remove the config folder ".config/Rocket.Chat+". 
It worked for me.

**Comment by hprem** [comment] 2018-01-12 11:56
Deleting the `.config/Rocket.Chat+` folder always made it to work, but I would loose all my settings.
So I know it was something under that folder it didn't like. After a lot of trial and error runs, I found that it was due to the `.config/Rocket.Chat+/window-state-main.json` file. If I rename that file, i could start rocket chat client without any issues. So I examined that file and found that rocket chat fails to load when `"isHidden": true` is present in that file. On changing it to `false`, it works fine

**Comment by gdelavald** [comment] 2018-01-12 12:09
@hprem thanks for the workaround. Your investigation will help us fix the issue.

**Comment by jaypea** [comment] 2018-01-17 14:26
steps to reproduce:
 - open chat
 - press "ctrl+w" in a chat window
 - gui closes
 - entry "isHidden": false will change to "isHidden": true in ~/.config/Rocket.Chat+/window-state-main.json
 - gui will not come up again

**Comment by jaypea** [comment] 2018-01-17 14:56
i've found this discussion which might help with closing and hiding the window: https://discuss.atom.io/t/how-to-catch-the-event-of-clicking-the-app-windows-close-button-in-electron-app/21425/8

**Comment by GPrimola** [comment] 2018-03-12 22:17
same here. any updates?

**Comment by gdelavald** [comment] 2018-03-15 21:07
Make sure you guys are using the latest version of the Rocket.Chat app, if this is still a problem, report here with the version and OS you are using.

**Comment by obfuscoder** [comment] 2018-04-03 13:21
I fixed this a few months ago by manually installing a newer version of RocketChat+ - not using the version being packaged within Ubuntu. After changing my domain password, I run into the same issue though. RocketChat+ did not start up any longer. Removing the config folder did not fix the issue.

**Comment by alencarandre** [comment] 2018-09-19 13:55
I am using fedora and I am having the same problem.

**Comment by tassoevan** [comment] 2018-09-19 21:33
@alencarandre Which version is misbehaving? Have you tried any suggested workaround in those comments?

**Comment by diskmaster23** [comment] 2018-11-16 21:40
This is the error I am getting in Xubuntu 14.04. Running 4.4.0-138-generic. I installed it via Snap.
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /run/user/1000/snap.rocketchat-desktop/.org.chromium.Chromium.s4mQWW: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/snap/rocketchat-desktop/4/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
`

**Comment by tassoevan** [comment] 2018-11-16 21:50
@davidgut1982 Could you open a new issue, please? Your error doesn't look similar to the ones reported here. Also, some users of recent Ubuntu/Debian versions are reporting issues with the snap package (#928).

**Comment by davidgut1982** [comment] 2018-11-16 22:05
@tassoevan Done. Check it out here. https://github.com/RocketChat/Rocket.Chat.Electron/issues/993

**Closed** 2020-09-02 23:54 UTC
Labels: plat: linux, type: bug
