### ISSUE TITLE
the app logout the user sometimes

### ISSUE THREAD

**Issue by ezef** [RocketChat/Rocket.Chat.Electron#737] opened 2018-05-29 13:21 UTC
hi all!
we have 50 pcs running electron over windows 7 / Windows 10. the user doesnt know the password of his account, so we in IT departament need to log in all the pcs manually by user/pass througt VNC connection. 

the problem is that sometimes electron app log out the user and prompt to input user/pass again. it seems randomly because its always a different machine or 2 and it seems not to be related with windows updates or electron app version ( we have a mix between 2.10.5 and 2.10.4 ).

i do not test with webapp because we use only electron app. its tedious to always once a week login manually 2 or 3 users. i am open to provide all kind of information needed to solve this, just ask

**Comment by ezef** [comment] 2018-06-13 11:36
thanks! @johnyb0y , i will try it!

**Comment by johnyb0y** [comment] 2018-06-13 12:05
@ezef No problem. It’s important that the new value will probably only be valid after the next login.

**Comment by markusstoll** [comment] 2018-07-25 08:12
I do have the same problem with the native client on macOS

Users do lose session quite often, currently daily. The session timeout is set to 90 days.
How can I debug, why this happens?

Ofter relogin, we do have to QUIT and restart the Client to get chat sessions updated (otherwise they show the content up to the time when the logout happened)

This raises another question, why does the client not allow to store the credentials in the Apple keychain - to enforce relogin so often AND to have to enter the credentials manually every time is.... not so user friendly

Markus

**Comment by maurice-schleussinger** [comment] 2018-09-27 08:53
> 
> 
> I do have the same problem with the native client on macOS
> 
> Users do lose session quite often, currently daily. The session timeout is set to 90 days.
> How can I debug, why this happens?
> 
> Ofter relogin, we do have to QUIT and restart the Client to get chat sessions updated (otherwise they show the content up to the time when the logout happened)
> 
> This raises another question, why does the client not allow to store the credentials in the Apple keychain - to enforce relogin so often AND to have to enter the credentials manually every time is.... not so user friendly
> 
> Markus

Any follow-up on this? The mac client loses sessions daily, while I am still logged in via web for a long time (as defined by the server).

**Comment by tassoevan** [comment] 2018-09-27 16:51
@maurice-schleussinger Not yet, but I bumped into a similar problem while solving other issues on Windows. Since the root cause is still unknown, I didn't schedule a fix.

**Comment by ura14h** [comment] 2020-02-18 01:09
I want receive a desktop notification when my account logged off automatically.

**Comment by jeanfbrito** [comment] 2022-01-10 18:02
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:02 UTC
