### ISSUE TITLE
Version 3.0.3 /disableAutoUpdates didnt work anymore

### ISSUE THREAD

**Issue by nexidus** [RocketChat/Rocket.Chat.Electron#1829] opened 2020-10-19 07:12 UTC
## My Setup

- Operating System: Windows 10 Enterprise 2004 Desktop and VM installation
- App Version: 3.0.3
- Installation type: exe manually and with SCCM

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

/disableAutoUpdates switch didnt work anymore.
Up to version 2.17.11 it worked wonderfully with the switches in the order: /S /allusers /disableAutoUpdates. Since version 3.0.3 every user gets the message that a new version is available and you should update. Of course, this does not work for the users because they have no rights to install software.

### Current Behavior

It doesn't matter whether it is installed manually via CMD with the switches or via SCCM it is rolled out with the same switches. The result is the same, the users are asked to perform an update.

**Comment by mape2k** [comment] 2020-11-05 11:45
We'll test 3.0.6 - maybe #1861 should fix the issue...

**Comment by mape2k** [comment] 2020-11-05 12:47
We can confirm, that the problem is fixed in 3.0.6.

**Comment by morgens** [comment] 2020-11-06 05:35
Is there a way do disable autoupdates with MSI installer?

**Comment by mape2k** [comment] 2020-11-16 19:43
@morgens: Just create a file update.json in the directory resources in the unstallation dir with
```
{
  "canUpdate": false,
  "autoUpdate": false
  }
```

**Comment by VasiliyMooduckovich** [comment] 2020-11-24 08:54
@mape2k im tested on 3.0.5 - didn't work for me, but it seems to be moved to client config named `config.json` string `"doCheckForUpdatesOnStartup": true,` that located in the user profile `%appdata%\Rocket.Chat\config.json`

**Comment by VasiliyMooduckovich** [comment] 2020-11-24 09:05
@mape2k just tested another option - the worked one has to look like this

`{`
`  "autoUpdate": false`
`  }`

[https://forums.rocket.chat/t/where-is-chat-server-address-saved-and-how-to-disable-updates-from-local-pc/3382](url)

**Comment by mape2k** [comment] 2020-11-24 12:58
> it seems to be moved to client config named `config.json` string `"doCheckForUpdatesOnStartup": true,` that located in the user profile `%appdata%\Rocket.Chat\config.json`

As mentioned in previous post update.json in resources directory of installation dir (C:\Program Files\Rocket.Chat\resources) did not work in versions between 3.0.0 and 3.0.5. Problem is fixed in #1861 - which is delivered in 3.0.6. So please check again on version 3.0.6 - 3.0.5 won't work.

**Comment by jeanfbrito** [comment] 2022-01-12 02:38
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 02:38 UTC
