### ISSUE TITLE
Install loop when installing 2.13.2

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.Electron#868] opened 2018-09-10 13:29 UTC
## My Setup
- Operating System: Windows 10
- App Version: 2.13.2

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The update notification shows, prompting me to upgrade to version 2.13.2

### Current Behavior
Update installs, RocketChat restarts, but then the update notification comes up again. Upon checking the version number it still shows 2.13.1 as the installed version.

### Expected Behavior
Version should be upgraded to 2.13.2 and no further notice should be shown.

### Humble Suggestion
Perhaps have a more conservative update cycle for the Electron app? Because the default implementation is automatic update checks, this has been causing some issues in our production environment. We are seeing updates almost every week, sometimes twice a week, and when they are broken, we have to jump in and support the users. 😃

**Comment by stevenhfotofix** [comment] 2018-09-10 14:35
It looks like the installers now install into windows with the version number attached to the program name.  I had to go in and uninstall several versions of the client (it had me stuck at 2.13.0 for a couple of weeks).  After cleaning all of those up and installing the latest version again, it is now showing as 2.13.2.

The installer needs to not be using the version number in the app name, and it needs to make sure its removing all old installs.

**Comment by tassoevan** [comment] 2018-09-10 17:34
@stevenhfotofix A mistake was made between 2.12.* and 2.13.* removing an `appId` parameter that identifies the Rocket.Chat setup -- BTW, can you confirm if any other version had this problem?

The multiple installed versions, as far as I know, are an auto update issue, because I couldn't reproduce it just running manually all setups in sequence.

**Comment by stevenhfotofix** [comment] 2018-09-10 20:14
@tassoevan It started with 2.13.0 upgrading to 2.13.1.  In my "Apps & Features" list on windows 10, saw Rocket.Chat (a pretty old version I believe), Rocket.Chat+ (something around 2.0 when hovered over), Rocket.Chat 2.13.1, and Rocket.Chat 2.13.2. 

With the upgrade to 2.13.1, I would get a message every day when I started the computer up, saying it needed to upgrade to 2.13.1 (with the about menu saying it had reverted back to 2.13.0).  I now believe that it was a conflict with multiple copies of the same app installed.  After it finished the install, the updated 2.13.1 app would show up (checking the about menu showed it as being 2.13.1).  But rebooting caused 2.13.0 to show up again as the app that booted up (therefore requesting another update).

The update today, it just kept saying after the update that it was 2.13.1.  So I went in and removed all versions of the app except 2.13.2 - and then ran an install fresh from github.  That caused it to finally say 2.13.2 in the about window.  I have not rebooted since, so I do not know what will happen once I restart - but I assume it will be fine. 

As far as I can tell, its treating all these new updates as a new install, and not as an update to an existing install - and its getting confused as to which binary to run.

**Comment by tassoevan** [comment] 2018-09-10 22:44
Just 2.13.1 is broken in that way. Confirmed after some tests.

**Comment by compuguy** [comment] 2018-09-19 21:08
@bkraul I'm assuming you are talking about 2.13.2?

**Comment by stevenhfotofix** [comment] 2018-10-11 14:28
> Just stumbled on the same bug updating from 2.13.3 to 2.14.0
> 
> Endless loop.

It may be prudent to uninstall everything - and install 2.14.0 fresh.  With this latest update, everything worked fine on all of the PC's I manage here.

**Comment by jmledantec** [comment] 2018-10-11 15:40
> > Just stumbled on the same bug updating from 2.13.3 to 2.14.0
> > Endless loop.
> 
> It may be prudent to uninstall everything - and install 2.14.0 fresh. With this latest update, everything worked fine on all of the PC's I manage here.

No problem for me on more than 10 PC. 
I have donne fresh install after 2.13.3 was realesed on all of them.

**Comment by rex4539** [comment] 2018-10-25 15:46
Endless loop again from 2.14.0 to 2.14.1

I have previously deleted everything in ~/Library/Application Support/Rocket.Chat

Can you folks add some logging for the installation process so you could get to the bottom of this?

**Comment by bkraul** [comment] 2018-10-25 16:01
Not happening on Windows 10. Upgrade goes as planned.

**Comment by jmledantec** [comment] 2018-10-25 16:09
Same here, no problem on win10

**Comment by tassoevan** [comment] 2018-10-25 16:45
@rex4539 The issue in MacOS is a little different:

> Unfortunately, autoupdate fixes can't be applied backwardly. Therefore, versions listed in #894 will fail on update regardlessly; we advise users to click the "Install later" button to update. (https://github.com/RocketChat/Rocket.Chat.Electron/pull/936)

@bkraul I'm closing this issue. Thank you very much for your report and feedback.

**Closed by tassoevan** 2018-10-25 16:45 UTC
