### ISSUE TITLE
Rocket.chat Desktop App not Connecting to Server

### ISSUE THREAD

**Issue by ohsofoxyroxy** [RocketChat/Rocket.Chat.Electron#2078] opened 2021-06-22 15:39 UTC
## My Setup

- Operating System: Windows 10
- App Version: Version 3.2.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Upon opening rocket.chat and trying to connect to server, it gives you the option to sign in, then select your CAC certification. Once selected, it stays idle in the Sign In page.
Screenshot:
![image](https://user-images.githubusercontent.com/11549214/122955530-311fa780-d34e-11eb-9d4c-f2c6d9f5a387.png)

### Current Behavior
Never connects. Stays on Sign In screen.

### Expected Behavior
Server should connect, select certificate, and rocket.chat should be able to be used as opposed to using web version.

**Comment by ajkerzner** [comment] 2021-11-01 19:20
Possible duplicate of #2035

**Comment by jeanfbrito** [comment] 2022-06-24 20:07
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-06-24 20:07 UTC
