### ISSUE TITLE
MacOS Dock Unread Messages Notification Bug

### ISSUE THREAD

**Issue by jthomae1** [RocketChat/Rocket.Chat.Electron#812] opened 2018-08-13 08:42 UTC
## My Setup
- Operating System: macOS High Sierra 10.13.6
- App Version: 2.12.0

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

Since the latest Rocket.Chat+ update (Version 2.12.0) the unread messages hint in the dock doesn't disappear or update/reduce the number of unread messages. For example: If I have two unread messages, the red icon with the number of unread messages (in this case '2') stays there after I read them. It always shows the highest number of unread messages I had, till I restart the app.

![bildschirmfoto 2018-08-13 um 10 27 38](https://user-images.githubusercontent.com/8523176/44020867-8c55a87c-9ee3-11e8-86c4-763842744a96.png)

Furthermore:
The notification in the menubar works correctly, but always show a '0' next to the Rocket.Chat icon, if I have no unread messages. That's actually right, but the number could be hide if there are no unread messages. 

![bildschirmfoto 2018-08-13 um 10 28 25](https://user-images.githubusercontent.com/8523176/44020896-a1e02276-9ee3-11e8-8d85-16cbdb82f214.png)

### Current Behavior

The number of unread messages hint doesn't disappear, after reading messages

### Expected Behavior

The hint should disappear or update the number of unread messages

**Comment by kaiiiiiiiii** [comment] 2018-08-13 11:57
Duplicate of #801

//CC: @tassoevan

**Comment by engelgabriel** [comment] 2018-08-13 12:49
@jthomae1 Can you please try the https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.13.0-develop ?

**Closed by engelgabriel** 2018-08-13 12:49 UTC

**Comment by jthomae1** [comment] 2018-08-14 09:49
@engelgabriel Sorry for duplicating, the version 2.13.0-develop works fine. Thanks!
