### ISSUE TITLE
Spelling language missing

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat.Electron#169] opened 2016-04-12 00:13 UTC
## My Setup

- **My OS name and version**: ArchLinux
- **My current app version**: 1.3.1

fr_FR is missing in the spelling languages menu. So every word I type is underlined in red.

Thanks.
##

**Comment by pyrignis** [comment] 2016-06-26 15:02
I'm also affected.

**Comment by xenithorb** [comment] 2016-08-28 22:35
After you added those dictionaries did you also try `LANG=fr_FR.UTF-8` or the equivalent proper environment variable? This could be a clue that it's not actually looking there for the dicts.

**Comment by pyrignis** [comment] 2016-08-29 10:06
starting rocket.chat.electron with the following command does not help: 
$ ./rocketchat --LANG=fr_FR.UTF-8

**Comment by xenithorb** [comment] 2016-08-29 10:09
If anything it would be

```
export LANG=fr_FR.UTF-8
rocketchat
```

or 
```
LANG=fr_FR.UTF-8 rocketchat
```

**Comment by pyrignis** [comment] 2016-08-29 10:12
it does not work either. And the command line output only complains about the certificate.json file that I have deleted earlier.

**Comment by chkal** [comment] 2016-09-15 17:44
Unfortunately just adding the dictionary files won't work. This is caused by this part of the code:

https://github.com/RocketChat/Rocket.Chat.Electron/blob/e0a426a2cbad6fc40f0e976848284dc268097031/app/scripts/preload.js#L197-L208

I did some research and this seems to happen in the code:

* [node-spellchecker](https://github.com/atom/node-spellchecker) is loaded via `require()`
* Then `getAvailableDictionaries()` is called which will always return an empty array on Linux (see https://github.com/atom/node-spellchecker/issues/54 and https://github.com/atom/node-spellchecker/issues/51)
* Now the client falls back to the three dictonaries which are included in the distribution. But the three locales are hard coded in the client (see code linked above)

I see the following ways to fix this:
  1. Wait for the upstream issues to get fixed ;-)
  2. Remove the hard coded locales and check the contents of the `dictionaries` folder to determine the locales. This way users can add dictionaries more easily.
  3. The same as mentioned in (2) but also check `/usr/share/hunspell` for dictionaries.

Any thoughts?

Upstream issues:
* https://github.com/atom/node-spellchecker/issues/54
* https://github.com/atom/node-spellchecker/issues/51

**Comment by xenithorb** [comment] 2016-09-15 18:09
Hmm, a possible clue as to why I can't get spellchecking to work in Fedora: 

```
$ rpm -ql hunspell-en-US
/usr/share/doc/hunspell-en-US
/usr/share/doc/hunspell-en-US/README_en_US.txt
/usr/share/myspell/en_US.aff
/usr/share/myspell/en_US.dic
```

I don't have a deep understanding of how the spellchecking works, but I am eager to get it working on Fedora for my package.  Thanks for the input!

**Comment by DemonTPx** [comment] 2017-03-07 19:02
I've fixed this in node-spellchecker, but the PR is still open.

See: https://github.com/atom/node-spellchecker/pull/69

It that is merged, the spellchecker will search for dictionaries installed globally on the system.

**Comment by chkal** [comment] 2017-03-07 19:15
That's awesome. Thank you so much.

**Comment by idl0r** [comment] 2018-04-04 08:30
Any news on this issue?

**Comment by xucong-zhang** [comment] 2018-12-10 10:19
+1

**Comment by tassoevan** [comment] 2018-12-10 11:47
Added this issue in 2.15.0 version milestone since I'm refactoring the spell checker code.

**Closed** 2020-02-20 02:59 UTC
Labels: feat: spell checker, type: enhancement
