### ISSUE TITLE
pasting server specific resource url into chat breaks app.

### ISSUE THREAD

**Issue by wspresto** [RocketChat/Rocket.Chat.Electron#1041] opened 2018-12-12 19:01 UTC
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

### Expected Behavior

e.g.
https://<server-url>/emoji-custom/super.jpg?_dc=985

**Comment by wspresto** [comment] 2018-12-12 19:17
https://our.companys.rocket.chat.server.domain.name/emoji-custom/file.jpg?_dc=985
I found this link by using dev tools when inspecting the css image url of an emoji.
I posted this link into chat.
I clicked on the link from chat.
The electron native client on windows 10 64bit was now stuck showing only the image. It had no way to get back to the home page.

**Comment by tassoevan** [comment] 2018-12-12 22:50
Duplicate of #952.

**Closed by tassoevan** 2018-12-12 22:50 UTC
