### ISSUE TITLE
Client scrolls further up in messages every time it is opened

### ISSUE THREAD

**Issue by MoritzMachatschek** [RocketChat/Rocket.Chat.Electron#2040] opened 2021-05-17 09:24 UTC
## My Setup

- Operating System: Windwos 10 Pro
- App Version: 3.2.1/3.2.2
- Installation type: exe

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
Every time the client is closed and opened again, it scrolls further up in the currently focused messages (and the scrollbar gets shorter and shorter), instead of displaying the last message. Reloading resets the position where it scrolls to to somewhere near the last message (i.e. the scrollbar is long again), but does not fix the problem.

Occured after installing the update to client version 3.2.1, and is still there after manually updating to 3.2.2 and after reinstalling (without deleting the user data). The previous version was very old, since the update did nothing (got the message, that the update is available, but never a message, that it is ready to install). The update to 3.2.1 also lead to the error described in #1781, which was solved by adding a `servers.json` as described. The update to 3.2.2 removed that file and it still works, so maybe it is not related to it.

### Current Behavior
Messages get scrolled up when opening the app

### Expected Behavior
Show the last message

**Comment by joaomezzari** [comment] 2021-05-17 18:22
Same behaviour here

**Comment by piotrp** [comment] 2021-05-19 11:15
Looks like duplicate of #1835

**Comment by jeanfbrito** [comment] 2022-08-04 21:54
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-08-04 21:54 UTC
