### ISSUE TITLE
Continually offering to upgrade, never does

### ISSUE THREAD

**Issue by radlyeel** [RocketChat/Rocket.Chat.Electron#1733] opened 2020-09-23 19:39 UTC
## My Setup

- Operating System: Windows 10
- App Version: 2.17.7
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

To reproduce: launch RocketChat 2.17.7

### Current Behavior

I get an offer to upgrade:
<img width="651" alt="RocketChat" src="https://user-images.githubusercontent.com/11529441/94060910-e8789500-fda1-11ea-93f3-ed6bd3b33bee.PNG">
When I click install I am promised a notification when the download is complete, which notification never comes.

### Expected Behavior

I should get either (a) no alert, (b) a notification of completed download, or (c) an actual interactive download/install.

**Comment by drdelaney** [comment] 2020-09-30 22:19
I had this happen as well.  I am not sure what the older install was, but the upgrade was also to 2.17.11.  I manually downloaded it and installed it to work around this as I got tired of trying to update and nothing happening.

**Comment by alc123ng** [comment] 2020-10-03 12:50
Duplicate of #1670

**Comment by ankar84** [comment] 2021-09-08 07:42
Closing in favor of RocketChat/Rocket.Chat.Electron#1670

**Closed by ankar84** 2021-09-08 07:42 UTC
