### ISSUE TITLE
Notification of available update is ok, but second prompt (update ready for installation) never appears

### ISSUE THREAD

**Issue by stupiddog1979** [RocketChat/Rocket.Chat.Electron#1445] opened 2019-12-16 09:17 UTC
## My Setup
- Operating System: Windows 10 Version 1909
- App Version: 2.17.0 -> 2.17.1 (see below)
- Installation type: EXE

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Since a couple of versions (no exact data available), Rocket Chat notifies me that a new version is a available and offers to download and notifies again when it is ready for installation. However, the second notification (ready to install) never comes. I have an unrestricted Internet connection, so there are no restrictions that prevent RocketChat access to the Internet for downloads. I have full admin privileges on my PC. My PC is not a member of a Windows domain, and there are no group policies that could interfere with RocketChat.

### Current Behavior
Update is either now downloaded or something fails before the prompt "ready for installation" appears.

### Expected Behavior
Update downloads and installs without problems.

**Comment by JohnnyRahul** [comment] 2019-12-16 09:57
When I get the New Version 2.17.1 prompted for installation but when I click on Install update, the new version does not get upgraded and no notification pops up when the installation is ready.

My Windows version - 10
Server version - 2.2.1
Current Rocket.chat version - 2.15.5

**Comment by apaarfus** [comment] 2019-12-16 17:09
The only workaround I've found for the time being, is to just "install" it again with the latest download available.  So:

1. Quit the Rocket.Chat application (via the systray icon)
2. Download and install the latest build from [rocket.chat/install](https://rocket.chat/install)
3. Run the installer

Also, this is likely linked to #1399

**Comment by joshmartintv** [comment] 2019-12-26 14:05
This has plagued us for a year now- Ever since 2.15.2.  There have been several issues opened up about this and it never seems to get resolved.  If it can't be fixed, then maybe the button/option just needs to be removed?

**Comment by jeanfbrito** [comment] 2022-01-12 01:37
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:37 UTC

**Comment by joshmartindev** [comment] 2022-01-12 12:41
I can confirm that this has been resolved!
