### ISSUE TITLE
Discolored tray icon

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#402] opened 2017-03-20 14:05 UTC
## My Setup

Fedora 25 with Gnome

![image](https://cloud.githubusercontent.com/assets/51996/24103026/f6097418-0d4b-11e7-8959-6a8981f39f3a.png)

Icon shows up like this when no unreads.  It used to be red, not sure what changed to cause the change

**Comment by graywolf336** [comment] 2017-03-20 19:07
Seeing this on Ubuntu as well.

**Comment by monspid** [comment] 2017-04-05 06:54
It should be blue if you do not read not direct messages.

**Comment by geekgonecrazy** [comment] 2017-04-06 19:53
I didn't realize this was intentionally colored this way: https://github.com/rocketchat/Rocket.Chat.Electron/blob/master/src/public/images/linux/icon-trayDot.png

I think either grey or just red all by its self like it used to be is what all of us have come to be used to.

**Comment by engelgabriel** [comment] 2017-04-06 19:56
it was done inside a fix, and the dev told was he was not a designer... we need to get a designewr to do it right

**Comment by monspid** [comment] 2017-04-07 17:28
Actually i did the icons and the number functionality. It ought to be like this. It is information for those who want to know that they have not direct messages. I have chosen the blue color to tell it is less important than the red color - direct messages. Of course you can make a new set of icons, but if you do so do it also for windows, where the size of icon is 32x32 px.

**Comment by TheReal1604** [comment] 2017-04-13 06:51
also happens on windows.

![image](https://cloud.githubusercontent.com/assets/5877910/24993393/672847c2-2026-11e7-890e-cd3cc905afb0.png)

**Comment by gdelavald** [comment] 2017-08-17 20:38
This is the intended behavior, so I'll close this issue. Thanks.

**Closed by gdelavald** 2017-08-17 20:38 UTC
Labels: plat: linux, plat: windows
