### ISSUE TITLE
No webcam/jitsi on the mac app (permissions?)

### ISSUE THREAD

**Issue by iamgoodbytes** [RocketChat/Rocket.Chat.Electron#1901] opened 2020-11-30 20:20 UTC
## My Setup

- Operating System: Mac OS Big Sur 11.0.1
- App Version: 3.0.3
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I can't get a video call going on the electron app. It works in Chrome. There are also no permissions for my camera or microphone (can't see the Rocket Chat app mentioned there) and there was no dialog asking me for permissions. 

I installed the latest version available in the mac app store which seems to be 3.0.3 
<img width="301" alt="Screenshot 2020-11-30 at 21 17 39" src="https://user-images.githubusercontent.com/3899360/100659840-7ac48880-3351-11eb-94f9-b9ed32ab57ae.png">

<img width="378" alt="Screenshot 2020-11-30 at 21 16 33" src="https://user-images.githubusercontent.com/3899360/100659737-536dbb80-3351-11eb-9ac5-c79f73e4396d.png">

### Current Behavior
When starting a video chat with jitsi, all I see is a gray box

### Expected Behavior
It should start the webcam.

I tried reinstalling the app, but that didn't solve the issue. Also, the app signed me in automatically to my server after reinstalling, which I found weird.

**Comment by ankar84** [comment] 2020-12-01 10:03
You can try this installer https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/3.0.7/rocketchat-3.0.7.dmg if your issue related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1819

**Comment by nicoroeser** [comment] 2020-12-01 10:14
May be a duplicate of/related to #1834, #1841, and/or #1881.

**Comment by iamgoodbytes** [comment] 2020-12-01 11:52
@ankar84 looks like a duplicate I missed indeed. Is there a specific release schedule related to the app store. That would be my preferred way of installing rocket chat. It says 3.0.0 on the app store, but after installing it's 3.0.3, while the latest dmg is 3.0.7.

**Comment by ankar84** [comment] 2020-12-01 11:57
> Is there a specific release schedule related to the app store

Only @tassoevan can tell.
I think there is some issue with publishing process.

**Comment by jeanfbrito** [comment] 2022-01-10 18:48
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:48 UTC
