### ISSUE TITLE
[BUG]: Context menu does not work (right mouse button) ver. 2.14.1

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat.Electron#965] opened 2018-10-31 14:34 UTC
## My Setup
- Operating System: Windows 7
- App Version: 2.14.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
Missing context menu.

### Expected Behavior
Return back.

**Comment by tassoevan** [comment] 2018-10-31 14:43
Duplicate of #956.

**Closed** 2018-11-21 06:16 UTC
Labels: feat: context menu, plat: windows, stat: duplicate, type: bug
