### ISSUE TITLE
Lag when typing, extremely high cpu load

### ISSUE THREAD

**Issue by j20d** [RocketChat/Rocket.Chat.Electron#773] opened 2018-07-18 09:14 UTC
## My Setup
- Operating System: debian stretch amd64
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When I type I experience severe lag and the app generates over 100% load.

### Current Behavior
Characters appear on screen significantly later than I typed them (think ssh over dial-up-modem in the 90s), cpu-load goes up, laptop turns on fans. Holding a key on the keyboard locks up the app for up to 30 seconds after letting go.

### Expected Behavior
I'd go for "text just appears, no lag, no load", there's no need for any background actions to significantly ramp up the load when I type.

**Comment by 0x6c** [comment] 2018-07-19 06:14
We had the same issue. It's related to locale which is configured in your os and spellchecker.

**Comment by gdelavald** [comment] 2018-07-19 16:40
Hey @0x6c could you provide a little bit more context on this? Maybe we could look for a fix or a workaround that could improve the performance.
Thanks!

**Comment by 0x6c** [comment] 2018-07-20 04:14
Hi @gdelavald ,
Sure. Some time ago I found this on few of our computers. When people starting to type something - chat freezes, after disabling of spell checker - everything works just fine.

It's especially related to Windows 8 / 8.1

**Comment by j20d** [comment] 2018-07-20 06:26
I have yet to find a way to disable the spellchecker, the linux-version does not seem to offer that.
What I've tried is moving all the dictionaries from their directory and then starting, that sets my spelling language to (empty). 
That does not make a difference in behaviour though.

**Comment by j20d** [comment] 2018-07-26 14:15
@0x6c en_IE, but rocketchat automatically starts with --lang=en_US and also uses en_US for the spell-checker. I've tried using de_DE, en_US and en_DK as LANG, no difference at all. Also, the dictionaries here are en_US, en_GB, es_ES and pt_BR - and even deleting them won't keep it from consuming ridiculous amounts of cpu.

**Comment by 0x6c** [comment] 2018-08-01 03:45
@j20d can you please try to turn off system spellchecker, just to confirm if it's related?

Thanks.

**Comment by tassoevan** [comment] 2018-08-01 20:56
* Just in case: does Rocket.Chat behave well in browser? I ask it because there were some reports weeks ago and they were out of scope of the Electron app.
* Besides CPU load, is any abnormal RAM usage noticed?

**Comment by j20d** [comment] 2018-08-03 16:15
@0x6c: I have no idea how to do that on linux, I don't even know if there is one.

@tassoevan: in firefox cpu ramps up to ~50% but not above, interface stays responsive, no lockups. I've cross-checked atom and slack as I believe they're both electron as well and they don't show the load-increase

**Comment by hillu** [comment] 2018-08-03 16:58
@0x6c In Chromium (free/libre version of Chrome) on Debian/stretch, I can reproduce bits of the observed behavior (100% CPU, noticeable lag but not as bad as described) by either holding down a key or rapidly typing random garbage into the chat window.
The profiler from the dev-tools shows that every(?) key press event eventually lead to a layout event, there is even a warning "Forced reflow is a likely performance bottleneck".

**Comment by kaiiiiiiiii** [comment] 2018-08-03 17:08
This issue was already addressed in the server repo and there’s also a open PR to fix it :)

https://github.com/RocketChat/Rocket.Chat/pull/11476

**Comment by engelgabriel** [comment] 2018-08-13 12:52
The new PR is https://github.com/RocketChat/Rocket.Chat/pull/11686

**Closed** 2020-08-12 22:50 UTC
