### ISSUE TITLE
Version > 2.15.5 : no fr-FR dico nor audio message

### ISSUE THREAD

**Issue by Sicoval31** [RocketChat/Rocket.Chat.Electron#1581] opened 2020-04-16 10:13 UTC
since upgrade in latest version, superior at 2.15.5 the fr-FR dictionnary (and other language...) is not enable.
We can't do audio message too !
why the latest version seems not to be an upgrade but a downgrade ????

**Comment by gabriellsh** [comment] 2020-04-27 16:40
Please, provide more info, such as server version, etc. Also, the app is at 2.17.9 ATM.

**Comment by Bob0t** [comment] 2020-05-20 13:25
I confirm there is no French dictionary available by default in Windows Client for spell checker, and when I try to add one it asks for a `*.dic` or `*.aff` which I can't find on the internet, also in browsers based one chromium it's `*.bdic` files.

Checking this page confirms that there is no fr_FR dictionary available.

The fact there is no default one isn't really an issue for me, but I'm wondering where I can find it. Looks like I'm bad with google ...

Client Version : 2.17.9 (Windows 10)
Server Version : 3.2.2

**Comment by nbara** [comment] 2020-07-23 13:40
Any news on this ? How to add a french dictionary to the list of available languages ?

**Comment by MatthieuPERIN** [comment] 2020-09-07 15:06
👍 
Same issue with the same error message.
Try to hard copy the dict file inside \AppData\Roaming\Rocket.Chat with no more success

System : Windows 10 Pro 64-bit
Rocket.chat desktop V 2.17.11

**Comment by Naworm** [comment] 2021-01-05 21:16
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1766

**Comment by jeanfbrito** [comment] 2022-01-12 01:44
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:44 UTC
Labels: feat: spell checker
