### ISSUE TITLE
 Don't open app in start when use tray icon 

### ISSUE THREAD

**Issue by HieuHongLe94** [RocketChat/Rocket.Chat.Electron#1396] opened 2019-11-15 08:27 UTC
## My Setup
- Operating System: Win 10
- App Version: 2.16.2
- Installation type: exe

## Description
1: Use tray icon and close app
2: In start, click app 
3: don't open app

### Current Behavior
Don't open app in start when use tray icon and close app

**Comment by CitizenDev** [comment] 2019-11-15 08:32
I can replicate the issue using same app version and WIN 10 1903

**Comment by apaarfus** [comment] 2019-11-24 05:22
We've tested and experienced this behavior in the following as well:

* Windows 7 x64 Professional
* Windows 7 x64 Home Premium
* Windows 10 Pro 1803
* Windows 10 Pro 1809
* Windows 10 Pro 1903
* Windows 10 Pro 1909

My only recommendation is to either never actually close (hide) the window; and to instead just minimize it--though, that's hardly a workaround.

**Comment by ankar84** [comment] 2019-12-02 06:48
I can't reproduce that on version 2.16.0 and 2.17.0 with Start Menu icon and Desktop icon on Windows 10 Pro 1809 and Windows 10 Pro 1909.
Thats my steps:
1. Press Exit in context menu of Rocket Chat tray icon
2. Launch Rocket Chat icon from start menu or Desktop
3. It is started normaly.

Important note. In you exit from Rocket Chat when it is minimized to tray, it will be launched minimized - no main window, only tray icon.

**Comment by jeanfbrito** [comment] 2022-01-12 01:02
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:02 UTC
