### ISSUE TITLE
High network usage 

### ISSUE THREAD

**Issue by lascapi** [RocketChat/Rocket.Chat.Electron#1563] opened 2020-03-26 16:41 UTC
Hi! 
I found the application for Windows 10 use a lot of data over Wifi. Something like 660Kbits/s even if it's in the background. 

If I use Rocket Web in Firefox it's 0Kbits/s. 

## My Setup

- Operating System: Windows 10 Pro v1903
- App Version:  2.17.7
- Server version: 1.3.2 
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily : yes, each time 

## Description
Just open the app, see how many it consume and close it. 

### Current Behavior
The app consume 660KBits/s

### Expected Behavior
The app should consume ~0Kbits/s 

Thanks a lot :)

**Comment by gabriellsh** [comment] 2020-04-27 15:27
Couldn't reproduce in Catalina. Maybe a windows only problem?

**Comment by jeanfbrito** [comment] 2022-01-12 01:45
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:45 UTC
Labels: plat: windows
