### ISSUE TITLE
MacOS: Paste text from the clipboard copied from MS Word for Mac as text

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat.Electron#951] opened 2018-10-26 09:42 UTC
My Setup
- Operating System: macOS High Sierra v.1013.6
- App Version: Rocket.Chat v.2.13.3, MS Word for Mac v.15.30

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

When you paste text into Rocket.Chat from the clipboard copied from an MS Word for Mac document, the text is inserted as an image. It is very uncomfortable.
In MS Windows, the text from the MS Word document to Rocket.Chat is inserted into the input field as text.

### Expected Behavior

It is necessary that in MacOS copied text from an MS Word for Mac document can be inserted into the input field Rocket.Chat as text, as in MS Windows.

**Comment by kz159** [comment] 2018-11-16 15:21
Any news about that? pretty nasty bug

**Comment by tassoevan** [comment] 2018-11-16 15:31
This issue wasn't triaged yet. BTW, isn't this bug occurring when accessing Rocket.Chat from a web browser too?

**Comment by kz159** [comment] 2018-11-16 15:57
@tassoevan sorry, cant reproduce it right now, far from my macbook now, will see on monday.

**Comment by kz159** [comment] 2018-11-20 08:51
This bug happens if i use native app or chrome/opera_neon browser
On safari copy/paste from ms office works as expected

**Comment by tassoevan** [comment] 2018-11-26 13:17
I'm closing it since is a known issue affecting all Rocket.Chat clients based on Chromium, even Google Chrome. Here is the original issue to follow: https://github.com/RocketChat/Rocket.Chat/issues/3551

**Closed by tassoevan** 2018-11-26 13:17 UTC
Labels: feat: web view, plat: osx, type: bug
