### ISSUE TITLE
Version 3.0.1 still does not validate valid server

### ISSUE THREAD

**Issue by kelirkenan** [RocketChat/Rocket.Chat.Electron#1764] opened 2020-10-02 07:19 UTC
## My Setup

- Operating System: Windows 10
- App Version: 3.0.1
- Installation type: .msi
- Server version: 3.7.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
My setup is as follows:
- Server side: Self-hosted docker deployment with reverse nginx-proxy with server certificate issued with a self-signed corporative CA with client certificate validation enabled on the nginx-proxy configuration.
- Client side: Each user has a certificate issued with the same self-signed corporative CA.

With app version 3.0.1, which, in theory, solves server validation I still can't connect to my local self-hosted server using the Electron client. The url of my server is https://teamchat but no matter how I type the url I cannot get the client to validate my server. If I try the `servers.json` workaround I get a window prompt asking to select my client certificate, but when I choose the certificate, the client app does nothing.

I think this is a client related issue because when accessing the server through any Browser (Firefox, Chrome, Edge,...) the experience is flawless.

### Current Behavior
I cannot use the Electron client, at least on Windows 10. Haven't tried other OS versions or other Operative Systems such as Mac or Linux.

### Expected Behavior
The client should be working perfectly as it has been working for more than two years without issues.

**Comment by servig** [comment] 2020-10-02 07:45
same

**Comment by Pschemek** [comment] 2020-10-02 07:45
Same here can't connect to local hosted server (3.6.2) in internal network. 
Electron version 3.0 and 3.0.1 for Windows giving same results: message that valid server is not found.

**Comment by hit-rsimcic** [comment] 2020-10-02 08:13
same

**Comment by ura14h** [comment] 2020-10-02 08:19
I'm running my RC server with a subdirectory. When I run Add Server on this version, the app tries to access the URL where the subdirectory was lost.

**Comment by sergeyreznik** [comment] 2020-10-02 09:15
I can confirm that server validation still does not work correctly. Win10, self-hosted server.

**Comment by fsfonte** [comment] 2020-10-02 11:39
Same here. Win10, self-hosted server.

**Comment by trickvi** [comment] 2020-10-02 11:54
Still the same on Ubuntu (snap) and now the fix to run on latest/edge also doesn't work because that is version 3.0.1

**Comment by stardude900** [comment] 2020-10-02 15:03
Same here. OSX 10.14

**Comment by kelbren** [comment] 2020-10-02 20:49
Confirm as well, client 3.0.1 Same here, self hosted. can not login

**Comment by TheDigitalEagle** [comment] 2020-10-02 23:05
Found a work around.
From a fresh install of 3.0.1, go in and connected to the default rocket chat url listed (https://open.rocket.chat). It will bring you to their chat login page.
At this point close the software completely (not even running in the tray) and go to C:\Users\(your ursername)\AppData\Roaming\Rocket.Chat and edit config.json.

It will look like this:

`{
	"__internal__": {
		"migrations": {
			"version": "3.0.1"
		}
	},
	"currentServerUrl": "https://open.rocket.chat",
	"doCheckForUpdatesOnStartup": true,
	"isMenuBarEnabled": true,
	"isShowWindowOnUnreadChangedEnabled": false,
	"isSideBarEnabled": true,
	"isTrayIconEnabled": true,
	"rootWindowState": {
		"focused": false,
		"visible": true,
		"maximized": false,
		"minimized": false,
		"fullscreen": false,
		"normal": true,
		"bounds": {
			"x": 460,
			"y": 240,
			"width": 1000,
			"height": 600
		}
	},
	"servers": [
		{
			"url": "https://open.rocket.chat",
			"title": "Rocket.Chat",
			"lastPath": "https://open.rocket.chat/home",
			"badge": "",
			"style": {
				"background": "rgb(47, 52, 61) none repeat scroll 0% 0% / auto padding-box border-box",
				"color": "rgb(158, 162, 168)"
			},
			"favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAO30lEQVR4Xu1dCXAUVRr+/p5JAoQjciMQku6ZBEXxwKM8WEVFXAFBS9ESb1a8Lbe8FkHXg6VWRVE264WlloCyiwgSBCktieuxiHIE5Eim3ySEqJCImIQj1/Tbem2STZijX09mJjNhXtVUB+Z///+9/5vX/Y7//U1IlrjyAMUVmiQYJAmJsx9BkpAkIXHmgTiDk+whSULizANxBiesHlKWm3t8nc+X6fD5DMXprGk0jIMOn68mq7S0hgBfnLUxoeBYElLsdp+tGMYlHLgEQGbTxxmilcUc2Ahgs4Pz7fWGseOE0tLShPJKB4L1I2RHdvawFIdjNOd8NAEXAsiJAL7PCVjS6HQuGV5UVBMBfZ1WRQshe4YM6XokLW0mATOj1VoCdnOiJU6iJdkez5Zo2UlkvS2EeDTtIwBXxKwxRB8Q56+4GFsXM5sJYKjNLUvXtA0cODPGuOc4fb5nsktLa2NsNy7N+T1DPKq6HkRnxxQt0QbFMJ7RvN5VMbUbh8YCjrI8qroTRMNjjZeAOS7GovYMi3V7wrEXkBBd0/pzYDOA48NR2q46RG9t1vXpU47R+UzQeQhT1TMMoABE6e1ycBiVObCaOxzTc4uLf2xd3eNy9TR8vmwn0WAfUX8A/RSgn7gaQH8F4JyognNeyYEKhagCgPkxFKUip0ePCtq4sSEMSDGrEnJiyFT1KoNoWczQtDW0iQNfEpDFgWxxBdAzAlh2ErCBE20gzrfUpaVtHbFjx8EI6I2ICsuZusflmgfOH4iItfhUYkAQBGxxcF7YyPmm3JKSDR0F1ZKQkqysjEZFWQeiUzsKZKztip4JIJ/7fPm5paW7YmnfkhABpkjTJivA8lgCixdbHPhYkGM4nfnDi4p+ijYuKUIECI+m/RvANdEGFK/6OSCeM/mc80W5Xu/qaOGUJqQ4O/sPpChfRAtIIunlwBIFyHMx9nWkcUsT0tRLFgD4U6RBJKo+Drzh4DxP83q3RaoN9ghxuW4E5+9Gyngn0XOEgLx6w/jniSUlu9vbJluEeLOzc32KEtNRR3MDHf36IS0nB0qPHlB69YKjZ0/zKv7tENeev09RjOpq+KqqYNTUwKiqgq+62ryKf9cVFcH3yy/t9Vmw+vsI+JuLsX+0x4AtQppuW3sBDGiPUau6wsldRo5E2sknI+2kk8xPypAhVtWkvm8oL0ddYSFqt21D/a5dqNu1K9Ik/YuAWS7GdClARwmFQ4jYvxA7iREtaSNGIH3MGHS74AKTAEpJiaj+UMoEMYfXr8fhggIc/uqrSNjdwzn/S47X+55dZR1KSKrL9TsJY8ag61ln2cUeFfn64mIcWrfOJOfId9+1zwbnM9xe79/tKOkQQnpeey26X3YZuo0ebQdrzGXrtm0zyalavBi+/fvDs8/5k26v9ynZyjElpMekSeh1ww3octppsvjiQq7xxx9R9d57qFq0CMahQ7YxGcBDuYy9IFPRFiEeVX0ARPNkFLeWEb2h19Sp6HrOOXarxpV8PWOobiKG+2yGnxFNcev6UqsGSRPiUdWpIFpkpbD192KU1Pv++83nRGcqdTt34rc330TNRyIuxEaRIEWKEI/LdSk4F9a7yJpPHzsWA559tmV+IFsvkeQOvPoq9r8gdSdqblYNV5SxOR7Pt8HaaUmIx+U6rYmMobLO6nXTTej3xBOy4gktd3DtWuy95x47bShwDR06lgoKGgNVsiSkWNM+JuByWYuD3ngD6RddJCveKeTEs6Vs3Dg7bXnBzdhDtgnxuFzXgHOx7C5VXHpYk1Mp3YkgpLtc8jCJxrh1veDoCiF7iEfTpGflmWvWINXtlgfUCSXrduzAniukgz9XuhmbJE1IsabdQsDbMn4b+PLL6D5+vIxop5epXroUFTNmyLWT6Ea3rrcZuQbtIcWatoEkwkp733svej/QmWMg5HzbWurAggXY/+yz1hWJNrh1vU2UaLBAuT+K2CgrjeLhLR7iyeLvgV/nz4f4WBVuGBfklJT8p1kuICHFmjafgPuslB2LIyornzR/31hRgfLJkyGuoQoH5uYw9nBIQjyaVgmgbyhFyd5hTY1MLyGgyMVYSxy1Xw8pUtXLFSIR+hKyJHuHlYdg9g6ZXkLAGS7GxDFA/0wOHk1bAuDaaPeOw19+idrNm1H3ww9IGTYM5gbVuHFQuna1bmkrCbEte+Sbb1C7datZt8uoUeh+8cVQMjJs6TEOH0bNihWo3bgR5HSiyymnIE18RoywpedoYclecoeLMfNh7NdDdE0r5MDIUCj6zpqFjFtuCRto1cKFqHzKf4sgJTMTA/PykHbiiVK6xe7e3rvvhnBm6+Ls3x99Hn0UYrlfptRu2oSKmTNR7/G0EafUVPSdMQO9brxRRk1Ambrt27HHAoeIXslh7I5gPUQ8hUREedDSntvV3jvvxMHPPgvZwOxvvoGjvwhuD16Ckdq6xvHvvINu558fUs/BNWuw977Q4xcZPcGMiB+Ld2TI37foFV+5GDN369r0EA44dE0LuOjV2uCwzz5DSpYIRrdXZCdNVgMG8asrv+Ya8Pr6kACUbt0weOlSpOXmBpUrGz8e9UVF7dYTSsHuiy9Gw+6QEUI/uBk72Y+QopycwYrPVx5KOaWlQdu+3R4TTdL7HnrIvE/LlKErVpjBDoGK2CSqkFxNHjhvHrpPnBhQjwhuKJswQQYO+s6ciYxbb5WSPVrop2nTcPiLkEGf5W7GzNX0Nj1kl6qe4SAKubOfmpODzNWWc8aAwHdfeCFEGI5M6T97Nnped11A0YpHH0X1MrljK31mzMBx06YFJnbZMghdMkWQKsgNp1Q+/TSq3g0ZX3jQzViPsAgRD9yhK1eGgwtJQoK6rcHNWGpYtyxHnz7I/jbohldIopK3rKDu2edmbKAfIbIPdXXbNtvzBWEs+VAPSshON2PmWN//nLqmWQ57M9euRaqmhXXbSg57A7rtazdj5vg8rInhoAUL2hVJkpwY+pHyppux24P1EMulk+4TJmDgSy+F1UOaK4nljoaff4avstKMTBGz667nnWf7ViiWThqKi9FQUQElJQXOQYPQ9cwzw1o6EUPTxr0ilhxwDhwIsXLQ7qWTvDz8auErA7gvl7G8gITILi6KkZbsEke7mEvgyuJohNjStRrqG5yPzvV6zSjvwKk1JJbfM267DX0feyyB3RV96L+99RZ+mTMnpCEO7G9IS8tqPisf9gaVo29fDPngg4id24i+e2JrgTc2Ys/EiX4Lln4oiN526/ptzf/fri1csZo6wF7kXmy90oHWqt5/H5WPP26JgICrXIy1HDlvd5BDv6efRq/rr7c0fCwJHPr8c3NbQPQSi8LKGRs+BmgRDEWIVBiQo3dvDF64EKkhVlStUHWm70UUY/nVV5tnGq0KAQ+7GJvbWi4igXIisHrg/PkxPYZm1diO+r703HMtAxuasBW4GfM7FhCaEBuhpGLsP2DuXDgHD+4oX3S4XYl9j/9jJLrMretrjwYd0WBrsWklSOly6jGTp6bFn3uuvBLiCJxUIXrJret/DiRrSYhIZMaJVnHJo9Bil06Qkn7ppVLYEl1I7ASWT5kifwaR8y1OwxiTXVr6W1iEiEp2E5n1uOoqDHjuuUT3tSV+MZr6efp0S7nWAgZwZS5jQbdNLXtIszKmqg8YkucLU4cPR+aqzp1gVDp+tzUbEidypQkRej0u14vgPOC97+ifibp5s5n2orOVmg8/NI9J1xYW2muaBBlCoS1CTFIkz4wMXrwYXc+Obfpfex6yJ31w9WqTiCPh7JYSLXPr+tUyFqNGyND8fKSdcIIMhriWEc8JQYRF1EioNgQ8mBOsQtQIGVZQkLALj0fWr29JryFm3uGWoyPbZfREjRB106aEOhJdu2ULRG84vG4dxDn0dpY9IJrp1vWFdvXYJ0RVvSDKtjIUzgHQmuXLse/hh83UG2Jy2eX0082/xe5dJIvImSWCs0Wgt0jPJALmGsrKImUidumZdmZlZTkdjhIr5GJta9Crr1qJtflejF72PfJIwDqOjAwzEl1EpIvtXjNhWeskZk1/g6hN8rI2ycyqq03nCxIi6PzWeCsJeCamCcyYql5vEC228nT/OXPQc8oUK7GW78OZYEkrj4Ug569AUV5063r4D5wmnLZuWcWa9joBllNTO8HYYhj549SpsXBbNGysFMl4Ap03D9eYNCG6po3iwPdWhsS9X2ztyhQxtt97//0yovEms6mJCFvJeGQaIU2IbO/o+/jjyLj5ZkvbB15/Hfuff95SLs4EGDh/E4oiekVdNLBJESLbO0RMlFjDEg/cYEXcog689hrEkbYEKZUgyifO8zXG8qP9nkZZQpZzYLKVA4+76y70efDBgGIiNklkZBN5phKg1IHzfCLKT2loyB9WVnYgVpgtCZHNIieyiA5dtcov5vfQp5/i4CefQKQx4rXx+94vDmwloFC8W0QxjHw1AkmRwyExJCHFbvepZBgiAY3lkVZxuKbfrFloKC1FfUmJGY8kiBBZPsMs4ryaB5xnReEtP+J8mXhnyAYi2urw+QrVkpJ9YeKMaLWghDBV7eUjWkVA6FOTTXDEyq4gwffrr5EAWAai6c17zoUDBqSnd++ezYlUbhjZJF53RNQNnKdzonSF826c83QQiZezVImTD+aV82oOVClEVQbn1Q6gijj/IV6cH8hRQQmROa8eCc8frYMD3zkN43a1pMTmhkM00MReZ7BQUqkJYMThcp5fbxjTR5SW/h6CfgyWQOdDnuNASzKUGPmkngOzcxh7Jkb24tZMG0I8qvpXED0ZS7QkXpFHNNut6/+Npd14tdVCSAeQIZbx89y6Ht5Z43j1aDtxtRCia5pIJXoTB6zXPcI3KpYbVhCwnBOtiNbyQ/jwOr6m3zNEvLSlUVEm0e+v8j4vEhA58BURLU9xOJZnFRVZ7qdEwmai6gg5MWSqmgNglEE0SlwBZDZ9nCEbzPkWKEoBDON7H+ffDy8pCZ1MJFG9FwXclksngWyW5eYeX+fzCXL8Uo93qa3dOrS8PCKzwyi0N+5VhkVI3LcqgQEmCYkz8pKEJAmJMw/EGZxkD0kSEmceiDM4yR4SZ4T8DzC3+7BnBMofAAAAAElFTkSuQmCC"
		}
	],
	"skippedUpdateVersion": null,
	"trustedCertificates": {},
	"isEachUpdatesSettingConfigurable": true,
	"isUpdatingEnabled": true,
	"externalProtocols": {}
}`

Modify this to only update the following below in bold. Do not try to edit anything else.

`{
	"__internal__": {
		"migrations": {
			"version": "3.0.1"
		}
	},
	"currentServerUrl": "**YOUR URL HERE**",
	"doCheckForUpdatesOnStartup": true,
	"isMenuBarEnabled": true,
	"isShowWindowOnUnreadChangedEnabled": false,
	"isSideBarEnabled": true,
	"isTrayIconEnabled": true,
	"rootWindowState": {
		"focused": false,
		"visible": true,
		"maximized": false,
		"minimized": false,
		"fullscreen": false,
		"normal": true,
		"bounds": {
			"x": 460,
			"y": 240,
			"width": 1000,
			"height": 600
		}
	},
	"servers": [
		{
			"url": "**YOUR URL HERE**",
			"title": "**YOUR TITLE HERE**",
			"lastPath": "**YOUR URL HERE**",
			"badge": "",
			"style": {
				"background": "rgb(47, 52, 61) none repeat scroll 0% 0% / auto padding-box border-box",
				"color": "rgb(158, 162, 168)"
			},
			"favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAO30lEQVR4Xu1dCXAUVRr+/p5JAoQjciMQku6ZBEXxwKM8WEVFXAFBS9ESb1a8Lbe8FkHXg6VWRVE264WlloCyiwgSBCktieuxiHIE5Eim3ySEqJCImIQj1/Tbem2STZijX09mJjNhXtVUB+Z///+9/5vX/Y7//U1IlrjyAMUVmiQYJAmJsx9BkpAkIXHmgTiDk+whSULizANxBiesHlKWm3t8nc+X6fD5DMXprGk0jIMOn68mq7S0hgBfnLUxoeBYElLsdp+tGMYlHLgEQGbTxxmilcUc2Ahgs4Pz7fWGseOE0tLShPJKB4L1I2RHdvawFIdjNOd8NAEXAsiJAL7PCVjS6HQuGV5UVBMBfZ1WRQshe4YM6XokLW0mATOj1VoCdnOiJU6iJdkez5Zo2UlkvS2EeDTtIwBXxKwxRB8Q56+4GFsXM5sJYKjNLUvXtA0cODPGuOc4fb5nsktLa2NsNy7N+T1DPKq6HkRnxxQt0QbFMJ7RvN5VMbUbh8YCjrI8qroTRMNjjZeAOS7GovYMi3V7wrEXkBBd0/pzYDOA48NR2q46RG9t1vXpU47R+UzQeQhT1TMMoABE6e1ycBiVObCaOxzTc4uLf2xd3eNy9TR8vmwn0WAfUX8A/RSgn7gaQH8F4JyognNeyYEKhagCgPkxFKUip0ePCtq4sSEMSDGrEnJiyFT1KoNoWczQtDW0iQNfEpDFgWxxBdAzAlh2ErCBE20gzrfUpaVtHbFjx8EI6I2ICsuZusflmgfOH4iItfhUYkAQBGxxcF7YyPmm3JKSDR0F1ZKQkqysjEZFWQeiUzsKZKztip4JIJ/7fPm5paW7YmnfkhABpkjTJivA8lgCixdbHPhYkGM4nfnDi4p+ijYuKUIECI+m/RvANdEGFK/6OSCeM/mc80W5Xu/qaOGUJqQ4O/sPpChfRAtIIunlwBIFyHMx9nWkcUsT0tRLFgD4U6RBJKo+Drzh4DxP83q3RaoN9ghxuW4E5+9Gyngn0XOEgLx6w/jniSUlu9vbJluEeLOzc32KEtNRR3MDHf36IS0nB0qPHlB69YKjZ0/zKv7tENeev09RjOpq+KqqYNTUwKiqgq+62ryKf9cVFcH3yy/t9Vmw+vsI+JuLsX+0x4AtQppuW3sBDGiPUau6wsldRo5E2sknI+2kk8xPypAhVtWkvm8oL0ddYSFqt21D/a5dqNu1K9Ik/YuAWS7GdClARwmFQ4jYvxA7iREtaSNGIH3MGHS74AKTAEpJiaj+UMoEMYfXr8fhggIc/uqrSNjdwzn/S47X+55dZR1KSKrL9TsJY8ag61ln2cUeFfn64mIcWrfOJOfId9+1zwbnM9xe79/tKOkQQnpeey26X3YZuo0ebQdrzGXrtm0zyalavBi+/fvDs8/5k26v9ynZyjElpMekSeh1ww3octppsvjiQq7xxx9R9d57qFq0CMahQ7YxGcBDuYy9IFPRFiEeVX0ARPNkFLeWEb2h19Sp6HrOOXarxpV8PWOobiKG+2yGnxFNcev6UqsGSRPiUdWpIFpkpbD192KU1Pv++83nRGcqdTt34rc330TNRyIuxEaRIEWKEI/LdSk4F9a7yJpPHzsWA559tmV+IFsvkeQOvPoq9r8gdSdqblYNV5SxOR7Pt8HaaUmIx+U6rYmMobLO6nXTTej3xBOy4gktd3DtWuy95x47bShwDR06lgoKGgNVsiSkWNM+JuByWYuD3ngD6RddJCveKeTEs6Vs3Dg7bXnBzdhDtgnxuFzXgHOx7C5VXHpYk1Mp3YkgpLtc8jCJxrh1veDoCiF7iEfTpGflmWvWINXtlgfUCSXrduzAniukgz9XuhmbJE1IsabdQsDbMn4b+PLL6D5+vIxop5epXroUFTNmyLWT6Ea3rrcZuQbtIcWatoEkwkp733svej/QmWMg5HzbWurAggXY/+yz1hWJNrh1vU2UaLBAuT+K2CgrjeLhLR7iyeLvgV/nz4f4WBVuGBfklJT8p1kuICHFmjafgPuslB2LIyornzR/31hRgfLJkyGuoQoH5uYw9nBIQjyaVgmgbyhFyd5hTY1MLyGgyMVYSxy1Xw8pUtXLFSIR+hKyJHuHlYdg9g6ZXkLAGS7GxDFA/0wOHk1bAuDaaPeOw19+idrNm1H3ww9IGTYM5gbVuHFQuna1bmkrCbEte+Sbb1C7datZt8uoUeh+8cVQMjJs6TEOH0bNihWo3bgR5HSiyymnIE18RoywpedoYclecoeLMfNh7NdDdE0r5MDIUCj6zpqFjFtuCRto1cKFqHzKf4sgJTMTA/PykHbiiVK6xe7e3rvvhnBm6+Ls3x99Hn0UYrlfptRu2oSKmTNR7/G0EafUVPSdMQO9brxRRk1Ambrt27HHAoeIXslh7I5gPUQ8hUREedDSntvV3jvvxMHPPgvZwOxvvoGjvwhuD16Ckdq6xvHvvINu558fUs/BNWuw977Q4xcZPcGMiB+Ld2TI37foFV+5GDN369r0EA44dE0LuOjV2uCwzz5DSpYIRrdXZCdNVgMG8asrv+Ya8Pr6kACUbt0weOlSpOXmBpUrGz8e9UVF7dYTSsHuiy9Gw+6QEUI/uBk72Y+QopycwYrPVx5KOaWlQdu+3R4TTdL7HnrIvE/LlKErVpjBDoGK2CSqkFxNHjhvHrpPnBhQjwhuKJswQQYO+s6ciYxbb5WSPVrop2nTcPiLkEGf5W7GzNX0Nj1kl6qe4SAKubOfmpODzNWWc8aAwHdfeCFEGI5M6T97Nnped11A0YpHH0X1MrljK31mzMBx06YFJnbZMghdMkWQKsgNp1Q+/TSq3g0ZX3jQzViPsAgRD9yhK1eGgwtJQoK6rcHNWGpYtyxHnz7I/jbohldIopK3rKDu2edmbKAfIbIPdXXbNtvzBWEs+VAPSshON2PmWN//nLqmWQ57M9euRaqmhXXbSg57A7rtazdj5vg8rInhoAUL2hVJkpwY+pHyppux24P1EMulk+4TJmDgSy+F1UOaK4nljoaff4avstKMTBGz667nnWf7ViiWThqKi9FQUQElJQXOQYPQ9cwzw1o6EUPTxr0ilhxwDhwIsXLQ7qWTvDz8auErA7gvl7G8gITILi6KkZbsEke7mEvgyuJohNjStRrqG5yPzvV6zSjvwKk1JJbfM267DX0feyyB3RV96L+99RZ+mTMnpCEO7G9IS8tqPisf9gaVo29fDPngg4id24i+e2JrgTc2Ys/EiX4Lln4oiN526/ptzf/fri1csZo6wF7kXmy90oHWqt5/H5WPP26JgICrXIy1HDlvd5BDv6efRq/rr7c0fCwJHPr8c3NbQPQSi8LKGRs+BmgRDEWIVBiQo3dvDF64EKkhVlStUHWm70UUY/nVV5tnGq0KAQ+7GJvbWi4igXIisHrg/PkxPYZm1diO+r703HMtAxuasBW4GfM7FhCaEBuhpGLsP2DuXDgHD+4oX3S4XYl9j/9jJLrMretrjwYd0WBrsWklSOly6jGTp6bFn3uuvBLiCJxUIXrJret/DiRrSYhIZMaJVnHJo9Bil06Qkn7ppVLYEl1I7ASWT5kifwaR8y1OwxiTXVr6W1iEiEp2E5n1uOoqDHjuuUT3tSV+MZr6efp0S7nWAgZwZS5jQbdNLXtIszKmqg8YkucLU4cPR+aqzp1gVDp+tzUbEidypQkRej0u14vgPOC97+ifibp5s5n2orOVmg8/NI9J1xYW2muaBBlCoS1CTFIkz4wMXrwYXc+Obfpfex6yJ31w9WqTiCPh7JYSLXPr+tUyFqNGyND8fKSdcIIMhriWEc8JQYRF1EioNgQ8mBOsQtQIGVZQkLALj0fWr29JryFm3uGWoyPbZfREjRB106aEOhJdu2ULRG84vG4dxDn0dpY9IJrp1vWFdvXYJ0RVvSDKtjIUzgHQmuXLse/hh83UG2Jy2eX0082/xe5dJIvImSWCs0Wgt0jPJALmGsrKImUidumZdmZlZTkdjhIr5GJta9Crr1qJtflejF72PfJIwDqOjAwzEl1EpIvtXjNhWeskZk1/g6hN8rI2ycyqq03nCxIi6PzWeCsJeCamCcyYql5vEC228nT/OXPQc8oUK7GW78OZYEkrj4Ug569AUV5063r4D5wmnLZuWcWa9joBllNTO8HYYhj549SpsXBbNGysFMl4Ap03D9eYNCG6po3iwPdWhsS9X2ztyhQxtt97//0yovEms6mJCFvJeGQaIU2IbO/o+/jjyLj5ZkvbB15/Hfuff95SLs4EGDh/E4oiekVdNLBJESLbO0RMlFjDEg/cYEXcog689hrEkbYEKZUgyifO8zXG8qP9nkZZQpZzYLKVA4+76y70efDBgGIiNklkZBN5phKg1IHzfCLKT2loyB9WVnYgVpgtCZHNIieyiA5dtcov5vfQp5/i4CefQKQx4rXx+94vDmwloFC8W0QxjHw1AkmRwyExJCHFbvepZBgiAY3lkVZxuKbfrFloKC1FfUmJGY8kiBBZPsMs4ryaB5xnReEtP+J8mXhnyAYi2urw+QrVkpJ9YeKMaLWghDBV7eUjWkVA6FOTTXDEyq4gwffrr5EAWAai6c17zoUDBqSnd++ezYlUbhjZJF53RNQNnKdzonSF826c83QQiZezVImTD+aV82oOVClEVQbn1Q6gijj/IV6cH8hRQQmROa8eCc8frYMD3zkN43a1pMTmhkM00MReZ7BQUqkJYMThcp5fbxjTR5SW/h6CfgyWQOdDnuNASzKUGPmkngOzcxh7Jkb24tZMG0I8qvpXED0ZS7QkXpFHNNut6/+Npd14tdVCSAeQIZbx89y6Ht5Z43j1aDtxtRCia5pIJXoTB6zXPcI3KpYbVhCwnBOtiNbyQ/jwOr6m3zNEvLSlUVEm0e+v8j4vEhA58BURLU9xOJZnFRVZ7qdEwmai6gg5MWSqmgNglEE0SlwBZDZ9nCEbzPkWKEoBDON7H+ffDy8pCZ1MJFG9FwXclksngWyW5eYeX+fzCXL8Uo93qa3dOrS8PCKzwyi0N+5VhkVI3LcqgQEmCYkz8pKEJAmJMw/EGZxkD0kSEmceiDM4yR4SZ4T8DzC3+7BnBMofAAAAAElFTkSuQmCC"
		}
	],
	"skippedUpdateVersion": null,
	"trustedCertificates": {},
	"isEachUpdatesSettingConfigurable": true,
	"isUpdatingEnabled": true,
	"externalProtocols": {}
}`

Notice only the few places being edited, not the rest of the document. Save and then reopen RocketChat. This will then connected you to your private server but ALSO update this config.json to fill in the rest of the setting with the correct settings. No need to manually fix the rest.

**Comment by tassoevan** [comment] 2020-10-03 14:57
Duplicate of #1764

**Closed by tassoevan** 2020-10-03 14:57 UTC
Labels: stat: duplicate

**Comment by TheDigitalEagle** [comment] 2020-10-03 15:10
Looks like this was marked as a duplicate of itself. :)

**Comment by kelirkenan** [comment] 2020-10-03 15:55
Can’t we reopen the issue? I can’t understand this is even possible 😅. Why would someone want to do this?

**Comment by tassoevan** [comment] 2020-10-03 20:26
🤦 Late night work, folks.

**Comment by TheDigitalEagle** [comment] 2020-10-03 20:42
Happens to us all.

**Comment by kelirkenan** [comment] 2020-10-05 06:36
> 
> 
> 🤦 Late night work, folks.

I understand you very well hehe. Thanks for working on this.
