### ISSUE TITLE
[bug] Crash to open Settings Page on Windows since 3.5.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#2146] opened 2021-09-07 03:25 UTC
**Describe the bug**
Desktop application was crashed a few times when I open Settings page

What operating system and which version? 
Window 10 1909
Which version of Rocket.Chat (Server)? 
3.16.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 
3.5.0
Is there any setting relevant changed? 
No

**To Reproduce**
1. Go to View - Settings
2. App crashed

**Expected behavior**
Desktop application works stable

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/132279601-13a43f51-f832-4c60-8d44-613e859ca444.png)

**Additional context**
App crashed not every time I open Settings

```
Имя сбойного приложения: Rocket.Chat.exe, версия: 3.5.0.0, метка времени: 0x612417bb
Имя сбойного модуля: Rocket.Chat.exe, версия: 3.5.0.0, метка времени: 0x612417bb
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000034645cb
Идентификатор сбойного процесса: 0x209c
Время запуска сбойного приложения: 0x01d7a394db7d1508
Путь сбойного приложения: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Путь сбойного модуля: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Идентификатор отчета: b1e2a5dd-dca9-48c8-9a10-9666f52fe348
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
```

**Comment by ankar84** [comment] 2021-09-09 08:33
Got it on 3.5.2 trying to change toggle for Flash Frame
```
Имя журнала:   Application
Источник:      Application Error
Дата:          09.09.2021 11:30:59
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     Comp
Описание:
Имя сбойного приложения: Rocket.Chat.exe, версия: 3.5.2.0, метка времени: 0x612417bb
Имя сбойного модуля: Rocket.Chat.exe, версия: 3.5.2.0, метка времени: 0x612417bb
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000034645cb
Идентификатор сбойного процесса: 0x2614
Время запуска сбойного приложения: 0x01d7a5494f332b69
Путь сбойного приложения: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Путь сбойного модуля: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Идентификатор отчета: fdc0ca7d-c4e7-42ed-8dba-5ec8e0c16db0
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-09T08:30:59.855239200Z" />
    <EventRecordID>158629</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Comp</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Rocket.Chat.exe</Data>
    <Data>3.5.2.0</Data>
    <Data>612417bb</Data>
    <Data>Rocket.Chat.exe</Data>
    <Data>3.5.2.0</Data>
    <Data>612417bb</Data>
    <Data>c0000005</Data>
    <Data>00000000034645cb</Data>
    <Data>2614</Data>
    <Data>01d7a5494f332b69</Data>
    <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data>
    <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data>
    <Data>fdc0ca7d-c4e7-42ed-8dba-5ec8e0c16db0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

```

**Comment by ankar84** [comment] 2021-09-10 02:26
3.5.3 still crash

**Comment by cazetto** [comment] 2021-09-10 17:16
Could anyone else confirm this issue? I tested it here on windows and I couldn't reproduce the problem.

**Comment by ankar84** [comment] 2021-09-15 05:05
Maybe that bug because on Windows shortcut `CTRL+I` creates _italic_ markdown in messagebox (2 underscore symbols)?
![image](https://user-images.githubusercontent.com/4023037/133373784-f09ba495-f02c-4aaf-a5a3-69eeb32b3233.png)
![image](https://user-images.githubusercontent.com/4023037/133373812-5f0d40c2-79c9-4feb-826d-56c5335eb7cf.png)

**Comment by ankar84** [comment] 2021-09-15 05:09
Also tested that bug on my personal laptop on Windows 21H1, same crash
```
Имя журнала:   Application
Источник:      Application Error
Дата:          15.09.2021 12:06:56
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     RV511
Описание:
Имя сбойного приложения: Rocket.Chat.exe, версия: 3.5.1.0, метка времени: 0x612417bb
Имя сбойного модуля: Rocket.Chat.exe, версия: 3.5.1.0, метка времени: 0x612417bb
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000034645cb
Идентификатор сбойного процесса: 0x768
Время запуска сбойного приложения: 0x01d7a9ef668c3298
Путь сбойного приложения: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Путь сбойного модуля: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
Идентификатор отчета: 2b0ca031-dc66-447d-8301-7fdd55ccbf20
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-15T05:06:56.9834791Z" />
    <EventRecordID>39929</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>RV511</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Rocket.Chat.exe</Data>
    <Data>3.5.1.0</Data>
    <Data>612417bb</Data>
    <Data>Rocket.Chat.exe</Data>
    <Data>3.5.1.0</Data>
    <Data>612417bb</Data>
    <Data>c0000005</Data>
    <Data>00000000034645cb</Data>
    <Data>768</Data>
    <Data>01d7a9ef668c3298</Data>
    <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data>
    <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data>
    <Data>2b0ca031-dc66-447d-8301-7fdd55ccbf20</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

```

**Comment by klou** [comment] 2021-09-23 15:55
Windows 10 Pro 1909
Rocket.Chat 3.5.5

I am able to reproduce this by repeatedly toggling between Settings and Server (5x or so).

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-09-23T15:50:40.741534900Z" /> 
  <EventRecordID>137955</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>XXXXXXXXXXX</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Rocket.Chat.exe</Data> 
  <Data>3.5.5.0</Data> 
  <Data>612417bb</Data> 
  <Data>Rocket.Chat.exe</Data> 
  <Data>3.5.5.0</Data> 
  <Data>612417bb</Data> 
  <Data>c0000005</Data> 
  <Data>00000000034645cb</Data> 
  <Data>e4</Data> 
  <Data>01d7b090e41c5278</Data> 
  <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data> 
  <Data>C:\Program Files\Rocket.Chat\Rocket.Chat.exe</Data> 
  <Data>7a039881-6c25-4a63-be2c-60d8905edb91</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by ankar84** [comment] 2021-12-03 05:04
[3.7.0 pre release](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.7.0) - crash still here

**Comment by jeanfbrito** [comment] 2021-12-03 09:34
This happens when you click on each tab to change of just using the keyboard shortcuts?

**Comment by ankar84** [comment] 2021-12-03 11:08
> This happens when you click on each tab to change of just using the keyboard shortcuts?

I did try only clicking tabs in Window menu.
Now I did try to switch all 3 windows (main chat server view, settings, downloads) using shortcuts and all stable, no crash.

But then clicked **Windows - Downloads** and crash immediately.

**Comment by Moku151** [comment] 2021-12-07 07:27
My rocket.chat client (Version 3.7.0) has the same behaviour on my Computer (winver 20H2). It crashes as soon as I open the Settings from the menu bar. With the Keyboard shortcut (CTRL + I) it works just fine.

**Comment by linefeed** [comment] 2021-12-15 10:30
Same happens here, after updating to version 3.7.0 (from 3.6.0?). Did not occur the last time I used it on previous version (a couple of months ago).

App crashes immediatey when opening the "Settings" or "Downloads" screen via the menu bar, but works when using keyboard shortcuts:

> Name der fehlerhaften Anwendung: Rocket.Chat.exe, Version: 3.7.0.0, Zeitstempel: 0x619588ac
> Name des fehlerhaften Moduls: Rocket.Chat.exe, Version: 3.7.0.0, Zeitstempel: 0x619588ac
> Ausnahmecode: 0xc0000005
> Fehleroffset: 0x00000000003b2c35
> ID des fehlerhaften Prozesses: 0x3694
> Startzeit der fehlerhaften Anwendung: 0x01d7f19cb1b96ec5
> Pfad der fehlerhaften Anwendung: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
> Pfad des fehlerhaften Moduls: C:\Program Files\Rocket.Chat\Rocket.Chat.exe
> Berichtskennung: f170ec29-87ca-4ce0-afdc-faa70e2c4e92
> Vollständiger Name des fehlerhaften Pakets: 
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
>

**Comment by jeanfbrito** [comment] 2021-12-28 03:40
This was fixed and I'm closing the issue. If it remains, please open it again.

**Closed by jeanfbrito** 2021-12-28 03:40 UTC
Labels: type: bug, plat: windows
