### ISSUE TITLE
Rocket.Chat.exe processes don't stop when app exits, and accumulate in task manager

### ISSUE THREAD

**Issue by pabrams** [RocketChat/Rocket.Chat.Electron#935] opened 2018-10-17 13:18 UTC
## My Setup
- Operating System:  Windows 7
- App Version:  2.14.0
- Installation type: portable exe

- [X ] I have tested with the latest version (according to your Releases page)
- [ ] I can simulate the issue easily  ( I don't need to "simulate" it because I can reproduce it. )

## Description
1. Open app. 
2. Close app. 
3. Open app.
4. Close app.
5. repeat a few times

![image](https://user-images.githubusercontent.com/1376688/47088782-47642580-d1ed-11e8-8e74-3c74e03b09da.png)

### Current Behavior
One or more new processes are started each time the app is opened, and are not killed when the app is closed, nor the next time it opens.

### Expected Behavior
The app should only run the processes it needs, and should kill them on exit.

**Comment by tassoevan** [comment] 2018-10-17 15:15
@crazy-max Are you the maintainer of https://github.com/portapps/rocketchat-portable, right? Any clue about what is happening here?

**Comment by crazy-max** [comment] 2018-10-17 15:34
@tassoevan Yeah i'm maintainer, I will check this out
@pabrams Can you open an issue on  this repo please : https://github.com/portapps/rocketchat-portable

**Comment by crazy-max** [comment] 2018-10-24 20:12
@pabrams I cannot reproduce your issue in my environment on Windows 7 / 10 using the [Portapps version of RocketChat](https://github.com/portapps/rocketchat-portable).

And indeed there are children process but they are killed when you exit the app :

![image](https://user-images.githubusercontent.com/1951866/47458447-d79bff00-d7d9-11e8-9487-48a5815bf8a0.png)

**Comment by crazy-max** [comment] 2018-11-12 20:59
@tassoevan I think we can close this issue

**Closed** 2018-11-12 23:46 UTC
Labels: plat: windows, type: bug
