### ISSUE TITLE
After updating, same update is offered again

### ISSUE THREAD

**Issue by AndreSomers** [RocketChat/Rocket.Chat.Electron#924] opened 2018-10-12 05:08 UTC
(moved from https://github.com/RocketChat/Rocket.Chat/issues/12313)
### Description:

On starting up the Rocket.Chat client, I get a message an update is available. I click to accept the update, install the update (for only this user) and it gets installed which restarts the client. No errors are shown. On the next start of the client, the same update available message for the same versions is shown again.  

### Steps to reproduce:

1. Run an outdated client
2. Start up the client to get the update available dialog
3. Accept the update, and install it
4. On restart, observe the update available dialog appearing again.

### Expected behavior:

I would have expected the update to be properly installed and the same update just installed not being offered again.

### Actual behavior:

See above: same update is offered again for the same outdated version of Rocket.Chat.
![snap 2018-10-11 at 08 55 33](https://user-images.githubusercontent.com/10531631/46786118-353d3f80-cd34-11e8-92b4-899c21cc04fa.png)

### Server Setup Information:

Rocket.Chat installed version: 2.13.1
Rocket.Chat offered update version: 2.14.0

### Additional context

Windows 10, all updates installed
I have also seen this in an earlier version.

**Comment by JohanLeDong** [comment] 2018-10-12 09:16
The same

**Comment by tassoevan** [comment] 2018-10-13 14:49
Duplicate of #868 (Windows) and #894 (MacOS).

**Closed by tassoevan** 2018-10-13 14:49 UTC
