### ISSUE TITLE
Rocket.Chat application on Mac does not respect system setting for Do-Not-Disturb

### ISSUE THREAD

**Issue by jaakkocsc** [RocketChat/Rocket.Chat.Electron#1313] opened 2019-09-11 09:27 UTC
## My Setup
- Operating System: macOS 10.14.6
- App Version: 2.15.5
- Installation type: Mac App Store

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocket.Chat application does not respect system setting for Do-Not-Disturb (option-click Notification center icon at system menu bar).

### Current Behavior
Regardless of the D-n-D setting of the system, Rocket.Chat still plays a sound and bounces the Dock icon for incoming messages. It does not show the notification message, though, and correctly displays a message count on Dock icon if D-n-D is enabled.

### Expected Behavior
New messages should not notify user (play sound, bounce dock icon, show notification message) when system D-n-D is enabled, but only display message count on Dock icon.

**Comment by joewiz** [comment] 2020-07-02 08:29
Is this a duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/873?

**Comment by jeanfbrito** [comment] 2022-01-12 00:58
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:58 UTC
