### ISSUE TITLE
PDF files open in a window without back or close button.

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat.Electron#1982] opened 2021-02-25 07:18 UTC
## My Setup

- Operating System: Windows 10
- App Version: 3.1.1
- Installation type: exe
- Server: 3.11.1 / 3.12.rc-1 (open.rocket.chat)

- [x ] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
PDF files open in a window without back or close button.

- upload a pdf file
- click pdf title in message

### Current Behavior
- window without back or close button
![grafik](https://user-images.githubusercontent.com/49910825/109116604-1c852700-7741-11eb-978e-a1026f7d2194.png)
- clicking the server in the server list doesn't work either

### Expected Behavior
- window with back or close button

**Comment by urosino** [comment] 2021-03-07 20:05
Could be duplicate of #1979

**Comment by jeanfbrito** [comment] 2022-01-10 18:34
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:34 UTC
