### ISSUE TITLE
Edit message option not visible in the context menu

### ISSUE THREAD

**Issue by redRolf** [RocketChat/Rocket.Chat.Electron#2429] opened 2022-06-09 08:45 UTC
**Describe the bug**
The edit message button is only displayed after some time has passed. Initially after posting a message the edit button is not displayed, it takes some time until it is displayed. Only users who do not have the `edit-message` permission are affected by this. Editing using the up arrow still works.

What operating system and which version?
* MacOS 12.4
Which version of Rocket.Chat (Server)?
* Server 4.8.0
Which version of Rocket.Chat.Electron (Electron/Desktop)?
* Desktop 3.8.7 
* Browser Chrome Version 102.0.5005.61 (Official Build) (arm64)
Is there any setting relevant changed?
* No

**To Reproduce**
1. Be a user who does not have the `edit-message` permission
2. Send a message 
3. Try to edit the message -> by navigating to the 3 dots on the right side and click to edit message button (no button)
4. Edit the message using the up arrow this works.
5. After some time the option to edit message will be displayed.

**Expected behavior**
The user immediately sees the option in the context menu to edit the message

**Screenshots**

https://user-images.githubusercontent.com/42872307/172804951-9a402a49-e62c-4dca-8885-187539d1ce2a.mp4

**Additional context**
This happens both in the browser and in the desktop client. Users running the 3.8.6 client are not affected by this. This is only happening to users running the 3.8.7 client.

**Comment by ankar84** [comment] 2022-06-10 05:05
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/25478

**Closed by ankar84** 2022-06-10 05:05 UTC
