### ISSUE TITLE
Not focusing on messages opened by it's link

### ISSUE THREAD

**Issue by beloniki** [RocketChat/Rocket.Chat.Electron#2155] opened 2021-09-09 13:09 UTC
**Describe the bug**
A message, that should be showed by its link following, is out of the messages field.

What operating system and which version? Win10 (20H2), MacOS (11.5.2)
Which version of Rocket.Chat (Server)? 3.18.1
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.2
Is there any setting relevant changed? No

**To Reproduce**
1. Get the message link
2. Send it
3. Click it

**Expected behavior**
Displaying the message within the message field. Maybe highlight it.

**Additional context**
Browser version is focusing on the message.

**Comment by cazetto** [comment] 2021-09-10 17:33
Could anyone else confirm this issue? I tested on windows 10 and macos 11.2 and I couldn't reproduce it.

I've copied the link from a message, sent it to the author of the message, and they can both open it. Obviously, anyone who isn't in the conversation won't be able to visualize it, but I don't think that's the case.

**Comment by tmartincpp** [comment] 2021-09-16 14:20
I don't reproduce this issue, I have the same behavior between RC Electron 3.5.4 and Chromium 90.0.4430.212 (both on Debian 10): it seems that clicking on a message link try to put the message in the middle of the page.

beloniki: maybe your issue is related to the fact that most of your content are attached files ?
Maybe they take more place in the screen so it gets messy ?


In any case I do agree that having the message highlighted would be very nice by making it easier to find.

**Comment by beloniki** [comment] 2021-09-16 14:49
@tmartincpp that's a good idea. I checked this, and I could reproduce this issue with messages that contain some attachments like image or poll.

**Comment by jeanfbrito** [comment] 2022-01-10 13:56
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 13:56 UTC
