### ISSUE TITLE
Notifications not show in windows client 1.0.0

### ISSUE THREAD

**Issue by kkachura** [RocketChat/Rocket.Chat.Electron#107] opened 2016-02-24 06:53 UTC
In Settings Desctop Notifications is on, but not showing when press "Test desktop notifications"
(Windows 8.1)
##

**Comment by alfredbez** [comment] 2016-03-21 09:01
Is this a duplicate of #55 ?

**Comment by kkachura** [comment] 2016-03-21 13:35
Most likely the reason for the same

**Comment by rodrigok** [comment] 2016-03-21 19:20
@alfredbez No, Win 7 does not have native notifications, so they are different issues.

**Comment by engelgabriel** [comment] 2017-01-11 02:50
Please try again with version 2.1.0 and reopen if problem persist.

**Closed by engelgabriel** 2017-01-11 02:50 UTC
Labels: feat: notifications, plat: windows, type: bug

**Comment by SteveOnorato** [comment] 2017-01-12 02:07
I just tried 2.1.0 on Windows 8 Enterprise and there are still no native notifications.  (It didn't work for me with 1.3.1 either.)

I downloaded the installer from https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.1.0/rocketchat-Setup-2.1.0.exe
