### ISSUE TITLE
Desktop notifications don't work

### ISSUE THREAD

**Issue by BreakfastSerial** [RocketChat/Rocket.Chat.Electron#1168] opened 2019-04-02 06:21 UTC
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Desktop notifications never appear, not even with `TEST DESKTOP NOTIFICATIONS`.

I've checked all suggested fixes from this issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/522

 - `My Account -> Preferences -> Messages -> Show Desktop Notifications For`; Set to all
 - `Max Room Members Before Disabling All Message Notifications`; Set to more than we have users
 - `Windows 10 notifications`; enabled
 - `Administration > Accounts > Default User Preferences > "Notification Duration"`; set long enough

**Comment by tassoevan** [comment] 2019-04-02 14:37
@BreakfastSerial Do the notifications work when accessing the server from a web browser? Also, could you please inform you Rocket.Chat server version?

**Comment by BreakfastSerial** [comment] 2019-04-04 06:26
@tassoevan `TEST DESKTOP NOTIFICATIONS` from a browser does not trigger a notification either. Rocket.Chat Server is version 0.74.2.

I've also tried different users.

**Comment by tassoevan** [comment] 2019-04-04 14:44
It's a server bug patched on version 0.74.3 (#13284). I'm closing this issue since is not caused by the desktop client, but please let me know if you still have issues after updating the server.

**Closed by tassoevan** 2019-04-04 14:44 UTC
