### ISSUE TITLE
Login issue with 2-Factor authentication from 2.15.0 to 2.15.3 versions

### ISSUE THREAD

**Issue by jbogdanov** [RocketChat/Rocket.Chat.Electron#1226] opened 2019-05-14 11:20 UTC
## My Setup
- Operating System: Windows 10 Pro 1809, 17763.475 build
- App Version: Windows, 2.15.3
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I connect to custom IM service provided by our partner using 2-Factor authentication. I was able to login successfully using 2.14.7 version and all the 2.15.* throwing me "Houston, we have a problem error" when I successfully put user name, password. For a while one time secret text box appearing (for less than a second) and then instantly this error is throwing.
Moreover, I am able to login via google chrome and via iPhone using latest version of app.
![huston](https://user-images.githubusercontent.com/9380590/57694013-4dbb6280-7653-11e9-9cff-c89709206ff3.png)

### Current Behavior
I am trying to connect to custom IM service.
I type my user name, password, clicking "next".
For a while (less than 1 second) I see one-time secret text box and then instantly is throwing "Houston" error.

### Expected Behavior
I am able to type to one-time secret text box and to login

**Comment by janmashat** [comment] 2019-06-18 10:05
This issue is a duplicate of: #1163
Another (probably related) issue I've noticed is that the cursor is missing in the SSO username/password text box fields in 2.15.*

**Comment by jeanfbrito** [comment] 2022-01-12 00:32
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:32 UTC
