### ISSUE TITLE
Status not updated since Server v. 3.12.1

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat.Electron#1990] opened 2021-03-12 15:36 UTC
## My Setup

- Operating System: Win 10
- App Version: 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The status of user isn't updated. only a restart of the application update the status

### Current Behavior
The status doesn't change since the start of application

### Expected Behavior
Status should be updated automatically

**Comment by ankar84** [comment] 2021-03-16 06:27
Could be related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1812

**Comment by Nono-m0le** [comment] 2021-03-16 06:30
Doesn't seems so.
user sees their own status correctly and Ctrl + R update /display it correctly for everyone.

**Comment by Nono-m0le** [comment] 2021-05-03 12:39
This is still happening with server version 3.13.2 (snap)

**Comment by Nono-m0le** [comment] 2021-05-17 10:51
There is still something wrong : 
On this screenshot, we use both Client v. 3.2.2
Server (snap) v. 3.13.2 : 
![image](https://user-images.githubusercontent.com/3726435/118477058-91e41080-b70e-11eb-98a1-807bb9e00ab8.png)

**Comment by ankar84** [comment] 2021-05-17 10:56
> Server (snap) v. 3.13.2

That is the root cause of your problem. There was both rocket chat server and desktop client user status issues. 
Client bug fixed in 3.2.2
Server bug should be fixed in 3.14

**Comment by jeanfbrito** [comment] 2022-01-12 02:35
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 02:35 UTC
