### ISSUE TITLE
Strange paint issue when app gets focus (occasional occurrence)

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat.Electron#626] opened 2017-12-05 12:00 UTC
## My Setup
- Operating System: MacOS 10.13.1
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Seems to happen sporadically, usually when the rocket.chat app becomes the focused window after not being looked at for a bit. Once it kicks in a refresh (Command + R) clears it but it often comes back. A restart of the app keeps it at bay a bit longer (anecdotal, no evidence of this). 

The image below shows the problem:
![rocketchat-grey-oddness](https://user-images.githubusercontent.com/76320/33605939-fc36641c-d9bb-11e7-95fd-ea009c5629f1.jpg)

### Current Behavior
App window has grey boxes painted over it but only sometimes happens when bringing app focus.

### Expected Behavior
App behaves normally.

**Comment by tanc** [comment] 2017-12-05 17:30
One of our users is reporting this behaviour on his Android app, so I wonder if this is an upstream issue with rocket.chat? I'll try running it in the browser for a day and see if it repeats there.

**Comment by gdelavald** [comment] 2017-12-05 18:06
I was able to reproduce this on the Electron app on Mac, but this happening on the Android is something that would be really weird.
Let me know if you find other cases of this happening.

**Comment by finnlewis** [comment] 2017-12-06 09:27
After updating Rocket on my Galaxy S6 yesterday, it is now unusable, looking similar to the issue @tanc reports above. Here's a screenshot
![screenshot_20171206-092459](https://user-images.githubusercontent.com/326588/33654304-99ae8d7c-da67-11e7-853e-37af6d65a6b5.jpg)

**Comment by tanc** [comment] 2017-12-06 11:43
I've been using rocket.chat in a Chrome tab all day and haven't been able to reproduce the issue.

**Comment by gdelavald** [comment] 2017-12-06 13:26
@finnlewis please report this issue in the appropriate repository (Rocket.Chat.Android since it's an Android bug).

@tanc this seems to occur only on the Electron app, thanks for confirming.

**Comment by tanc** [comment] 2017-12-11 12:35
@gdelavald any idea what is causing this? I had a good 24 hours without the bug occurring and then today it seemed to co-incide with high CPU use of Window Server, requiring a reboot. I'll keep monitoring for any clues, but if you already know what causes the issue then I'll keep quiet :wink:

**Comment by tanc** [comment] 2017-12-28 08:30
I tested this app again after a couple of weeks using Rocket.chat in a Chrome tab and can confirm this issue does kick off a nasty Window Server spike in CPU. Once the paint issue occurs its impossible to get the Window Server CPU usage down even after quitting this app. After a short while the system becomes extremely sluggish and a reboot is required.

**Comment by jeanfbrito** [comment] 2022-01-10 17:41
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 17:41 UTC
Labels: type: bug
