### ISSUE TITLE
Uploaded images not showing up

### ISSUE THREAD

**Issue by Kyoshir0** [RocketChat/Rocket.Chat.Electron#408] opened 2017-03-24 12:07 UTC
## My Setup
Fedora 25, Windows 10, MacOS 
app version: 2.5.0 and  2.2.0-1 

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

In rocket.chat app uploaded images are not showing up.
Everything is working fine under chrome, firefox and edge. 
Issue occurred after rocket.chat server update to 0.54.0 version.

#### Current Behavior

![rocketchat](https://cloud.githubusercontent.com/assets/4522608/24293370/b512b9b2-1091-11e7-8d90-dca893427471.png)
After clicking on the place where the image should be I'm getting error: This image could not be loaded

#### Expected Behavior

Images should be displayed

**Comment by graywolf336** [comment] 2017-03-24 12:25
Duplicate of #406, update your instance to the latest version of Rocket.Chat.

**Closed by graywolf336** 2017-03-24 12:25 UTC
