### ISSUE TITLE
Search feature does not search on attachments names

### ISSUE THREAD

**Issue by nadjibnet** [RocketChat/Rocket.Chat.Electron#2130] opened 2021-08-26 10:03 UTC
Hi,

When we add some attachments, will could not apply a search (CTRL+F) to find them by it attachment name (I'm not asking to find them by filename but attachment name),.

Server Running on Ubuntu 20.04, Client app on Android and Windows 10.
Rocket.Chat (Server): 3.17.1
Rocket.Chat.Electron (Electron/Desktop) 3.2.4
Is there any setting relevant changed. No

**To Reproduce**
1. Go to any private discussion or on any channel.
2. Add and Send an attachment like an image as flow:
![image](https://user-images.githubusercontent.com/39797899/130942473-64806368-8e06-4ec0-8641-200e5c8f0ec6.png)

3. Add some more attachment with names.
4. using search button or CTRL+F: Search for an name of attachment previously added.
5. You can see that the search feature does not look at attachments name.

**Expected behavior**
Rocket chat search on attachments names

**Comment by ankar84** [comment] 2021-09-07 07:24
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23114
And I think, that issue itself not with Electron app, but with RocketChat in general.

**Comment by jeanfbrito** [comment] 2022-08-04 21:49
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-08-04 21:49 UTC
Labels: stat: duplicate
