### ISSUE TITLE
Notifications in Windows crashes the program.

### ISSUE THREAD

**Issue by teodoro-vargas** [RocketChat/Rocket.Chat.Electron#997] opened 2018-11-19 17:29 UTC
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by tassoevan** [comment] 2018-11-19 17:49
Duplicate of #977 and #991.

**Closed by tassoevan** 2018-11-19 17:49 UTC
Labels: feat: notifications, plat: windows, stat: duplicate, type: bug
