### ISSUE TITLE
Windows client: Unable to download files from channel file list

### ISSUE THREAD

**Issue by danila-kovalev** [RocketChat/Rocket.Chat.Electron#678] opened 2018-03-05 12:19 UTC
## My Setup
- Operating System: win-clients (win8.1x64 and win10)
- App Version: v.2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
It is not possible to download files from "files list" of the channel.
This is valid for win-client only
Using web-browser as a client or apple-mobile-app - there are no such problem

### Current Behavior

 1. open "File list" of the channel -> files of the channel are displayed ok (suppose that one file is *.odt document, i.e. any other attach which can be open by external (to RChat client) app)
 2. click on *.odt
 3. no action

exception: if you click on picture file (*.jpg or *.png) - it is displayed in RocketChat client

### Expected Behavior
User expect File->Save dialog window
Note: it is possible to download this file if you find it in discussion thread
But if the discussion thread is huge it is quite painfull and non-user-friendly to look for it scrolling back and forth through tons of text lines.

**Comment by Yuu94** [comment] 2018-03-27 04:26
Is the problem solved?
This problem is solved by modifying the RocketChat server.

**Comment by zookah** [comment] 2018-04-03 12:30
@Yuu94 What changes should be done on the server side?

**Comment by Yuu94** [comment] 2018-04-04 00:11
The cause is in the Html file which displays the list of Rocket.Chat.

 There is an a tag in line 16 of Rocket.Chat-develop/packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html .
I think that this problem will be solved by changing the target attribute of a tag from "_blank" to "_self".

**Comment by Yuu94** [comment] 2018-04-04 00:13
@zookah The cause is in the Html file which displays the list of Rocket.Chat Server.


There is an a tag in line 16 of Rocket.Chat-develop/packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html.

I think that this problem will be solved by changing the target attribute of a tag from "_blank" to "_self".

**Comment by zookah** [comment] 2018-04-04 14:30
@Yuu94 Thank you!

**Comment by GoetheG** [comment] 2018-04-08 08:11
When I see all the problems with files and open source software in general it gets me thinking why some of those companies do not work together. For example Nextcloud and Rocket.Chat. It diesn’t have to be Nextcloud, that is just an example. ownCloud is fine by me. And also Rocket.Chat. Also Open-XChange and Kopano.

**Comment by danila-kovalev** [comment] 2018-04-09 10:29
Right now the problem still exists. I do not have enough tech. expertise to assess fix propose by Yuu94, but seem to be this is a proper direction. This problem is not so critical to experiment with self-made manual modification (risking it will be fixed in the other way), so I shall wait for the fix bundled in server or client or both.

**Comment by fbartels** [comment] 2018-04-10 12:31
@GoetheG this ticket is afaik not really about file support in Rocket Chat, but more about a bug in the rocket chat client that does not properly download files.

But since you mentioned Kopano: we at Kopano recently joined the document foundation advisory board in an effort to bring easy document viewing and editing to users (based on LibreOffice Online). See https://kopano.com/news-and-press-releases/kopano-to-bring-libreoffice-online-to-its-enterprise-audience/ for more details, there will also be a followup announcement quite soon.

**Comment by Datseris** [comment] 2018-05-02 21:12
Problem still exists (Windows 10)

**Comment by zookah** [comment] 2018-05-02 21:19
Same here (macOS and Manjaro Linux): Rocket.chat+ version 2.10.5

**Comment by tassoevan** [comment] 2018-07-19 15:11
I'm closing this issue because it is not inside the desktop client. There was an [issue](https://github.com/RocketChat/Rocket.Chat/issues/9557) in Rocket.Chat that reflected this behavior in all desktop clients.

The correction is on track to be deployed in 0.67.0 release.

**Closed by tassoevan** 2018-07-19 15:11 UTC
