### ISSUE TITLE
Right-clicking on link could have "Copy URL" option

### ISSUE THREAD

**Issue by tadeu** [RocketChat/Rocket.Chat.Electron#606] opened 2017-11-13 15:00 UTC
In the Windows client, this option is missing: right-clicking an URL and copying the URL to the clipboard (like "Copy link address" from Chrome).

**Comment by engelgabriel** [comment] 2018-08-14 16:01
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/215

**Closed by engelgabriel** 2018-08-14 16:01 UTC
Labels: type: enhancement
