### ISSUE TITLE
Disappearing chat box upon resize.

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#401] opened 2017-03-20 09:26 UTC
## My Setup

 - __My OS name and version__: Mac OS Sierra 
 - __My current app version__: 2.5.0 

- [ x] I have tested with the latest application version
- [ x] I can simulate the issue easily

## Description

On mac, I have several colleagues that do not want rocketchat to take up a large amount of screen space, as a result they resize the rocket chat window. In resizing the window there is a bug where the message bar at the bottom of the client disappears, a server reload of the client is the only way to fix this which is quite annoying. 

#### Expected Behavior

Message Box should become smaller and stay on screen not disappear and force the user to restart the application.

**Comment by jeff-hobbs** [comment] 2017-03-29 00:26
If you `rm ~/Library/Application Support/Rocket.Chat+/Preferences` you get message line and right action bar back, but the minute you try and resize again they disappear.

**Comment by alexbrazier** [comment] 2017-05-06 16:12
@oliver-bowman @jeff-hobbs Could you confirm that this is still an issue with the latest client and server?

When I resize it looks like this:
![image](https://cloud.githubusercontent.com/assets/5689874/25773959/121f2b9a-327f-11e7-9fd7-87d089770f89.png)

**Comment by jeff-hobbs** [comment] 2017-05-06 17:23
@alexbrazier I can confirm that testing this with 2.7 shows working behavior. The text input box does not disappear, and the UI shows proper responsive behavior when shrunk and expanded. Looks fixed to me. Thx!

**Comment by alexbrazier** [comment] 2017-05-06 17:39
Great, thanks for responding. I'm closing this, but if its still an issue for anyone it can be reopened.

**Closed by alexbrazier** 2017-05-06 17:39 UTC
Labels: stat: waiting response
