### ISSUE TITLE
Version 3.8.16 does not work on macos M1 (via app store)

### ISSUE THREAD

**Issue by dup2** [RocketChat/Rocket.Chat.Electron#2583] opened 2023-01-11 12:37 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macos 12.6.2

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.8.16

### Rocket.Chat Server Version

4.8

### Describe the bug

No chat window at all after updating from 3.8.15 via app store. Can not use the application - it starts (top level navigation ok, can show the about dialog) but do not see the chat window, even after restarting the application.

### How to Reproduce

Restart the application

### Describe your Expected behavior

Works as before

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by ssbmaccom** [comment] 2023-01-11 15:06
I actually ran into the same issue with latest RocketChat version on macOS 12.6.1
The Electron task "RocketChat Helper(Renderer)" is crashing (that's why I as developer do not like Electron). Without this task, the app is not able to display the window.

See below crash report:

```
{"app_name":"Rocket.Chat Helper (Renderer)","timestamp":"2023-01-11 15:54:26.00 +0100","app_version":"","slice_uuid":"4c4c443f-5555-3144-a179-1590ef36f28f","build_version":"102","platform":1,"bundleID":"chat.rocket.electron.helper.Renderer","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.2 (21G320)","incident_id":"DE515A91-6357-47BE-8DCB-88735008960A","name":"Rocket.Chat Helper (Renderer)"}
{
  "uptime" : 20000,
  "procLaunch" : "2023-01-11 15:54:26.6214 +0100",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac21,1",
  "procStartAbsTime" : 483082652356,
  "coalitionID" : 24385,
  "osVersion" : {
    "train" : "macOS 12.6.2",
    "build" : "21G320",
    "releaseType" : "User"
  },
  "captureTime" : "2023-01-11 15:54:26.6596 +0100",
  "incident" : "DE515A91-6357-47BE-8DCB-88735008960A",
  "bug_type" : "309",
  "pid" : 16018,
  "procExitAbsTime" : 483083563151,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Rocket.Chat Helper (Renderer)",
  "procPath" : "\/Applications\/Rocket.Chat.app\/Contents\/Frameworks\/Rocket.Chat Helper (Renderer).app\/Contents\/MacOS\/Rocket.Chat Helper (Renderer)",
  "bundleInfo" : {"CFBundleVersion":"102","CFBundleIdentifier":"chat.rocket.electron.helper.Renderer"},
  "storeInfo" : {"deviceIdentifierForVendor":"D40D41C2-C86A-5123-BC46-7C8E79DCF009","thirdParty":true},
  "parentProc" : "Rocket.Chat",
  "parentPid" : 16015,
  "coalitionName" : "chat.rocket",
  "crashReporterKey" : "E2F6717D-710F-2A8E-4B8C-B6A19FF54E6E",
  "responsiblePid" : 16015,
  "responsibleProc" : "Rocket.Chat",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001148f44a0","rawCodes":[1,4639900832],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":16018},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":216715,"threadState":{"x":[{"value":0},{"value":18446744073709551615},{"value":7},{"value":6},{"value":262144},{"value":1},{"value":1},{"value":80},{"value":13},{"value":8654330656,"symbolLocation":0,"symbol":"errno"},{"value":4667709148,"symbolLocation":17512736,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)"},{"value":12},{"value":18944},{"value":4294967295},{"value":4341805600},{"value":1243033618},{"value":7161574484,"symbolLocation":0,"symbol":"__error"},{"value":2301},{"value":0},{"value":268435456},{"value":1},{"value":5368709120},{"value":268435456},{"value":5117153120},{"value":5117153208},{"value":5117153144},{"value":4744415824,"symbolLocation":356408,"symbol":"vtable for v8::Extension"},{"value":1},{"value":5117152632}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4639900764},"cpsr":{"value":2684358656},"fp":{"value":6125264944},"sp":{"value":6125264848},"esr":{"value":4060086272,"description":"(Breakpoint) brk 0"},"pc":{"value":4639900832,"matchesCrashFrame":1},"far":{"value":4630078504}},"name":"CrRendererMain","queue":"com.apple.main-thread","frames":[{"imageOffset":18023584,"symbol":"v8::internal::CodeRange::~CodeRange()","symbolLocation":476,"imageIndex":0},{"imageOffset":18023516,"symbol":"v8::internal::CodeRange::~CodeRange()","symbolLocation":408,"imageIndex":0},{"imageOffset":18024848,"symbol":"v8::internal::CodeRange::~CodeRange()","symbolLocation":1740,"imageIndex":0},{"imageOffset":18329592,"symbol":"v8::internal::Heap::AllocatedExternalMemorySinceMarkCompact()","symbolLocation":1032,"imageIndex":0},{"imageOffset":17891200,"symbol":"v8::internal::Isolate::Init(v8::internal::SnapshotData*, v8::internal::SnapshotData*, v8::internal::SnapshotData*, bool)","symbolLocation":1324,"imageIndex":0},{"imageOffset":17894196,"symbol":"v8::internal::Isolate::InitWithSnapshot(v8::internal::SnapshotData*, v8::internal::SnapshotData*, v8::internal::SnapshotData*, bool)","symbolLocation":12,"imageIndex":0},{"imageOffset":22684652,"symbol":"v8::internal::Checksum(v8::base::Vector<unsigned char const>)","symbolLocation":944,"imageIndex":0},{"imageOffset":16742352,"symbol":"v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&)","symbolLocation":356,"imageIndex":0},{"imageOffset":65981592,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":37662428,"imageIndex":0},{"imageOffset":65981080,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":37661916,"imageIndex":0},{"imageOffset":78630092,"symbol":"node::AsyncResource::get_async_id() const","symbolLocation":12315928,"imageIndex":0},{"imageOffset":78631280,"symbol":"node::AsyncResource::get_async_id() const","symbolLocation":12317116,"imageIndex":0},{"imageOffset":66099048,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":37779884,"imageIndex":0},{"imageOffset":96629572,"symbol":"node::CommonEnvironmentSetup::event_loop() const","symbolLocation":17127840,"imageIndex":0},{"imageOffset":96839012,"symbol":"node::CommonEnvironmentSetup::event_loop() const","symbolLocation":17337280,"imageIndex":0},{"imageOffset":96835072,"symbol":"node::CommonEnvironmentSetup::event_loop() const","symbolLocation":17333340,"imageIndex":0},{"imageOffset":96838628,"symbol":"node::CommonEnvironmentSetup::event_loop() const","symbolLocation":17336896,"imageIndex":0},{"imageOffset":96870340,"symbol":"node::CommonEnvironmentSetup::event_loop() const","symbolLocation":17368608,"imageIndex":0},{"imageOffset":4729704,"symbol":"v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*)","symbolLocation":14184,"imageIndex":0},{"imageOffset":4732196,"symbol":"v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*)","symbolLocation":16676,"imageIndex":0},{"imageOffset":4726844,"symbol":"v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*)","symbolLocation":11324,"imageIndex":0},{"imageOffset":4728052,"symbol":"v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*)","symbolLocation":12532,"imageIndex":0},{"imageOffset":2087284,"symbol":"ElectronMain","symbolLocation":128,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":1}]},{"id":216735,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]},{"id":216739,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":2}]},{"id":216743,"name":"ThreadPoolServiceThread","frames":[{"imageOffset":54104,"symbol":"kevent64","symbolLocation":8,"imageIndex":3},{"imageOffset":44987964,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16668800,"imageIndex":0},{"imageOffset":44701908,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16382744,"imageIndex":0},{"imageOffset":44492708,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16173544,"imageIndex":0},{"imageOffset":44806832,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16487668,"imageIndex":0},{"imageOffset":44722312,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16403148,"imageIndex":0},{"imageOffset":44807204,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16488040,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]},{"id":216744,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":3},{"imageOffset":44964028,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16644864,"imageIndex":0},{"imageOffset":44779764,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16460600,"imageIndex":0},{"imageOffset":44782120,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462956,"imageIndex":0},{"imageOffset":44781392,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462228,"imageIndex":0},{"imageOffset":44781240,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462076,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]},{"id":216745,"name":"ThreadPoolBackgroundWorker","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":3},{"imageOffset":44964028,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16644864,"imageIndex":0},{"imageOffset":44779764,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16460600,"imageIndex":0},{"imageOffset":44781688,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462524,"imageIndex":0},{"imageOffset":44781260,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462096,"imageIndex":0},{"imageOffset":44781108,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16461944,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]},{"id":216746,"name":"Chrome_ChildIOThread","frames":[{"imageOffset":54104,"symbol":"kevent64","symbolLocation":8,"imageIndex":3},{"imageOffset":44987964,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16668800,"imageIndex":0},{"imageOffset":44701908,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16382744,"imageIndex":0},{"imageOffset":44492708,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16173544,"imageIndex":0},{"imageOffset":44806832,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16487668,"imageIndex":0},{"imageOffset":65524924,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":37205760,"imageIndex":0},{"imageOffset":44807204,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16488040,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]},{"id":216747,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":3},{"imageOffset":44964028,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16644864,"imageIndex":0},{"imageOffset":44779764,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16460600,"imageIndex":0},{"imageOffset":44781688,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462524,"imageIndex":0},{"imageOffset":44781392,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462228,"imageIndex":0},{"imageOffset":44781240,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16462076,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]},{"id":216748,"name":"GpuMemoryThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":3},{"imageOffset":44964028,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16644864,"imageIndex":0},{"imageOffset":44963700,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16644536,"imageIndex":0},{"imageOffset":44372472,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16053308,"imageIndex":0},{"imageOffset":44701908,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16382744,"imageIndex":0},{"imageOffset":44492708,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16173544,"imageIndex":0},{"imageOffset":44806832,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16487668,"imageIndex":0},{"imageOffset":44807204,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16488040,"imageIndex":0},{"imageOffset":44912652,"symbol":"v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)","symbolLocation":16593488,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":2},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4621877248,
    "CFBundleIdentifier" : "com.github.Electron.framework",
    "size" : 120995840,
    "uuid" : "4c4c447d-5555-3144-a149-d43bae7e8378",
    "path" : "\/Applications\/Rocket.Chat.app\/Contents\/Frameworks\/Electron Framework.framework\/Versions\/A\/Electron Framework",
    "name" : "Electron Framework",
    "CFBundleVersion" : "21.3.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4342218752,
    "size" : 393216,
    "uuid" : "f0564ec5-bf9c-3107-82b3-485f927b489f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7161794560,
    "size" : 53248,
    "uuid" : "63c4eef9-69a5-38b1-996e-8d31b66a051d",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7161565184,
    "size" : 229376,
    "uuid" : "b71e7783-80bc-36bb-af5d-579344d68742",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  }
],
  "sharedCache" : {
  "base" : 7158497280,
  "size" : 3144761344,
  "uuid" : "be7fe6ad-4560-3ae2-883e-432f78b45062"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=457.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=457.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nDispatch continuations            64.0M        1 \nKernel Alloc Once                   32K        1 \nMALLOC                            88.2M       26 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)\nMach message                        32K        2 \nMemory Tag 253                    32.0G       41 \nMemory Tag 255                     1.1T       13 \nMemory Tag 255 (reserved)         1024K        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        9 \nStack                             57.1M        9 \n__AUTH                            2597K      308 \n__AUTH_CONST                      20.3M      500 \n__CTF                               756        1 \n__DATA                            19.0M      492 \n__DATA_CONST                      23.9M      507 \n__DATA_DIRTY                      1784K      213 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       581.7M        5 \n__OBJC_CONST                      3634K      279 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           609.6M      524 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                       45.4M        8 \nshared memory                      192K        5 \n===========                     =======  ======= \nTOTAL                              1.1T     2958 \nTOTAL, minus reserved VM space     1.1T     2958 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "CrRendererMain",
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000238
    }
  ],
  "experiments" : [

  ]
}
}

System Profile:
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Thunderbolt Bus: iMac, Apple Inc.
Thunderbolt Bus: iMac, Apple Inc.
Boot Volume File System Type: apfs
Memory Module: LPDDR4
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB Receiver
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
Display: iMac, Retina 4.5K (4480 x 2520), Main, MirrorOff, Online
Model: iMac21,1, BootROM 8419.60.44, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
AirPort: Wi-Fi, wl0: Mar 23 2022 19:44:05 version 18.60.27.0.7.8.129 FWID 01-62606619
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
``

**Comment by ssbmaccom** [comment] 2023-01-11 15:13
Addition: In Finder I can use "Show Info" and set the flag "Open with Rosetta". This will execute the App (and obviously also the sub-tasks) as Intel code using the Rosetta engine. The app works in this case (slow but not crashing). So this seems to be an issue of the "Electron Helper (Renderer)" app when compiled to run natively on Apple Silicon machines. Depending on the issue, this may also affect iOS sooner or later, if not fixed.

**Comment by ttrippel** [comment] 2023-01-11 15:34
The same with macOS 13.1 (Ventura), with Rosetta is works (thanks @ssbmaccom), natively on ARM  it does not.

**Comment by jeanfbrito** [comment] 2023-01-11 15:40
Hello, thanks for the warning!

The iOS is another project on React Native. https://github.com/RocketChat/Rocket.Chat.ReactNative

I'm investigating but nothing changed on the build process, seems to be a bug.
For now you can use the Github version from the dmg file. https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.8.16

I will rebuild and resend to Apple Store and lets see if this fixes it.

**Comment by ssbmaccom** [comment] 2023-01-11 16:03
Thanks @jeanfbrito - indeed teh same version(number) downloaded from here does not crash when running as native AppleSilicon app. Potentially teh bundling for AppStore is broken - maybe the helper is not updated? (I actually haven't compared both binaries before I replaced it from teh download - my fault).

**Comment by airbenich** [comment] 2023-01-12 09:11
Same problem here on M1 mac and Version 3.8.16 from the app store.
Rosetta works as @ssbmaccom explained.

**Comment by kiskv** [comment] 2023-01-12 11:40
Same with macos 13.1 on m1 pro, rocket.chat 3.8.16 from app store

**Comment by tkexit** [comment] 2023-01-12 19:02
Same with Rocket.Chat Verze 3.8.17 (103) from AppStore, M2, 2022, MacOS 13.1 (22C65)

**Comment by TorstenBraun-GitHub** [comment] 2023-01-12 19:08
Same with Rocket.Chat Version 3.8.17 (103) from AppStore, M1, 2021, MacOS 13.1

**Comment by NetsrotXc** [comment] 2023-01-12 19:12
Same with Rocket.Chat 3.8.17 (103), AppStore, M1, 2021, MacOS 13.1

**Comment by graffpl** [comment] 2023-01-12 19:48
Same here, Rocket.Chat 3.8.17, AppStore, M1, MacOS 13.1

**Comment by codezero** [comment] 2023-01-13 06:57
I think the problem is in Electron

objc[45444]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x248a0f110) and /Applications/Rocket.Chat.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x107d82978). One of the two will be used. Which one is undefined.

So 3.8.17 didn't fix the problem from AppStore on M1, MacOS 13.1

**Comment by marcin-kwiatkowski** [comment] 2023-01-13 08:13
Same here unfortunately. macOS on m1 pro.

I was using 3.8.16 and realized that it started to crash (only top menu indicated that the app was running). After updating to 3.8.17 nothing actually happened. I see that new version is installed (RocketChat => About RocketChat) but the main window is not displaying.

**Comment by oneCentral** [comment] 2023-01-13 09:12
Same issue here, also after updating to 3.8.17. No window is displayed

**Comment by jkiddo** [comment] 2023-01-13 10:29
Same here - just updated to 3.8.17 - no windows of the application - running on MBP M1.

**Comment by mrboogiee** [comment] 2023-01-13 10:33
just to add insult to injury, it indeed seems like the issue is not resolved with 3.8.17

**Comment by ma-he-sh** [comment] 2023-01-13 14:29
Same here, Rocket chat window not launching for version 3.8.17. On MBP M1 - Ventura

**Comment by Vaxter** [comment] 2023-01-13 15:37
For me the issue started with 3.8.17 on MacBook Air M2 Ventura 13.1

**Comment by jeanfbrito** [comment] 2023-01-13 18:49
Version 3.8.19 is already awaiting approval from Apple. It will fix this issue.
The problem was the compilation of the package by Electron. We didnt had the problem outside of the Mac Apple Store.
Sorry for the problem.

**Comment by dup2** [comment] 2023-01-14 15:17
Can confirm that 3.8.19 available via App Store fixes the issue.

**Comment by marcin-kwiatkowski** [comment] 2023-01-15 19:21
> Same here unfortunately. macOS 13.1 on m1 max.
> 
> I was using 3.8.16 and realized that it started to crash (only top menu indicated that the app was running). After updating to 3.8.17 nothing actually happened. I see that new version is installed (RocketChat => About RocketChat) but the main window is not displaying.

3.8.19 fixes the issue, thank you very much!

**Closed** 2023-01-26 14:36 UTC
Labels: type: bug
