### ISSUE TITLE
Update Rocket Chat in the Mac AppStore!

### ISSUE THREAD

**Issue by Joshua2504** [RocketChat/Rocket.Chat.Electron#2039] opened 2021-05-17 06:51 UTC
As the title says.

**Comment by ankar84** [comment] 2021-05-17 08:21
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1974

**Comment by andylin2004** [comment] 2021-05-17 17:04
Duplicate of #1931

**Comment by compuguy** [comment] 2021-05-25 20:08
Duplicate of #1009.

**Comment by compuguy** [comment] 2021-05-25 20:08
Duplicate of #1009.

**Comment by jicho** [comment] 2021-06-01 07:56
nice all those duplicates :)

But... when will it be updated in the Mac AppStore? 7 months vs 18 days old (looking at the versions) is a huge difference and a lot of stuff changed ;)

**Comment by compuguy** [comment] 2021-06-03 14:39
I don't know @jicho. I honestly wouldn't recommend downloading RocketChat from the Mac App Store. The built in update mechanism seems to be working now...

**Comment by redRolf** [comment] 2021-08-17 07:51
Does anyone know what is going on?  All previous years seem to have multiple releases for the app store, but this year there were no new releases for the rocket chat app on the app store. Is the app store app no longer supported or maintained?

Is there some sort of statement out there regarding this?

**Comment by loginx** [comment] 2021-09-17 12:35
It's been nearly a year, and the release on the mac app store is 17 releases out of date.
I'll switch to the auto-updating releases posted on Github, but the RocketChat website is still telling people to download from the app store even though it's completely unmaintained.

**Comment by felixspitzer** [comment] 2021-11-18 07:48
Please update! AppStore is still on 3.0.0 and will not receive updates

**Comment by jeanfbrito** [comment] 2021-11-18 12:04
Apple changed the requirements to be able to update the app on Apple Store.
We will be working on this in the next weeks.

**Comment by ankar84** [comment] 2021-11-18 13:16
> Apple changed the requirements to be able to update the app on Apple Store. We will be working on this in the next weeks.

Thanks, @jeanfbrito

**Comment by Marx1st** [comment] 2022-03-16 14:09
> Apple changed the requirements to be able to update the app on Apple Store. We will be working on this in the next weeks.

Weeks turn to months, months turn to years...

**Comment by jeanfbrito** [comment] 2022-03-25 04:49
The Apple Store version is updated, you can install it from there right now.

**Closed by jeanfbrito** 2022-03-25 04:49 UTC
