### ISSUE TITLE
v3 login doesn't persist

### ISSUE THREAD

**Issue by shinebayar-g** [RocketChat/Rocket.Chat.Electron#1744] opened 2020-09-30 21:32 UTC
## My Setup

- Operating System: Debian 10
- App Version: 3.0.0
- Installation type:  amd64.deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![image](https://user-images.githubusercontent.com/3091558/94741806-50972000-033a-11eb-9f7b-81b27232e357.png)

### Current Behavior

My account gets logged out every time I quit the application. My login was saved when I was using v2.7
### Expected Behavior

Login persist when I launch app again.

**Comment by AmatorPhasma** [comment] 2020-09-30 22:16
Same here

Operating System: Windows 10 Version: 2004
App Version: 3.0.0
Server version: 3.6.3
Installation type: exe from releases over version 2.17.11

**Comment by ankar84** [comment] 2020-10-01 01:41
@shinebayar-g please enable Server list in View menu and select your server
Issue is that RC 3.0.0 starts with adding new server layout, but not with already configured server
![image](https://user-images.githubusercontent.com/4023037/94756509-62aba980-03a0-11eb-8b8d-2a0fed12c220.png)

**Comment by shinebayar-g** [comment] 2020-10-01 01:46
It's already enabled.

![Screenshot_2020-09-30_20-45-00](https://user-images.githubusercontent.com/3091558/94756762-06279a80-035e-11eb-8458-14c10dc7ee0f.png)

**Comment by tassoevan** [comment] 2020-10-01 02:12
It's a "last minute" regression where persisted data is replaced by defaults. Please be patient, I'm working on it.

**Comment by ankar84** [comment] 2020-10-01 05:48
> It's already enabled. I even clicked on it few times, it's doing nothing.

Try to create `servers.json` file like [described here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743#issuecomment-701736762) and after restart application press **CTRL+1**

**Comment by AkimoA** [comment] 2020-10-01 06:09
but where would the  manually created server.json be recognised in macOS ? ,

i tried the given  examples from the main page  

with no luck 

~/Users/<username>/Library/Application Support/Rocket.Chat/
~/Applications/Rocket.Chat.app/Contents/Resources/

**Comment by User35123** [comment] 2020-10-01 12:40
> 
> 
> > It's already enabled. I even clicked on it few times, it's doing nothing.
> 
> Try to create `servers.json` file like [described here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743#issuecomment-701736762) and after restart application press **CTRL+1**

This works for me! Thanks a lot. I do not have to press CTRL+1. It just works as expected

**Comment by shinebayar-g** [comment] 2020-10-02 06:37
Looks like it's fixed for me on 3.0.1?

**Comment by blacklord049** [comment] 2020-10-02 10:56
> 
> 
> Looks like it's fixed for me on 3.0.1?

Me too. If I close the app and restart it the login persists with 3.0.1

**Comment by tassoevan** [comment] 2020-10-02 13:04
So, my [guess](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1745#issuecomment-701748434) was right. Closing this issue.

**Closed by tassoevan** 2020-10-02 13:04 UTC
Labels: type: bug
