### ISSUE TITLE
Screen-sharing macOS

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat.Electron#2249] opened 2021-12-06 09:44 UTC
The Video Call (Jitsi Meet) Screen-sharing with version 3.7.0 under macOS doesn't work anymore.

**Comment by ankar84** [comment] 2021-12-08 11:29
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2028

**Comment by BSerpent86** [comment] 2021-12-15 09:26
@jeanfbrito this affects Windows and Linux, too. It's extremely annoying. Could this be fixed in 3.7.1, too?

**Comment by jeanfbrito** [comment] 2021-12-15 10:49
> @jeanfbrito this affects Windows and Linux, too. It's extremely annoying. Could this be fixed in 3.7.1, too?

Yep, is the priority to fix, we already found the problem. Working in a fix right now.

**Closed** 2021-12-29 19:44 UTC
Labels: subj: jitsi
