### ISSUE TITLE
Update dialog not working on 2.15.0

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat.Electron#1141] opened 2019-03-13 18:56 UTC
As reported and fixed by @SimonStefan in #1123, update dialog buttons will not work to autoupdate from version 2.15.0.

EDIT: this bug happens in **ALL** platforms.

**Comment by wreiske** [comment] 2019-03-13 19:41
![YGcOcx8Xk7](https://user-images.githubusercontent.com/6295044/54309408-761cd700-45a6-11e9-8b75-161bcd492b77.gif)

**Comment by NathanBeddoeWebDev** [comment] 2019-03-13 22:04
This has been fixed in https://github.com/RocketChat/Rocket.Chat.Electron/pull/1123.

You will have to download the .exe from the releases, or on the Rocket Chat site to update to 2.15.1.

**Comment by ElieMyIdea** [comment] 2019-03-14 08:34
Same here on OSX

**Comment by dontait** [comment] 2019-03-14 09:26
I'm also getting the same issue on on macOS Mojave

**Comment by svennd** [comment] 2019-03-14 09:45
Same issue on Windows 10 enterprise, 1803.

**Comment by drasbeck** [comment] 2019-03-14 10:40
Same issue, macOS Mojave 10.14.3

**Comment by JorisVanEijden** [comment] 2019-03-14 12:33
Can the update server return a message that a manual update is required when the current version is 2.15.0?

**Comment by tklotz** [comment] 2019-03-14 14:05
Same with Windows 10 Pro (1809)

**Comment by bkraul** [comment] 2019-03-14 15:38
I went ahead and updated from the releases page. I know this is not feasible on some auto-deployments, but it solved the issues I was having with 2.15.0.

**Comment by tklotz** [comment] 2019-03-14 15:50
dito: for other windows-environment users:
You can start* the rocketchat-setup-2.15.1.exe with the silent parameter /S (uppercase s). Old version will be uninstalled, new version installed. Sometimes you must run it twice, because the first run only uninstalls rocket chat >_> 
(*admin privs required)

**Comment by dmoldovan123** [comment] 2019-03-15 08:36
Hello, same on windows 10

**Comment by btafoya** [comment] 2019-03-15 13:15
Same issue, latest Windows 10.

**Comment by nrenich** [comment] 2019-03-15 16:09
Seeing this on both Win 7 x64 & Win 10 x64 Ent 1809 and macOS 10.14.3

**Comment by HappyTobi** [comment] 2019-03-15 16:28
Same on my machine osx 10.14.3

**Comment by MartinWeniger** [comment] 2019-03-21 07:34
Hi, 
so i have to install the new rocketchat update manually to the newest version, for all computers in my company?

**Comment by bkraul** [comment] 2019-03-21 10:10
I would not upgrade to 2.15.1. See #1147

**Comment by inon-peled** [comment] 2019-03-26 17:04
Had the same problem with version 2.15.0 on my Win10 Home Edition, so I manually downloaded and installed version 2.15.1.

**Comment by LeeThompson** [comment] 2019-03-28 05:07
Same. (Windows 7).

**Comment by Nono-m0le** [comment] 2019-04-03 08:44
Is there any update regarding this issue ?
Same question as @MartinWeniger : Is that correct to assume we have to manually update all client in 2.15.0 ?

**Comment by alireza-salehi** [comment] 2019-04-08 07:05
same issue here (windows 10 / 1809 )
ver 2.15.0 
i manually upgraded to ver 2.15.1

**Comment by Nono-m0le** [comment] 2019-04-17 08:24
Well, this morning, I got the notification to update to 2.15.2 but still the "install" button doesn't trigger anything.

**Comment by wreiske** [comment] 2019-04-17 12:04
For anyone reading this:
Updating from 2.15.0 WILL NEVER WORK. 

If you're on 2.15.0, you will need to download the latest from installer from Rocket.Chat's website, or the release page here. 

Save your precious time and headache. Just go grab the new installer.

**Comment by bkraul** [comment] 2019-04-17 12:14
@wreiske this issue should really be closed.

**Closed** 2019-04-17 13:14 UTC
Labels: type: urgent

**Comment by alireza-salehi** [comment] 2019-04-19 08:47
we manually downgraded all clients to version 2.15.0 because of update problem and automatic close.

**Comment by Roman-Bober** [comment] 2019-05-06 07:38
Same with me not working on windows 10 enterprise, any fixes?

**Comment by wreiske** [comment] 2019-05-06 16:12
> Same with me not working on windows 10 enterprise, any fixes?

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1141#issuecomment-484054696

**Comment by montymotz** [comment] 2019-05-23 06:58
Same on Windows 10 Pro, Home and Mac OSx 13.3

**Comment by alireza-salehi** [comment] 2019-08-28 06:40
on version 2.15.3 update dialog appears every time but never updates the application. i have manually updated to 2.15.5.

update dialog is broken.

**Comment by franckadil** [comment] 2019-10-21 18:21
@tassoevan @wreiske I can confirm tested with 2.15.5 to 2.16.0 doesn't work on Windows 10 (1903) x64

**Comment by alireza-salehi** [comment] 2019-11-11 19:57
I'm on version 2.15.5 and every day i see update dialog 2.16.2 but it never works,
i also manually installed latest version from github, but still see version 2.15.5.

once a while update dialog wont work. 
windows 10 x64 latest update

**Comment by tassoevan** [comment] 2019-11-11 20:00
@alireza-salehi It's possible that you've installed the two versions, one for your user and the other for all users. Try to uninstall it before reinstall.

**Comment by alireza-salehi** [comment] 2019-11-12 12:12
@tassoevan 
there are two entries on "Programs and Features" 2.15.5 and 2.16.2!
there is an installation (2.15.5) on "C:\Users\Alireza\AppData\Local\Programs\Rocket.Chat"
nothing on "Program Files (x86)" or "Program Files".

there is  an installer 2.16.2 inside "C:\Users\Alireza\AppData\Local\rocketchat-updater" which i run it manually (i think it is installed in background before, because i accepted update dialog many times before.) 
there is two options on installation wizard i always select "only for me" which installs Rocket.Chat on my AppData directory.

but still my Rocket.Chat is 2.15.2.
cannot locate the installation folder for second installation, looked everywhere!?!!?

it is supposed to be "Auto Update", very confusing. either remove the AppData Option on installer or fix it.

**Comment by jsmithxti** [comment] 2019-11-18 18:23
I also have the same issue upgrading from 2.15.5 to 2.16.2.  What I have figured out is that I originally installed RC client using the "Install for anyone" option in the installer.  I was able to upgrade by selecting that option from the downloaded installer.  My guess is that the self upgrade option does not have permissions and does not prompt for the elevate permission as the manual install does.

**Comment by NicolasDionB** [comment] 2020-07-23 12:20
Why is that pop-up still available. At least you could change it for a button labeled "Get the new version" instead of having us waiting for the update to auto install later. Clearly the function does not work properly. I'm using the app on Windows 10 and have never seen such an auto update work. I'm using version 2.17.7 now and see the update notice for 2.17.11, which of course does nothing. I'll download it manually... ☹

**Comment by alireza-salehi** [comment] 2020-08-11 08:10
i'm having same problem every time, this functionality is not working well, we have to install new versions manually every time.

**Comment by Frank-RC** [comment] 2020-11-13 07:41
Hy all,

same problem here (Win 10) again and again since years. Meanwhile with V 3.0.5 to 3.0.7 and the all time promise to be "notified when the update is ready to be installed", since now that means "never".

After having downloaded and installed the last update 3.xy manually my RC-host wasn't accepted any more. Uninstalling and new installation solved that problem.

**Comment by breigo** [comment] 2020-11-13 13:39
> Hy all,
> 
> same problem here (Win 10) again and again since years. Meanwhile with V 3.0.5 to 3.0.7 and the all time promise to be "notified when the update is ready to be installed", since now that means "never".
> 
> After having downloaded and installed the last update 3.xy manually my RC-host wasn't accepted any more. Uninstalling and new installation solved that problem.

I can only agree with that.
Same problem since years.
