### ISSUE TITLE
Notification pop up appears but if clicked nothing happens

### ISSUE THREAD

**Issue by Ein-Tim** [RocketChat/Rocket.Chat.Electron#1858] opened 2020-10-29 18:01 UTC
## My Setup

- Operating System: Windows 10 Home 2004 (Build 19041.5722)
- App Version: 3.0.5 - 3.1.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
If somebody sends a message and I have Rocket.Chat running in System Tray a Pop Up appears but if I click on it Rocket.Chat isn't opened.

### Expected Behavior
Rocket.Chat App should be opened

**Comment by ankar84** [comment] 2020-10-30 07:31
**Not confirm that** - application opens on notification click
![desktop-notif](https://user-images.githubusercontent.com/4023037/97672311-deca0780-1a9a-11eb-9ab2-4ba24bff27ca.gif)
But @tassoevan I think, that **chat from notification should be opened**, but **now I see last opened chat** in applications, and not chat from notification.

**Comment by Ein-Tim** [comment] 2020-10-30 12:58
@ankar84 
And if you close the Rocke.Chat window completely and have Rocket.Chat only running in the background, is the App still opened?

**Comment by ankar84** [comment] 2020-10-30 13:45
> @ankar84 
> And if you close the Rocke.Chat window completely and have Rocket.Chat only running in the background & you get a notification, is the App still opened? 

Yes, did try that too

**Comment by Ein-Tim** [comment] 2020-10-30 15:24
Okay, @ankar84 Thanks!
I will continue to watch and report back here 👍

**Comment by ankar84** [comment] 2020-10-30 16:14
> Okay, @ankar84 Thanks!
> I will continue to watch and report back here 👍

Is your issue 100% reproducible in your environment?

**Comment by Ein-Tim** [comment] 2020-10-30 16:26
Yes it is, I wonder why it is not in your enviroment...
If I click on a message from Rocket.Chat (note that this message is just an example, it also happens with "real" notifications):

![image](https://user-images.githubusercontent.com/67682506/97730738-8b74ab00-1ad4-11eb-8e82-e788f59396f2.png)

it disappears from notification center, than I close the notification center and reopen it and the message is back... (but Rocket.Chat was not opened...)

**Comment by Ein-Tim** [comment] 2020-11-18 09:05
Tested it again yesterday. Was again 100% reproducible. Clicked on the Pop Up but the App stays closed.

**Comment by ankar84** [comment] 2020-11-20 04:24
> **Not confirm that** - application opens on notification click
> ![desktop-notif](https://user-images.githubusercontent.com/4023037/97672311-deca0780-1a9a-11eb-9ab2-4ba24bff27ca.gif)
> But @tassoevan I think, that **chat from notification should be opened**, but **now I see last opened chat** in applications, and not chat from notification.

Yeap, I just experienced that too!
So confirm that issue!

**Comment by ankar84** [comment] 2020-11-20 04:29
Reproduce steps.
1. Set desktop notifications ON (All Messages)
2. Minimize application to system tray by clicking X button in top right corner
3. Get a mew message, click on notification.
4. Nothing happens

So, issue is about maximizing application from system tray.
@tassoevan please take a look.

**Comment by rcadmin19** [comment] 2021-01-15 12:25
This issue exists also in RC Desktop client version 3.1.1 (Windows). In our experience, version 3.0.7 did not have the problem.

**Comment by pascal1337** [comment] 2021-01-22 12:10
Hey, we also have this experience using the latest versions

Server 3.10.4
Client 3.1.1

Some users are clicking and nothing happens, some users get their chats opened and other users have to click the notification multiple times till it opens the window.

**Comment by hkpanchani** [comment] 2021-04-01 05:19
yes indeed, clicking on notification leads to null. Nothing opens..app is not maximazed

**Comment by Ein-Tim** [comment] 2021-04-08 12:31
Meanwhile I switched to a MacBook, using the version from the App Store and MacOS BigSur 11.2.3, I'm still able to reproduce this.

**Comment by Mystikal57** [comment] 2021-07-22 07:59
hi,

Same problem for us :-( last electron client installed

**Comment by shawneepiano** [comment] 2021-08-12 15:37
Has this issue been solved / If not, is it in the works? or has anyone found a work-a-round?
I did see version 3.3.0 client "in the works" here https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.3.0
and not sure if this is addressed there?

Many thanks 
Shawn

**Comment by Mystikal57** [comment] 2021-08-12 15:58
Problem seems to be resolved in 3.3 but this version is too buggy

**Comment by shawneepiano** [comment] 2021-08-12 17:39
> Problem seems to be resolved in 3.3 but this version is too buggy

Thanks for your reply, Mystikal57!

Is there an easy way to see which lines of codes were changed to fix it?

If not, that's OK.

**Comment by Mystikal57** [comment] 2021-08-12 18:14
I tried but it's not easy with typescript
I don't found

**Comment by jeanfbrito** [comment] 2022-01-10 16:52
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 16:52 UTC

**Comment by Ein-Tim** [comment] 2022-01-10 16:55
As I'm not using Rocket.Chat anymore, I can't check this. Maybe someone of the other users who confirmed this bug can confirm the fix?
