### ISSUE TITLE
Video Full screen option not working

### ISSUE THREAD

**Issue by basant807** [RocketChat/Rocket.Chat.Electron#1276] opened 2019-07-05 11:22 UTC
Video Full screen option not working

**Comment by wreiske** [comment] 2019-09-03 15:05
+1, same issue here for both YouTube and uploaded videos.

**Comment by wreiske** [comment] 2019-09-03 15:07
@rocket-cat duplicate
@rocket-cat close

Duplicate of #1220

**Closed** 2019-11-23 14:18 UTC
