### ISSUE TITLE
Server Icons are duplicated in sidebar

### ISSUE THREAD

**Issue by MFietze** [RocketChat/Rocket.Chat.Electron#746] opened 2018-06-11 05:52 UTC
## My Setup
- Operating System: Windows 10 Version 1703
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Since I updated to 2.11.0 the sidebar shows the server icons multiple times (see screenshot). When I hover my mouse pointer over the icons, the additional icons disappear till I move the mouse back. The issue remains even after a reboot, restart or reinstall of the app.

![screenshot](https://user-images.githubusercontent.com/6169702/41214485-f461dd1a-6d4b-11e8-9e19-57d84344e359.PNG)

### Current Behavior
The server icons in the sidebar are duplicated. The duplicates are not functional. They disapear when the mouse pointer hovers over the original icons.

### Expected Behavior
The icons should be displayed only one time on the top of the sidebar.

**Comment by kaiiiiiiiii** [comment] 2018-06-11 07:12
Duplicate of #744

**Comment by engelgabriel** [comment] 2018-06-12 03:59
Duplicate of #744 indeed

**Closed by engelgabriel** 2018-06-12 03:59 UTC
