### ISSUE TITLE
Using .36 version of RocketChat

### ISSUE THREAD

**Issue by skizzors** [RocketChat/Rocket.Chat.Electron#222] opened 2016-08-14 21:04 UTC
## My Setup

 - __My OS name and version__: All OS, versions
 - __My current app version__: 0.36

- [ x] I have tested with the latest application version
- [ x] I can simulate the issue easily

## Description
 It would be GREAT if you could just rename files you upload to rocket.chat, this seems super simple, but is a big issue to keep uploaded files organized. Currently when uploading files I have not found a way to rename the upload title before uploading it, aside from renaming the file itself before uploading. It would be great to have it not say "File Uploaded" in front of the file name as well, or at least have it be seperate, smaller, lighter font text and not part of the file link itself. It makes the filename hard to see quickly.

#### Current Behavior
![screen shot 2016-08-14 at 4 00 03 pm](https://cloud.githubusercontent.com/assets/17693312/17652034/87be7210-6238-11e6-8065-975ba273037c.png)
![screen shot 2016-08-14 at 3 13 09 pm](https://cloud.githubusercontent.com/assets/17693312/17652048/b8b2bc28-6238-11e6-8ba1-71665d78b203.png)

**Comment by xenithorb** [comment] 2016-08-18 23:53
You should close this issue and file it against: https://github.com/RocketChat/Rocket.Chat

Such an issue would be handled by the webapp code, I'm almost positive. 

It's a good idea, too.

**Comment by graywolf336** [comment] 2016-08-19 00:36
Closing as this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/1279

**Closed by graywolf336** 2016-08-19 00:36 UTC
