### ISSUE TITLE
Jitis not working 

### ISSUE THREAD

**Issue by philippbr** [RocketChat/Rocket.Chat.Electron#1573] opened 2020-04-06 10:14 UTC
I am using the Rocket.Chat App 2.17.7 on the newest OSX.
The app itself works fine, yet, our integrated Jitsi does not work. If Jitsi starts in the Rocket.Chat app, neither the mic, nor the camera works.
can you open the link to the jitsi conference in an external browser?

**Comment by CitizenDev** [comment] 2020-04-07 06:55
There is already registered issue about it few posts back #1562

**Comment by gabriellsh** [comment] 2020-04-27 15:53
Duplicate of #1562

**Closed by gabriellsh** 2020-04-27 15:53 UTC
