### ISSUE TITLE
No message color displayed

### ISSUE THREAD

**Issue by NocnyKochanek** [RocketChat/Rocket.Chat.Electron#154] opened 2016-03-23 18:09 UTC
[instruction]: # (Answer the questions below about your current setup)

* My OS name and version: Ubuntu 15.10
* My current app version: 1.2.0

--
[instruction]: # (Answer the questions below by checking items with x, like [x] )

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

--
[instruction]: # (Add more information about your issue below)

Messages are displayed without color attribute (between avatar and text).
This occurs in a linux desktop app and through browser. Android app does not have that issue.

**Comment by rodrigok** [comment] 2016-03-24 03:39
Can you post one print screen of the current state and one of the expected behavior? I didn't understand you only with your description

**Comment by NocnyKochanek** [comment] 2016-03-24 14:59
Current state:
![ubuntu_app](https://cloud.githubusercontent.com/assets/18035824/14020861/45df1db0-f1d9-11e5-99b6-995b92f8b23d.jpg)

Expected output:
![android_app](https://cloud.githubusercontent.com/assets/18035824/14020865/489c3a6a-f1d9-11e5-9057-15229d6a2e54.jpg)

**Comment by rodrigok** [comment] 2016-03-24 16:14
Sure, this seems to be a problem related with our theme package at Rocket.Chat server. Which version of the server are you using?

**Comment by NocnyKochanek** [comment] 2016-03-24 16:23
Im using latest server version 0.23.0.

**Comment by rodrigok** [comment] 2016-03-24 16:24
@NocnyKochanek can you try our latest develop version?

**Comment by NocnyKochanek** [comment] 2016-03-24 19:07
@rodrigok  Just tested latest develop version - color attribute works as expected.
Thank You very much for help :)
I assume this will be fixed in a stable version as well?

**Comment by rodrigok** [comment] 2016-03-24 20:04
Yes, will

I will close this issue

**Closed by rodrigok** 2016-03-24 20:04 UTC
