### ISSUE TITLE
Deep linking to rooms/channels

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat.Electron#506] opened 2017-08-14 18:08 UTC
This is a new feature.

## Description
With the new feature of rocketchat protocol being merged, we open the possibility of having deep links to room and channels inside the Rocket.Chat App. This would allow us to have links as rocketchat://<SERVER_URL>/channel=<Channel Name> that when clicked would open the server and room directly on the electron app.

**Comment by marceloschmidt** [comment] 2018-07-25 16:06
Please fix the deep link to match what's described on https://rocket.chat/docs/developer-guides/deeplink/#deeplink

**Comment by Cruaier** [comment] 2018-12-12 07:31
Is there a plan to implement this feature?

**Comment by moriccelli** [comment] 2019-11-21 07:34
We still meet the issue. https://go.rocket.chat/room?host=<chat.server>&rid=iBXhQLNQvecDjcE2Q doesn't open the needed chat in windows app. It just opens the app - that's all. The problem is quite appreciable for us.

**Comment by phiter** [comment] 2020-05-22 01:38
Hey, is this active? I can't open a direct message chat either.

**Comment by anthonymanzo** [comment] 2020-07-14 04:15
Having this same issue.  Just getting bounced to the rc home when I choose the web, desktop not working at all.

**Comment by tassoevan** [comment] 2020-09-29 05:23
Closed by #1726

**Closed by tassoevan** 2020-09-29 05:23 UTC
Labels: type: enhancement, type: new feature

**Comment by didacroyo** [comment] 2021-08-03 07:26
> We still meet the issue. https://go.rocket.chat/room?host=<chat.server>&rid=iBXhQLNQvecDjcE2Q doesn't open the needed chat in windows app. It just opens the app - that's all. The problem is quite appreciable for us.

Also, trying to send the param "path" and we don't find how to redirect the user directly to the threaded conversation
