### ISSUE TITLE
[3.0.1] Rocket.Chat is still running Notification

### ISSUE THREAD

**Issue by thorin8k** [RocketChat/Rocket.Chat.Electron#1765] opened 2020-10-02 08:10 UTC
## My Setup

- Operating System: Windows 10 v.1909
- App Version: 3.0.1
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Since last update this message is shown every time the application is closed:
![image](https://user-images.githubusercontent.com/50626175/94901680-4d657680-0497-11eb-9f50-6a39fcb80683.png)

### Current Behavior
The notification appears every time you close the app.

### Expected Behavior
The notification should only appear the first time or let you decide whenever you want to ignore it.

**Comment by User35123** [comment] 2020-10-02 15:41
Yes, this is really annoying

**Comment by tassoevan** [comment] 2020-10-02 15:49
Duplicate of #1749

**Closed by tassoevan** 2020-10-02 15:49 UTC
Labels: stat: duplicate

**Comment by narslankaya** [comment] 2020-11-03 05:41
+1
