### ISSUE TITLE
Windows application does not update

### ISSUE THREAD

**Issue by csymvoul** [RocketChat/Rocket.Chat.Electron#1876] opened 2020-11-12 09:19 UTC
## My Setup

- Operating System: Windows 10 Education 
- App Version: 2.17.11
- Installation type: -

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
This popup windows shows up when opening the application. 
![image](https://user-images.githubusercontent.com/36190914/98920179-73d7f200-24d8-11eb-9d48-44ed3a698f6e.png)
A message saying that I will be notified after update is complete is shown. 

### Current Behavior
The update is never complete and every time I open the Rocket.chat or restart my machine this popup for the update is shown.

### Expected Behavior
Update to the newest version of Rocket.chat.

**Comment by ankar84** [comment] 2020-11-12 10:04
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1399 and https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Comment by AlbyGNinja** [comment] 2020-11-25 09:07
@csymvoul workaround solution here: 
[https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302)

**Comment by ankar84** [comment] 2021-09-08 07:45
Closing in favor of #1670

**Closed by ankar84** 2021-09-08 07:45 UTC
