### ISSUE TITLE
Windows 10 Screen Fails to Render

### ISSUE THREAD

**Issue by steve-geek** [RocketChat/Rocket.Chat.Electron#1406] opened 2019-11-21 20:10 UTC
## My Setup
- Operating System: Windows 10
- App Version:  2.16.2
- Installation type: 
 Independant Server

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

 After installation - Rocket window shows. Close/Open many times. Restart machine. Start Rocket by clicking on the icon in the start menu (which appears after a successful install)... the Rocket main window does not show/render, the processes start, however the window is not visible. Remove and reinstalled Rocket several times, window is never visible in the above sequence. I tested several other sequences too, (just black box testing) and the results are the same.

Also, after starting Rocket (in the above sequence AND  no window appears) if you hover over the Rocket icon, it doesn't show a thumbnail of the started (but not displaying) window. So, clearly the window is not starting, and being displayed on  a hidden virtual display or some other inactive display.

THEN A WORKING SOLUTION - in the "processes" tray, lower right corner, I noticed the Rocket Notification icon. It is grayed out (correctly so, because no new notifications). When I click on the Notification icon, then the Rocket main window appears on my desktop - AND - now when you hover of the icon, a thumbnail does appear.

I've actually had this problem on several versions, I have tested on 3 (three) different platforms, all  windows 10,, to work around the problem, I would just always go back to a 2.10 copy I had in my archives. But this time wanted to see if I could figure it out.

Ran several different sequences, also logged in on web, then did install, basically trying to correlate when the window would appear. 

No response necessary.

### Expected Behavior

When you click on the Rocket Icon the main window should appear.

**Comment by tassoevan** [comment] 2019-11-26 22:11
Maybe related to #1209?

**Comment by brandonharshe** [comment] 2019-12-03 17:23
I could be wrong about this specific issue you're talking about, but it _seems_ to be #1104. The reason I think it's the same is because you say the process starts but the window isn't showing, and that you have to go to the tray icon to see the window. As far as I'm aware, this is "correct" behavior as designed, but it's highly abnormal when compared to any other Windows application, which leads to a lot of confusion.

**Comment by steve-geek** [comment] 2019-12-03 17:50
thank you - I do a lot of gui stuff... i understand what you are saying, with respect to if something is autostart, perhaps it should be in the tray... but, I am clicking on the actual icon, whether on the desktop or the task bar... this, in general means "open the application"... so, I agree, "highly abnormal" to then have to find the application in the system tray and open again -- BUT -- to be clear, while I think this is incorrect, it is NOT A GAME CHANGER - ONCE i understood the behavior... but prior to that, (meaning 1) the application didn't "open" no matter what I did; and, 2) then, by luck, finding it in the system tray and opening from there... but prior I was convinced the application was broken.

Thanks ALL - I am a big fan!!!

Steve

**Comment by brandonharshe** [comment] 2019-12-09 00:07
Yes, it's very confusing behavior. Glad we figured it out.

**Comment by tassoevan** [comment] 2019-12-10 12:28
Move this to the next minor version because the behavior has to change.

**Comment by tassoevan** [comment] 2020-10-02 05:27
It must have been fixed by 3.0.0 (despite creating #1749).

**Closed by tassoevan** 2020-10-02 05:27 UTC
Labels: feat: tray icon / dock / taskbar, plat: windows, type: bug
