### ISSUE TITLE
Showing About gives a JavaScript error dialog in 2.7.0

### ISSUE THREAD

**Issue by thehutman** [RocketChat/Rocket.Chat.Electron#431] opened 2017-04-26 15:17 UTC
## My Setup

 - Window 10 v1607
 - Rocket.Chat+ 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Just upgraded to 2.7.0 from 2.6.1

When opening the Rocket.Chat+ -> About menu, I get the following error dialog:
![image](https://cloud.githubusercontent.com/assets/4375809/25441792/d7603896-2a68-11e7-9096-f4fe5a62b50b.png)

Closing the error message shows a blank about window.

#### Expected Behavior

Expect to see the about dialog :)

**Comment by goobersmooch** [comment] 2017-04-26 16:07
I'm having the same issue on macOS.

**Comment by kainjow** [comment] 2017-04-26 16:23
Me too.

**Comment by kainjow** [comment] 2017-04-26 17:26
Looks like this is a duplicate of #427

**Comment by engelgabriel** [comment] 2017-05-05 15:13
Closed in favor of  #427

**Closed by engelgabriel** 2017-05-05 15:13 UTC
