### ISSUE TITLE
[BUG] Tray Icon / Taskbar no unread message count on Windows client

### ISSUE THREAD

**Issue by CitizenDev** [RocketChat/Rocket.Chat.Electron#1499] opened 2020-02-04 13:24 UTC
### My Setup

Operating System: WIN 10 PRO 1909
App Version: 2.17.4
Server version 2.0.0
Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Description
There is never actual unread count number on tray icon (just one dot over gray icon if there are unread messages)
And no unread count on taskbar.

Looking through code and repo I found said icons are on this location \src\public\images\tray\darwin
Can someone explain why aren't these windows icons used instead? \src\public\images\tray\win32

I'm definitely using Windows not macOS

### Current Behavior
No unread count on tray or taskbar icon

### Expected Behavior
I've read the code and at least tray icon should show numbers from 1-9 over tray icon.

It seems that the client is detecting the system as macOS not Windows and therefore shows icons from darwin directory not win32

This is the second time I'm posting this because previous post was ignored and is now buried for months.

**Comment by tassoevan** [comment] 2020-02-04 14:01
Duplicate of #1395. Sorry for losing track of your original post.

**Closed by tassoevan** 2020-02-04 14:01 UTC
Labels: feat: tray icon / dock / taskbar, plat: windows, type: bug
