### ISSUE TITLE
persistent startup options for window-state

### ISSUE THREAD

**Issue by rschoell** [RocketChat/Rocket.Chat.Electron#1160] opened 2019-03-26 08:40 UTC
## My Setup
- Operating System: Windows 10 Pro 1809
- App Version: 2.15.1
- Installation type: exe silent install

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When opening RocketChat client, the window-state-main.json file is read and last window state applied. 

### Current Behavior
when having client hidden, it starts hidden, irritating users, who call IT to report non working program.

### Expected Behavior
We would like to have a gui option to setup startup preference (hidden, minimized, normal, maximised). This should be in a persistent saved state, unless changed through the GUI settings. 

Many thanks.

**Comment by tassoevan** [comment] 2019-03-31 21:31
@rschoell Is the window getting hidden *without* a tray icon appearing?

**Comment by rschoell** [comment] 2019-04-01 15:44
The tray icon is there. But my users get irritated, when an app they start is not showing. That's where the request comes from.
Thanks Ralph



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Tasso Evangelista <notifications@github.com>
Datum: 31.03.19 23:31 (GMT+01:00)
An: "RocketChat/Rocket.Chat.Electron" <Rocket.Chat.Electron@noreply.github.com>
Cc: rschoell <rschoell@outlook.com>, Mention <mention@noreply.github.com>
Betreff: Re: [RocketChat/Rocket.Chat.Electron] persistent startup options for window-state (#1160)


@rschoell<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frschoell&data=02%7C01%7C%7Cb3628937e9624d14cf4208d6b6204ab1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636896647133226616&sdata=M%2BPMXDYJyNGCH8ZVT9d8cPlvNk3eYOsPJu4HAN1%2BpYc%3D&reserved=0> Is the window getting hidden without a tray icon appearing?

**Comment by tassoevan** [comment] 2019-04-01 16:42
@rschoell I got it. It is by design persisting the last window state for reuse on startup, but I understand how this could be confusing for some users and why there must be a preference to handle it.

**Comment by rschoell** [comment] 2019-04-02 04:24
Thank you very much Tasso. My users will appreciate it.



Von: Tasso Evangelista <notifications@github.com>
Gesendet: Montag, 1. April 2019 18:43
An: RocketChat/Rocket.Chat.Electron <Rocket.Chat.Electron@noreply.github.com>
Cc: rschoell <rschoell@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [RocketChat/Rocket.Chat.Electron] persistent startup options for window-state (#1160)


@rschoell<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frschoell&data=02%7C01%7C%7C4e60cc0c95ea4f34ee3808d6b6c116ae%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636897337759103739&sdata=qV%2BN%2BTgFGCX7PA9OxYqAmeV8AReOCG5n8SoSuLgTlFQ%3D&reserved=0> I got it. It is by design persisting the last window state for reuse on startup, but I understand how this could be confusing for some users and why there must be a preference to handle it.

**Comment by StephanePepin** [comment] 2019-05-01 21:02
Hello, we have recently starting rolling out Rocket.Chat in our department and we have been getting similar complaints that rocket.chat is no opening when they launch the desktop app. After investigating a little, I found  the window-state-main JSON file and why this is occurring. Is there a way to ensure that 'isHidden" stays = true, for at least at startup or launching the app?

![window-state-main JSON](https://user-images.githubusercontent.com/47756291/57042515-d9d09180-6c32-11e9-9320-94844b399e6c.PNG)

**Comment by FixitMad** [comment] 2019-05-29 14:43
We too are having issues with the RocketChat after rolling it out to our users. Users are complaining that RocketChat is opening up on the notification bar only and not a maximized window.

So is the fix to prevent this from happening is to change the "isHidden" field from true to false under the window-state-main.json file? 

If not, Do users have to leave their RocketChat maximized before they shutdown systems so the window-state-main.json file still shows false under "isHidden"?

Thanks.

**Comment by Sicoval31** [comment] 2019-10-16 09:17
a problem link with yours : do you know where/how i can manage the option for RC desktop launhc at windows startup ?

**Comment by drenton1** [comment] 2019-10-29 19:20
As a workaround you could run a powershell script before Rocket.Chat starts to change the isHidden value.

`$a = Get-Content "$($ENV:AppData)\Rocket.Chat\window-state-main.json" | ConvertFrom-Json`
`$a.isHidden = $false`
`$a | ConvertTo-Json | set-content "$($ENV:AppData)\Rocket.Chat\window-state-main.json"`

**Comment by antonioli86** [comment] 2021-02-04 12:21
Not fixed after this time?

**Comment by jeanfbrito** [comment] 2022-01-12 00:20
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:20 UTC
Labels: type: bug

**Comment by Sicoval31** [comment] 2022-01-12 08:11
the last version didn't resolve that because there is no flag in auto install to add the autostart option !

Or no communication on this features !!!!

**Comment by jeanfbrito** [comment] 2022-01-12 12:27
This issue has nothing to do with auto install and autostart option.
The state of window is persisted everytime it changes.

> the last version didn't resolve that because there is no flag in auto install to add the autostart option !
> 
> Or no communication on this features !!!!
