### ISSUE TITLE
icon not showing correctly in Terminal Server clients.

### ISSUE THREAD

**Issue by tokafondo** [RocketChat/Rocket.Chat.Electron#397] opened 2017-03-15 15:53 UTC
- Windows Terminal Server Client included in Windows 7.
 - Windows Server 2008 R2
 - Version 2.5.0 

- [ x] I have tested with the latest application version
- [ x] I can simulate the issue easily

## Description

The rocket chat client is installed in a Windows Server, with terminal services enabled. The client works right when users use the terminal services client, with every user getting its own rocket chat session.

#### Current Behavior

The icon is shown in the tray inside a black square and _always_ shown as if there was a channel notificacion. **not** a gray icon with transparent background as default, but **colored** icon with a **black** background. When a direct message arrives, it changes to a red icon with the number inside. When cleared, it returns to colored icon with black background.

![image](https://cloud.githubusercontent.com/assets/26439185/23957526/8046dcd2-0997-11e7-9ba2-edaf22c8e18c.png)

#### Expected Behavior

The expected behavior should be the same as the desktop client installed in a non terminal services remote desktop session:

- gray icon when no pending messages
- colored icon when general chat messages are unread 
- red icon with number when direct messages or mentions are unread.

**Comment by geekgonecrazy** [comment] 2017-04-05 16:13
#402 related maybe duplicate

**Comment by tokafondo** [comment] 2017-04-06 07:40
I don't think so. This happens in Windows Server Terminal Services.


--

Saludos y cerveza.


-------- Mensaje original --------
De: Aaron Ogle <notifications@github.com>
Fecha:05/04/2017 17:13 (GMT+00:00)
Para: "RocketChat/Rocket.Chat.Electron" <Rocket.Chat.Electron@noreply.github.com>
Cc: Claudio Sánchez <tokafondo@gmail.com>, Author <author@noreply.github.com>
Asunto: Re: [RocketChat/Rocket.Chat.Electron] icon not showing correctly in Terminal Server clients. (#397)


#402<https://github.com/RocketChat/Rocket.Chat.Electron/issues/402> related maybe duplicate

**Comment by geekgonecrazy** [comment] 2017-04-06 19:19
@tokafondo both show the same discolored icon.  :smile:  Something is wrong with the icon its self since its happening on windows server as well as on linux.

**Comment by geekgonecrazy** [comment] 2017-04-06 19:20
https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/src/public/images/windows/icon-trayDot.png yup there it is :)

**Comment by monspid** [comment] 2017-04-07 17:46
It's not a bug, it's a feature. It is the same as on slack. It shows when you have not read not direct messages (dot messages). Example for slack below:
https://get.slack.help/hc/en-us/articles/201675007-App-icon-notifications#mac-1

**Comment by gdelavald** [comment] 2017-08-17 20:35
The issue has been fixed in the latest version.

**Closed by gdelavald** 2017-08-17 20:35 UTC
