### ISSUE TITLE
Rocket Chat v3.7.0 crashes when opening Windows -> Settings on Windows Desktop

### ISSUE THREAD

**Issue by ajmaske** [RocketChat/Rocket.Chat.Electron#2246] opened 2021-12-03 23:18 UTC
**Describe the bug**
v3.7.0 windows desktop version, opening Windows -> Settings crashes rocket chat.

What operating system and which version?  Windows 10
Which version of Rocket.Chat (Server)? Not sure.
Which version of Rocket.Chat.Electron (Electron/Desktop)? Desktop v3.7.0
Is there any setting relevant changed?

**To Reproduce**
1. running RC Desktop v3.7.0
2. Click menu item Window and select Settings
3. Rocket chat will crash a couple of seconds later.

**Additional context**
The main menu Window->Setting appears to be the only place the crash will appear.  Clicking the gear on the lower left and Ctrl+I will load the settings without crashing.

**Comment by ankar84** [comment] 2021-12-06 01:26
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2146

**Closed by ankar84** 2021-12-06 01:26 UTC
