### ISSUE TITLE
Can't login with google OAUTH

### ISSUE THREAD

**Issue by TracyP** [RocketChat/Rocket.Chat.Electron#1526] opened 2020-02-18 03:57 UTC
## My Setup

- Operating System: OSX 10.14.6 (18G2022)
- App Version:2.7.17
- Installation type: DMG 

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Added a server but it says I can't login with google.  I get error:

Google Couldn't sign you in
This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

### Current Behavior

I can't log in.  I downloaded the mobile app, and added the same server, and logged in by auth against my google account just fine.
### Expected Behavior

The google auth from the desktop app should work just the same as the mobile (android) version.

**Comment by tassoevan** [comment] 2020-02-20 02:54
Duplicate of #1459.

**Closed by tassoevan** 2020-02-20 02:54 UTC
Labels: feat: web view, stat: duplicate, type: bug
