### ISSUE TITLE
Video call triggers again (Jitsi self-hosted)

### ISSUE THREAD

**Issue by thisfro** [RocketChat/Rocket.Chat.Electron#1847] opened 2020-10-23 09:28 UTC
## My Setup

- Operating System: Manjaro Linux 5.8.16-2
- App Version: 3.0.4
- Installation type: pacman

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I started a video call in the evening (say 9 pm). I end the call with the hang up button in jitsi and leave the tab open (see screenshot). Then I put my computer to sleep overnight. The next morning my friend gets a new call.

![image](https://user-images.githubusercontent.com/9142702/96986926-9c487e00-1522-11eb-97b5-b3558d642d8b.png)

It also shows me that I started a call, which I did not.
![image](https://user-images.githubusercontent.com/9142702/96986858-8470fa00-1522-11eb-9bcc-7cc44efa2388.png)

### Current Behavior
Both users (direct message) get a new call notification.

### Expected Behavior
Only trigger the call when the button to call is actually clicked.

**Comment by ankar84** [comment] 2020-10-23 10:11
I experienced same issue, but I think it's Rocket Chat server issue, because in my case RC RM application was involved.

**Comment by thisfro** [comment] 2020-10-24 11:41
@ankar84 as the client that triggerd a new call? or did it just show the call?

**Comment by ankar84** [comment] 2020-10-24 12:13
> @ankar84 as the client that triggerd a new call? or did it just show the call?

Actually few clients of my server experienced that issue, not me.
And as I understand, there was a call in mobile application, call was finished. And after some time there appeared another call, that no-one start.
All circumstances of that issue is unknown currently.

**Comment by sandreddu** [comment] 2020-10-28 08:08
We had that same issue and what triggered it was an automated server restart after updates

**Comment by ankar84** [comment] 2020-10-28 08:19
> We had that same issue and what triggered it was an automated server restart after updates

Very interesting.
@sampaiodiego @pierre-lehnen-rc can you take a look at that issue?

**Comment by mape2k** [comment] 2020-11-19 14:22
We can confirm this issue on Win 10 using client 3.0.6.
It seems to start after Upgrade to client 3.x and affects just 2 users...

**Comment by ankar84** [comment] 2021-04-05 10:23
Recently a lot of our users got affected by that issue.
I'll try to make reproduce script to get the root cause of that issue.

**Comment by ankar84** [comment] 2021-04-05 10:31
That bug creates call button every 1 minute
![image](https://user-images.githubusercontent.com/4023037/113564545-3e13e100-9612-11eb-8d8b-9871c3408b2b.png)
![image](https://user-images.githubusercontent.com/4023037/113564603-5421a180-9612-11eb-9cc6-8abca541ad3d.png)
![image](https://user-images.githubusercontent.com/4023037/113564713-7d423200-9612-11eb-9f54-ca537130f6ef.png)
![image](https://user-images.githubusercontent.com/4023037/113564798-a1057800-9612-11eb-9db5-96c1a599d360.png)
That's really annoying and users get angry about that.
Here some another users with that problem https://open.rocket.chat/channel/support?msg=EgWZ4BAaGqPY4JSzy

**Comment by ankar84** [comment] 2021-04-05 11:03
**jitsi:updateTimeout** is a root cause for that!
And it's RocketChat issue, not Electron issus

`["{\"msg\":\"method\",\"method\":\"jitsi:updateTimeout\",\"params\":[\"gYFnyDxfwdDom9jeRiodE4TwMg4i729GoH\"],\"id\":\"65\"}"]`

**Comment by ankar84** [comment] 2021-04-05 12:19
I definitely figure out that issue!
It is a **Web client issue** for sure, so @ggazzo FYI.
I'm on 3.7.1 now, but I see, that 3.8.1 involved to and some 3.9 version too.
##Root cause
If **Call contextual bar** remain open and all call participants except one (with Call contextual bar open) leave that call, then after 3-5 minutes that calls buttons repeat to create in chat every single minute by **jitsi:updateTimeout** from websocket of that alone user in call, or more accurate by **jitsi:updateTimeout of Call contextual bar**.
![image](https://user-images.githubusercontent.com/4023037/113572925-cea5ed80-9621-11eb-9f9a-b3b88bf90cb4.png)
![image](https://user-images.githubusercontent.com/4023037/113573045-09a82100-9622-11eb-85ad-4827cab619c0.png)

##Solution
It might be solved with https://github.com/RocketChat/Rocket.Chat/pull/21004 by @yash-rajpal who fixed that with close that Call contextual bar after call started. So I believe 3.12.1 and higher may not be affected.

##Workaround
Advice your users always close that **Call contextual bar** after call is started or update to 3.12.1+

**Comment by ankar84** [comment] 2021-05-20 03:57
I have that bug somehow on recent 3.14 Rocket.Chat version with **Call contextual bar** closed right after call is started.
I don't know all conditions right now, but definitely "Click to Join!" button every minute flood is present in 3.14!

If I find a reproduce way I will open separate issue in main RC repo.

**Comment by ankar84** [comment] 2021-05-27 09:04
Also related
https://github.com/RocketChat/Rocket.Chat/issues/12148
https://github.com/RocketChat/Rocket.Chat/issues/18136

**Comment by arpsyapathy** [comment] 2021-06-03 17:41
@ankar84 
Hi!
You have same problem?
I have this problem too
So far there is no solution for this problem?

**Comment by ankar84** [comment] 2021-06-04 03:44
> @ankar84 
> Hi!
> You have same problem?
> I have this problem too
> So far there is no solution for this problem?

Yeah 
But we today updated to 3.15.0
Let's see

**Comment by arpsyapathy** [comment] 2021-06-04 08:17
> > @ankar84
> > Hi!
> > You have same problem?
> > I have this problem too
> > So far there is no solution for this problem?
> 
> Yeah
> But we today updated to 3.15.0
> Let's see

@ankar84 
I have 3.15.0..
The problem is still relevant...

**Comment by ankar84** [comment] 2021-06-08 06:07
That and related issues could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/22277

**Comment by mjunghanns** [comment] 2021-06-14 12:05
Same issue here

**Comment by Cob0ld** [comment] 2021-06-21 17:53
any hope this will be fixed ?

**Comment by pierre-lehnen-rc** [comment] 2021-06-21 20:06
> any hope this will be fixed ?

It's fixed on the next Rocket.Chat version, which will be released next week.

**Comment by ankar84** [comment] 2021-06-22 01:23
> > any hope this will be fixed ?
> 
> It's fixed on the next Rocket.Chat version, which will be released next week.

I hope you are right, Pierre!

**Closed** 2022-01-11 12:15 UTC
Labels: subj: jitsi
