### ISSUE TITLE
No video preview and playback

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat.Electron#834] opened 2018-08-23 10:58 UTC
## My Setup
- Operating System: Mac OS High Sierra
- App Version: 2.12.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![no preview](https://user-images.githubusercontent.com/3521624/44521681-2a6f1280-a6d4-11e8-8c83-1f185772d0e3.png)

### Current Behavior
You can't preview a video

### Expected Behavior
You can preview a video

**Comment by tassoevan** [comment] 2018-08-23 14:04
I couldn't reproduce it using a MP4 video file in the https://open.rocket.chat server. Would you mind to inform the Rocket.Chat server version and video format uploaded?

**Comment by dzienisz** [comment] 2018-08-23 15:18
![zrzut ekranu 2018-08-23 o 17 17 39](https://user-images.githubusercontent.com/3521624/44534620-88155600-a6f8-11e8-9452-89a5e9898bed.png)

this is .mov file (screencast)

**Comment by tassoevan** [comment] 2018-08-23 18:02
It seems related to https://github.com/RocketChat/Rocket.Chat/issues/3547, but I need to investigate this inconsistency between your browser and the Electron app.

**Comment by dzienisz** [comment] 2018-08-24 08:33
I heard from my friend that when you have 2 videos one by one on (Safari) it's totally break the browser.

**Comment by tassoevan** [comment] 2018-08-25 04:01
Yes, it's a really wild Safari bug that is biting us: https://github.com/RocketChat/Rocket.Chat/issues/11336

**Comment by Andy58** [comment] 2018-10-09 19:52
Hi, we're running server 0.69.2 and are also having lot's of non showing video and images. Only sometimes a refresh helps, but most often not. Also trying to download non displayed media creates 0 bytes files, hence this is broken as well.

This only happens in the client app on macOS and Windows. The iOS clients and Chrome on desktops show the media fine.

Any clues? Unfortunately we have a handful of users who leave their rage over this with me.

**Comment by jeanfbrito** [comment] 2022-01-10 18:23
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:23 UTC
Labels: plat: osx

**Comment by sorteam** [comment] 2022-04-15 11:54
mov video files still doesn't play at desktop app on my Mac
