### ISSUE TITLE
Name does not change when transferring multiple files

### ISSUE THREAD

**Issue by DeadMozay** [RocketChat/Rocket.Chat.Electron#2201] opened 2021-10-07 05:07 UTC
**Describe the bug**
When several files are sent at the same time, the subsequent ones will always have the name of the first file.

What operating system and which version? Any
Which version of Rocket.Chat (Server)? 4.0.0
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.7
Is there any setting relevant changed? No

**To Reproduce**
Go to file manager, select 2 or more files and drag them to the chat window, 
after clicking the Send button, the first file is sent correctly, after sending, 
a dialog box for the second file will open, where the real name of the file will
already be visible, and the one that will be assigned by rocketchat after sending, 
it always matches the name of the first file uploaded

![Peek 2021-10-07 11-42](https://user-images.githubusercontent.com/39763483/136326572-b3b012ae-7d62-47c7-9737-d153dda02357.gif)

**Expected behavior**
the file name must match the real name

**Comment by ankar84** [comment] 2021-12-03 08:41
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2206

**Closed by ankar84** 2021-12-03 08:41 UTC
