### ISSUE TITLE
[Version 3.0.2] No valid server found at the url

### ISSUE THREAD

**Issue by kasingal** [RocketChat/Rocket.Chat.Electron#1787] opened 2020-10-05 18:50 UTC
## My Setup

- Operating System: Windows 10
- App Version: 3.0.2
- Installation type: exe, msi (https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.0.2)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
On Rocket.Chat APP, it says 'No valid server found' for the urls (below), though both accessible via web browser:
> http://onap-integration.eastus.cloudapp.azure.com:3000/home
> https://onap-integration.eastus.cloudapp.azure.com/home

### Steps to reproduce:
1. Install Rocket.Chat 3.0.2 using (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/3.0.2/rocketchat-setup-3.0.2.exe)
2. Launch Rocket.Chat and put any Server URL from description above
3. Click on Connect  -> it shows No valid server found error
![image](https://user-images.githubusercontent.com/37604944/95022646-91e34480-0646-11eb-8f50-4844f8349879.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/37604944/95022613-652f2d00-0646-11eb-8890-efb64a499462.png)

### Expected Behavior
It should be able to connect the server as it was working with version 2.17.11 and earlier.

**Comment by drizzit56** [comment] 2020-10-06 08:37
Having the same problem. Trailing slash at the end of the URL fixes the issue but I don't think this is expected behavior as the next time the client is started all of the servers are missing and the URL(S) have to be entered again. They log in instantly when the URLs are entered in again but it seems like something is broken in the client at the moment.

**Comment by Sadrak** [comment] 2020-10-06 08:43
Running into the same issue on Ubuntu.

Some URLs gives an `No valid server found at the URL` (mostly anything with `/home` or `.../home/`), others are accepted but only redirect to a blank page with `nothing`.

**Comment by drizzit56** [comment] 2020-10-06 09:02
For further information. Have had a number of emails from users this morning using Windows, Mac and Ubuntu so seems to be something to do with latest client update and the field cleanup. Same bug in snap package and the deb package.

**Comment by sergeyreznik** [comment] 2020-10-06 09:14
Can confirm that issue with invalid is still there in 3.0.2, Win10

I would be glad to help to resolve this issue?

**Comment by payam124** [comment] 2020-10-06 09:20
> Can confirm that issue with invalid is still there in 3.0.2, Win10
> 
> I would be glad to help to resolve this issue?

I do confirm

**Comment by payam124** [comment] 2020-10-06 09:20
> Can confirm that issue with invalid is still there in 3.0.2, Win10
> 
> I would be glad to help to resolve this issue?

I do confirm

**Comment by sergeyreznik** [comment] 2020-10-06 09:37
I have certain certificates installed on my system (unfortunately, I can't tell more), and  there is one more difference between 3.0.x and 2.17.x - version 3.0.x never asks for a credentials, while 2.17.x does:
![cred](https://user-images.githubusercontent.com/1440331/95184903-4bb5ee80-07c8-11eb-9a4c-a27768766e10.jpg)

**Comment by a5his** [comment] 2020-10-06 09:45
@kasingal Make sure you are running RocketChat server version 2.x or 3.x
https://github.com/RocketChat/Rocket.Chat.Electron/pull/1770

**Comment by drizzit56** [comment] 2020-10-06 09:48
Seems to be a duplicate of #1781

**Comment by drizzit56** [comment] 2020-10-06 09:50
> @kasingal Make sure you are running RocketChat server version 2.x or 3.x
> #1770

For your information this is occurring with server versions 3.3.0, 3.5.1 and 3.6.1 for me.

**Comment by sherwinravindran** [comment] 2020-10-06 14:34
Also getting **Timeout trying to connect** after the upgrade.

**Comment by kasingal** [comment] 2020-10-06 15:40
> > @kasingal Make sure you are running RocketChat server version 2.x or 3.x
> > #1770
> 
> For your information this is occurring with server versions 3.3.0, 3.5.1 and 3.6.1 for me.

How a client is affected by what server version is ?
Server is running fine as I can connect to Rocket.Chat via Web Browser, but Rocket.Chat Windows App (3.0.2) is not working.

**Comment by kasingal** [comment] 2020-10-06 15:41
> Having the same problem. Trailing slash at the end of the URL fixes the issue but I don't think this is expected behavior as the next time the client is started all of the servers are missing and the URL(S) have to be entered again. They log in instantly when the URLs are entered in again but it seems like something is broken in the client at the moment.

Trailing Space, or Servers.json... nothing works !!

**Comment by kasingal** [comment] 2020-10-06 21:27
Instead adding servers.json, or putting server URL on launch screen,
Clicking on **OR** on Top Left, lead to a login page directly which let me login to my Rokcet.Chat server :)

![image](https://user-images.githubusercontent.com/37604944/95261757-f1815180-07f8-11eb-8151-476689df27e2.png)

**Comment by HermanCattaneo** [comment] 2020-10-07 08:39
We had the same problem with the domain:

https://chat.server.companyname domain with cert issued by own pki with own ca cert.

I made a new domain for that: https://chat.compani.tld and with letsencrypt cert and this way I can connect.

Operating System: macOS Catalina 10.15.6
App Version: 3.0.2
Installation type: dmg  (https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.0.2)

**Comment by j0wns** [comment] 2020-10-09 14:29
> We had the same problem with the domain:
> 
> https://chat.server.companyname domain with cert issued by own pki with own ca cert.
> 
> I made a new domain for that: https://chat.compani.tld and with letsencrypt cert and this way I can connect.
> 
> Operating System: macOS Catalina 10.15.6
> App Version: 3.0.2
> Installation type: dmg (https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.0.2)

My SSL and domain configuration sounds similar to the one @HermanCattaneo describes above.

My network and domain are private, that is not internet connected/dependent.
The private domain has an internal Certificate Authority that signs all "domain.local" certificates.
This private root certificate is trusted by all domain machines through the various operating systems' trust libraries.

My RocketChat Server uses an SSL certificate signed by this **private Certificates Authority**.

Everything has been working great for months.

My desktops' electron based RocketChat clients 'break' upon upgrading the desktop client to 3.0.0.
Downgrading to the latest 2.x electron client eliminates the problem immediately.
No other changes have been made to the working server/client/SSL-PKI environment.

Again, the private root certificate is trusted in applicable operating system certificate stores.
HTTPS access using Chromium browsers works regardless of the installed electron clients.

I suspect the 3.X Electron client does not support our private SSL configuration.

Were changes made to the SSL libraries in 3.X of the electron?
Does Electron 3.X use the system's trust root store?
Does the Electron 3.X client perform some sort of new URL/Server validation before storing the server information in the server list?

**Comment by HermanCattaneo** [comment] 2020-10-12 07:00
@j0wns I don't think it's a certificate issue, when I try to tcpdump the client there is no sign of connection if the client says " No valid server found at the url"

> Does the Electron 3.X client perform some sort of new URL/Server validation before storing the server information in the server list?

Yes it has, for sure:
#https://github.com/RocketChat/Rocket.Chat.Electron/commit/91f7c5a2e4ad983c3d81a2383a96ef3b54850f51

Because there is no TCP connection, I can't think anything else than it's validating the url and the private tld is not recognized.

**Comment by ahotzler** [comment] 2020-10-12 08:59
Same problem here. 

In the developer tools you will not see any outgoing connection attempt at all.

I have tested the desktop versions 3.0.1 and 3.0.2 on Win7, server version 3.6.3

Slashes, IP address instead of server name, nothing helps.

**Comment by cmol** [comment] 2020-10-13 13:11
@j0wns I'm running the server with Let's encrypt and are still seeing this, so I'd also find it strange if it was an SSL issue.

**Comment by HermanCattaneo** [comment] 2020-10-13 14:50
@cmol @ahotzler @j0wns 

I found this issue: #1778 

@tassoevan says there:

> For instance, the current "invalid server" errors are result of our first attempt to match the client and the server without giving room for malicious instances abusing the preload script.

So I'am sure they are aware of this problem already and they know the cause.

I would appreciate some feedback from @tassoevan or somebody from the team.

**Comment by tassoevan** [comment] 2020-10-13 18:33
@kasingal it looks like your server version (0.72.3) not supported anymore - only version 2 and above are accessible in the desktop app v3.

**Comment by tassoevan** [comment] 2020-10-13 18:45
I believe many people here are running under the problem of the app having to support subdirectories, so trimming `/home` from the server's URL is tricky. I'll look for a more robust way of getting the root address, but for now consider removing `/home` or anything else before adding the server.

**Comment by cmol** [comment] 2020-10-13 18:52
> I believe many people here are running under the problem of the app having to support subdirectories, so trimming `/home` from the server's URL is tricky. I'll look for a more robust way of getting the root address, but for now consider removing `/home` or anything else before adding the server.

I'm running mine on `chat.domain.tld` directly. No subfolders. The SSL cert is though a wildcard cert for `*.domain.tld` with the server behind an nginx proxy, with both the proxy and chat on Docker. Not sure if that is needed info, but now you know.

**Comment by sergeln** [comment] 2020-10-13 19:15
Fix it in new version 3.0.3.
Ubuntu server 20.04.1
Rocket.Chat Version: 3.7.1                           | 
NodeJS Version: 12.14.0 - x64                   | 
MongoDB Version: 4.0.20
UFW enable
Trusted certificate SSL from my CA
Tnx!

**Comment by ahotzler** [comment] 2020-10-13 19:30
3.0.3 solved the problem for me

**Comment by HermanCattaneo** [comment] 2020-10-13 20:32
@cmol @j0wns

3.0.3 solved the problem (even if its not subfolder related)

thnx @tassoevan

**Closed** 2020-10-13 22:44 UTC

**Comment by j0wns** [comment] 2020-10-19 15:30
I concur, 3.0.4 client allows me to add the server.
