### ISSUE TITLE
Tray icon is invisible on Windows 7 client

### ISSUE THREAD

**Issue by ktsangop** [RocketChat/Rocket.Chat.Electron#852] opened 2018-08-31 07:01 UTC
## My Setup
- Operating System: Windows 7 64bit (latest updates)
- App Version: 2.13.1

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
With latest updates, the tray icon color seems to have changed.
This leads to the following problem as seen on the picture below. The tray icon is not visible at all, unless you hover over it, when a slight outline is visible.

![rocket_chat](https://user-images.githubusercontent.com/25545730/44897429-a3203100-acc9-11e8-9511-bdd0c88d16ba.jpg)

### Reproduce
Go to Control Panel\All Control Panel Items\Notification Area Icons and set Rocket.Chat setting to : 'Only show notifications'

### Current Behavior
Tray icon is invisible

### Expected Behavior
Tray icon should be visible. Probably a thin outline on the icon would be sufficient.

**Comment by tassoevan** [comment] 2018-08-31 13:18
Duplicate of #804

**Closed by tassoevan** 2018-08-31 13:18 UTC
Labels: plat: windows
