### ISSUE TITLE
RocketChat updater buttons don't work

### ISSUE THREAD

**Issue by DesktopZN** [RocketChat/Rocket.Chat.Electron#1149] opened 2019-03-16 05:18 UTC
## My Setup
- Operating System: Windows 10 Pro 1803 x64
- App Version: 2.15.0 update to 2.15.1
- Installation type: exe

- [ ] I have tested with the latest version
- [X ] I can simulate the issue easily

## Description
Update pop-up appears, but cannot click on any buttons other than the x to close.

### Current Behavior
Nothing

### Expected Behavior
Update should install

![image](https://user-images.githubusercontent.com/48612504/54471067-56ff8e80-47cc-11e9-8e73-12b13cc48f3b.png)

**Comment by tassoevan** [comment] 2019-03-16 05:54
Duplicate of #1141.

**Closed by tassoevan** 2019-03-16 05:54 UTC
