### ISSUE TITLE
MacOS version 2.13.0 is available!

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat.Electron#844] opened 2018-08-27 21:19 UTC
@coreyfeder commented on [Mon Aug 27 2018](https://github.com/RocketChat/Rocket.Chat/issues/11880)

Or so the application claims; but clicking Install Update just closes the app. And the latest version listed on the site's Desktop Clients section is 2.12.1. What's up?

---

@MartinSchoeler commented on [Mon Aug 27 2018](https://github.com/RocketChat/Rocket.Chat/issues/11880#issuecomment-416360287)

This issue is related to the desktop client, please reopen this in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!

**Comment by crazy-max** [comment] 2018-08-27 23:27
@tassoevan I saw you removed release 2.13.0, for what reason? I think it's better to keep the workflow in place and rather increment the patchlevel in your versioning if you want to revert.

**Comment by engelgabriel** [comment] 2018-08-27 23:34
I am republishing. I have removed by mistake.

**Comment by engelgabriel** [comment] 2018-08-27 23:47
its back

**Comment by crazy-max** [comment] 2018-08-27 23:50
Thanks @engelgabriel !

**Comment by tassoevan** [comment] 2018-08-28 00:53
It can be related to https://github.com/electron-userland/electron-builder/issues/3269.

**Comment by dzienisz** [comment] 2018-08-28 14:10
I have the same issue. You can't "Install now" the update :(

**Comment by raymondfeliz** [comment] 2018-08-29 00:48
I also got this update to pop up for my OS X users. Is there a means to block it for them? I see that on windows there’s a file in their app data that I can change and do it for them but can’t find a way to do it on OS X client

**Comment by Antairez** [comment] 2018-08-29 05:49
@tassoevan That works as a workaround, thank!

**Comment by dzienisz** [comment] 2018-08-31 08:33
The issue is not resolved. It's still in 2.13.0 :(

**Comment by stan-savransky** [comment] 2018-09-01 06:39
i have some issue after server & client update
![image](https://user-images.githubusercontent.com/42885891/44943187-912eb300-addb-11e8-9df8-8dca7efca642.png)
server version 0.69.0
macOsx client 2.13.0 & 2.13.1

web version is works fine

**Comment by compuguy** [comment] 2018-09-19 20:09
This is still happening with the upgrade from 2.13.2 to 2.13.3.

**Comment by Antairez** [comment] 2018-09-20 02:50
Exactly, update has been a problem on both Windows and MacOS platform recently. I face both issues because I have two computers.

**Comment by compuguy** [comment] 2018-09-20 14:01
@tassoevan #857 seems specific to Windows. I'm having this issue with Mac OS X.

**Comment by tassoevan** [comment] 2018-09-21 05:10
@compuguy Would you mind opening a new issue for your case? I'd like to have more specific information, like how Rocket.Chat was installed at first time and at which version.

**Comment by compuguy** [comment] 2018-09-21 14:20
@tassoevan Done, new issue is #894.

**Comment by tassoevan** [comment] 2018-11-19 06:37
Anyone can confirm it's working for MacOS after 2.14.1?

**Comment by jeanfbrito** [comment] 2022-01-10 18:21
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:21 UTC
Labels: plat: osx
