### ISSUE TITLE
Error in plugin "gulp-execa" on Arch Linux

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat.Electron#1496] opened 2020-02-04 00:01 UTC
Hi @tassoevan I hope you're energized for 2020, you may want to look at this :sweat_smile: 

This Happen only on Linux so far on `yarn start` and `yarn release`, Windows and Mac are unaffected.
I have opened an issue on the Execa repo:
https://github.com/ehmicky/gulp-execa/issues/4

I have also noticed that the fsevent 1.2.9 is not compatible with the Linux platform.
`[!] Error: Could not resolve './preload/spellChecking' from src/preload.js`

```
[00:36:35] 'build:bundle' errored after 5.14 s
[00:36:35] Error in plugin "gulp-execa"
Message:
    Command failed with exit code 1: rollup -c
Stack:
Error: Command failed with exit code 1: rollup -c
Stack:
Error: Command failed with exit code 1: rollup -c
    at makeError (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[00:36:35] 'build' errored after 5.15 s
[00:36:35] 'start' errored after 5.15 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Kind Regards,

**Comment by tassoevan** [comment] 2020-02-04 00:17
> I hope you're energized for 2020
⚡⚡ ABSOLUTE HIGH VOLTAGE⚡⚡

I've merged some significative breaking changes today, so I'm expecting unfortunate bugs coming. I'll check this one ASAP.

**Comment by franckadil** [comment] 2020-02-04 00:22
⚡⚡ ABSOLUTE HIGH VOLTAGE ⚡⚡ :smiley:  well that's good to know :zap: keep it up ! :electric_plug:

**Comment by tassoevan** [comment] 2020-02-04 00:34
Is it possible that the file `./preload/spellChecking.js` has a different case in your fork, i.e.,  `spellchecking.js` instead of `spellChecking.js`? NTFS (Windows) and APFS (MacOS) are case-insensitive by default, but Ext (Linux) isn't.

**Comment by franckadil** [comment] 2020-02-04 00:43
@tassoevan I have checked the .../src/preload.js and the case is fine:
![image](https://user-images.githubusercontent.com/42721509/73703282-b1108780-46ef-11ea-9ad2-ac51f2d681c4.png)

**Comment by tassoevan** [comment] 2020-02-04 00:50
That's odd. It has nothing to do with `gulp-execa`, but with `rollup`. I can't reproduce the error **unless I explicitly rename the file `spellChecking.js` as `spellchecking.js`** while keeping those lines untouched.

**Comment by franckadil** [comment] 2020-02-04 00:52
I think we have found the culprit: 
![image](https://user-images.githubusercontent.com/42721509/73703662-fa150b80-46f0-11ea-8b36-043504ed7e32.png)
I'll give it a try now :smile:

**Comment by franckadil** [comment] 2020-02-04 00:54
You are right! that's the issue. You officially saved the day :heart_eyes:  :medal_sports:

**Closed** 2020-02-04 01:08 UTC
