### ISSUE TITLE
Rocket.Chat Notification Problem

### ISSUE THREAD

**Issue by erkankyn1** [RocketChat/Rocket.Chat.Electron#1376] opened 2019-11-01 08:30 UTC
## My Setup
- Operating System: Windows 10
- App Version: 2.15.5
- Installation type: EXE

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Hello everybody. I have an issue. My RocketChat Electron is not working normally.
If my electron is hidden mode and someone was texting me, the notification light and number is not showing. Sorry for my bad expression. Please look at the attachment.
![2019-11-01_11-20-20](https://user-images.githubusercontent.com/41471219/68012087-25273380-fc9a-11e9-87a0-ae6952a68db5.png)

### Current Behavior

No notification light or number.

### Expected Behavior

Notification light and message number.

![asddd](https://user-images.githubusercontent.com/41471219/68012344-d29a4700-fc9a-11e9-8c1f-1d1c5d65a603.png)

**Comment by marcosmolinamaxicon** [comment] 2019-11-06 16:50
I have some problem

**Comment by ddbrandonb** [comment] 2019-11-07 12:01
We are also having this issue. The issue seems to be related (in my testing) to minimizing RocketChat by clicking the taskbar icon to minimize, rather than the actual minimize button itself.

**Comment by ddbrandonb** [comment] 2019-11-08 12:31
I just confirmed this bug still exists in 2.16.2. @marcosmolinamaxicon and @erkankyn1 could you see if the problem persists when "hiding" rocketchat using the minimize button on the title bar? 

I can easily reproduce this issue in my environment by:

1. Opening RC desktop client and logging in.
2. Maximize using the taskbar RC icon, then quickly (within 3-10s) minimize by clicking the same RC taskbar icon (NOT the title bar minimize button!).
3. Now from another account send a message to the account logged into your test machine.
4. No blinking notification on the icon.

If you do the same steps but you do use the window title bar minimize button the blinking taskbar notifications work every time.

**Comment by CitizenDev** [comment] 2019-11-14 14:23
For me its even weirder, no matter the amount of unread messages, I only get a single dot, never the number of unread messages and the icon behind it always remains gray.

**Comment by orelinde** [comment] 2019-12-30 12:31
I think I got a little further with this:
Apparently, there is an issue with Electron itself (https://github.com/electron/electron/issues/9092). Even thought that issue is closed, the issues still remain. This means that the _isMinimized()_, _isMaximized()_, _isFocussed()_ methods of the browserWindow give invalid values back. For the notification system, the behavior is all depending on those values.

if I overwrite those Electron functions of the BrowserWindow in the mainWindow.js file:
```	
	browserWindow.isMaximized = function () {
		const { outerWidth, outerHeight, screen: { availWidth, availHeight } } = global;
		return availHeight == outerHeight && availWidth == outerWidth;
	}

	browserWindow.isMinimized = function () {
		return document.visibilityState == 'hidden';
	}

	browserWindow.isFocused = function () {
		return document.hasFocus();
	}
```

Then it all starts to work again. 
> Please note that I am using visibilityState == 'hidden', which doesn't always mean that the window is hidden:
([Source:MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState)) The page content is not visible to the user. In practice this means that the document is either a background tab or part of a minimized window, or the OS screen lock is active.

**Comment by jthomae1** [comment] 2020-07-08 13:36
The issue still seems to be open (v3.1.1)

**Comment by jeanfbrito** [comment] 2022-01-12 00:52
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:52 UTC
Labels: type: bug, plat: windows, feat: tray icon / dock / taskbar
