### ISSUE TITLE
Move distribution from snap to AppImage

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.Electron#2084] opened 2021-07-01 17:52 UTC
## My Setup

- Operating System: Linux
- App Version: 3.2.2
- Installation type:  snap

- [ x ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Please move distribution of the linux client from snap to AppImage. Snap is auto updated and usually break all my linux clients rocketchat installation. The last really stable version for linux is 3.1.0. The more recently segfaults a lot. Simple example: Try to enable/disable tray icon on Linux Mint. It crashes.
Using AppImage let the Administrator easily choose when updates and do a better QA process.

**Comment by tmartincpp** [comment] 2021-09-07 16:33
Kind of duplicate of #1270.

**Comment by reetp** [comment] 2021-09-29 10:46
It is a duplicate of #1270 and closing accordingly.

Please follow up on the original Issue.

**Closed by reetp** 2021-09-29 10:46 UTC
