### ISSUE TITLE
Updates not installing

### ISSUE THREAD

**Issue by sheriikeda** [RocketChat/Rocket.Chat.Electron#1399] opened 2019-11-19 18:00 UTC
## My Setup
- Operating System: Windows 10 Enterprise
- App Version: 2.15.5
- Installation type: N/A

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Updates to not install

### Current Behavior
I receive a daily popup after rebooting my machine, stating, "New Update is Available". I click "Install Update", then receive another popup stating, "You will be notified when the update is ready to be installed" however the update is never installed.

The only way to clear this issue is by completely uninstalling the app and installing a fresh, current copy.

I had this issue with a prior version as well but cannot recall what version that was.

### Expected Behavior
After clicking "Install Update", the update should install.

**Comment by avignat** [comment] 2019-11-20 09:22
Same here

**Comment by Sicoval31** [comment] 2019-11-21 07:47
same here since the last three version.

**Comment by sgostelow** [comment] 2019-11-21 09:19
Yes, we've also experienced this issue on Windows clients.

**Comment by lucianomlima** [comment] 2019-11-24 16:48
macOS Catalina 10.15.1
Rocket.Chat 2.16.1

Always show this screen and never upgrades

![image](https://user-images.githubusercontent.com/1580205/69497938-f2e7ab00-0ec0-11ea-97bd-989a525bb016.png)

**Comment by ankar84** [comment] 2019-11-26 11:03
Same here 2.16.0 to 2.16.2

**Comment by alleait** [comment] 2019-11-28 09:46
This happens for me also , Windows 10 machines , been going on since a few versions before .

**Comment by foss-** [comment] 2019-12-02 08:29
Continuing 2.16.2 to 2.17.0, macOS 10.14

- shows "Install Now" "Install Later"
- Clicking Install Now does not restart app
- Manually quitting and then restarting the app resulted in crash ([log here, 1 year)](https://bin.disroot.org/?ea405671d8f67143#DXaMfYVNbJmqs2nWfSVB1ANAqeA6pU6yRFXk2nhak59f)
- crash reproducible when app is started

in 2.17.0 there were fixes in regards to updates:

- [FIX] Loading error view updates #1412 
- [FIX] Update dialog events #1381

Guess 2.17.0 has to be installed manually for those fixes to take effect.

**Comment by cdisabatino** [comment] 2019-12-02 09:27
I have the same problem. Version 2.16.2 to 2.17.0.

**Comment by lucianomlima** [comment] 2019-12-02 15:10
Please, read the foss- comment:

> Guess 2.17.0 has to be installed manually for those fixes to take effect

**Comment by cdisabatino** [comment] 2019-12-04 11:59
I have installed version 2.17.0.
In the "Propo" menu, there are no more update options.

Does this version still allow automatic update ?

Thank you

**Comment by ankar84** [comment] 2019-12-05 04:55
> I have installed version 2.17.0.
> In the "Propo" menu, there are no more update options.
> Does this version still allow automatic update ?
I have same question. 
No updates options anymore:
![image](https://user-images.githubusercontent.com/4023037/70205291-a27c1300-1734-11ea-9bb5-d7e51c0fc70a.png)

**Comment by cdisabatino** [comment] 2019-12-11 13:33
I am currently in version 2.17.0. Since this morning, I have a popup to update to version 2.17.1.

Rocketchat does not update even after clicking the '_Install update_' button.

The bug is still present in version 2.17.0.

![rocketchat update](https://user-images.githubusercontent.com/46713357/70625617-0f0a7c80-1c23-11ea-9e50-123e4fd179f1.png)

**Comment by Anigif** [comment] 2019-12-13 08:29
I guess this is the same issue stated in #1205?

**Comment by DevAntonP** [comment] 2019-12-19 17:50
@cdisabatino is right. The bug still exists.

**Comment by zedar187** [comment] 2019-12-20 09:43
+1

**Comment by cdisabatino** [comment] 2020-02-05 08:49
With version 2.17.3, the update option is available again but when click on the button "Check for updates", the error "dialog.about.errorWhileLookingForUpdates" is displayed. I tested with two network connections, Wifi and RJ54. Without proxy.

![image](https://user-images.githubusercontent.com/46713357/73825483-50bb3c00-47fc-11ea-84bb-e5574b2eee8b.png)

**Comment by foss-** [comment] 2020-02-05 08:51
@cdisabatino That is pretty certainly a different problem so created a different issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1500

**Comment by cdisabatino** [comment] 2020-02-05 09:11
> 
> 
> @cdisabatino That is pretty certainly a different problem so created a different issue: #1500

Sorry, thanks.

**Comment by csymvoul** [comment] 2020-11-03 11:54
Same here.  Every  time I open the rocket chat the notification regarding the new update is shown. I press the  "Install Update " button and I get a "We'll notify you when the update is complete" message. But nothing happens.

**Comment by groemer05** [comment] 2020-11-09 06:46
Same here

**Comment by archisint** [comment] 2020-11-10 13:50
Same thing here, not working on windows 10.

**Comment by Fosol** [comment] 2020-11-11 16:29
This has been going on for me for over a year...  Windows 10

**Comment by ephi0815** [comment] 2020-11-12 09:12
Currently the client offers the update from 3.0.6 to 3.0.7. "Install Update" does not cause an update. The behaviour is the same since 2.17.0 (Win10).

**Comment by Frank-RC** [comment] 2020-11-13 08:06
Hy all,

same problem here (Win 10) again and again since years. Meanwhile with V 3.0.5 to 3.0.7 and the all time promise to be "notified when the update is ready to be installed", since now that means "never".

After having downloaded and installed the last update 3.xy manually my RC-host wasn't accepted any more. Uninstalling and new installation solved that problem.

**Comment by solrosin** [comment] 2020-11-17 16:43
This has been an open issue for over a year and hasn't been fixed.

**Comment by tungdt-90** [comment] 2020-11-20 15:18
![image](https://user-images.githubusercontent.com/8186562/99816448-48ab6d80-2b7e-11eb-86a6-e10aad63c0cd.png)
Still happens in version 3.0.6.
Windows 10 Pro

**Comment by klepp0906** [comment] 2020-11-30 20:59
just found this as its happening to me as well.  updated manually to 3.06 because prior 2.xx version wasnt updating either.  Immediately upon starting it prompted for 3.07 but the behavior persists, cant update.

**Comment by densik** [comment] 2020-12-08 18:28
Can't update from 3.0.6 -> 3.0.7 either. This has been happening for many releases back to back now. I uninstalled and reinstalled and it still occurs, I tried installing per-user and all users, both not working.

**Comment by CSchmidtDD** [comment] 2020-12-29 13:51
This needs to be higher priority. It is a pain to see the message everytime you open it up.
Am behind proxy, still without proxy is does the same - nothing. Related Issue #1445

**Comment by fotisj** [comment] 2021-05-29 18:31
Same here (windows 10)

**Comment by therealZottel** [comment] 2021-09-08 13:39
Still exists with 3.5>3.5.1 (Windows 10)

**Comment by benwick** [comment] 2021-09-22 07:11
+1

**Comment by ankar84** [comment] 2021-09-22 08:12
Closing that issue as duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Closed by ankar84** 2021-09-22 08:12 UTC
Labels: type: bug, feat: installer / update
