### ISSUE TITLE
Rocket.Chat lags, extremely cpu load and black screen on linux

### ISSUE THREAD

**Issue by Kernell** [RocketChat/Rocket.Chat.Electron#1114] opened 2019-02-27 13:56 UTC
## My Setup
- Operating System: Ubuntu 18.04 and OpenSUSE Tumbleweed
- App Version: 2.14.7
- Installation type: tested on deb, snap and rpm

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

We use Rocket.Chat as a means of communication within the company's network. We have about 20 employees who use it (technical department). At first time everything was fine until many messages appeared in the chat (mostly in two channels).

Now when Rocket.Chat Desktop started (or when you open it in the browser), we see a very heavy freezes and CPU usage is above 150% and crash (black screen or firefox\chrome error) after a few seconds. This completely blocks the work of users, the chat is no longer possible to open (sometimes it turns out, but after a while again a black screen).

I tested this problem with different users on freshly installed Ubuntu 18.04, openSUSE Leap 15.1 and Tubmleweed.

Our organization uses mainly Ubuntu 18.04 (previously 14.04) and they all have these problems. Only users on Windows have no problems. Rocket.Chat on Windows 10 works almost perfectly.

### Current Behavior

I think that Rocket.Chat at startup tries to load all chats and cannot cope with this.

**Comment by tassoevan** [comment] 2019-02-27 14:40
Could you provide some info about your Rocket.Chat server too following [this template](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by Kernell** [comment] 2019-02-28 06:56
@tassoevan 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: CentOS 7 (3.10.0-862.2.3.el7.x86_64)
- Deployment Method: docker (18.09.0-beta5, build e1910c5)
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0

**Comment by tassoevan** [comment] 2019-03-08 01:37
I've found that #1131 is caused by a misbehavior of spell checking. Could it be a root cause here too?

**Comment by chrBrd** [comment] 2019-03-08 12:28
I'm experiencing the same issue on OpenSUSE TW. On an 17-2600k it's at ~20-40% CPU load when writing a comment, and spikes above 80% on editing. It's very, very laggy.

If this was an issue with the system spellchecker I'd expect to see it in other Electron applications, but Skype, VS Code and Slack all perform fine.

**Comment by tassoevan** [comment] 2019-03-08 14:41
@chrBrd Sure, soon a patch will fix it.

**Comment by Kernell** [comment] 2019-03-25 06:18
> I've found that #1131 is caused by a misbehavior of spell checking. Could it be a root cause here too?

As I said earlier, problems occur when starting the client. This means that it is logical that this is not related to spell checking, since users cannot even begin to write text.

**Comment by Kernell** [comment] 2019-04-10 13:18
Apparently it's easier for me to find an alternative for Rocket.Chat, than to wait for the solution of the problem.
Has nobody come across this?

**Comment by fabien-michel** [comment] 2019-04-18 09:03
RocketChat permanently use 10 to 15% of my CPU when idle. (I have a 4-cores Intel Core i5-5257U 2.7Ghz) I'm on Manjaro/Arch Linux. I'm using the last version (2.15.9) but got the problem since installed this app on Linux.

The web version does not make the browser (firefox) being so much hungry in CPU.
I'm using other electron apps (VSCode) which does not have this problem.

I'm connected to a single locally hosted server serving only in http (no https) (webkit warn to not use cache because of http, see logs below)
I've subscribed to many channels (around 20) plus a lot of privates messages with others users. 

Webkit logs if devtools:

```webview: Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.

webview: Error: Cannot find module 'meteor/rocketchat:utils'

webview: Error: Cannot find module 'meteor/rocketchat:settings'

webview: WebSocket connection to 'ws://rocketchat.hespul.org/sockjs/434/3byqcyp2/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

webview: Uncaught TypeError: Cannot read property 'match' of null

```

How can I help you to debug this problem ?

**Comment by fabien-michel** [comment] 2019-04-18 09:39
Ok, we have upgraded server to last version and problem seems to not occur anymore.
Sorry for the noise.

**Comment by engelgabriel** [comment] 2020-08-12 22:55
@tassoevan should we close this issue?

**Closed** 2020-08-14 13:02 UTC
Labels: plat: linux, subj: performance
