### ISSUE TITLE
Clicking "About Rocket.Chat+" causes error pop-up

### ISSUE THREAD

**Issue by shellster** [RocketChat/Rocket.Chat.Electron#443] opened 2017-05-10 21:58 UTC
## My Setup

 - __My OS name and version__:  Windows 10
 - __My current app version__:  Rocket Chat 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Clicking "About Rocket.Chat+" from the "Rocket.Chat+" drop-down immediately displays an error pop-up

Title: "Error"

Header: "A JavaScript error occurred in the main process"

Message:

Uncaught Exception...

#### Current Behavior

Error message pops up and a blank about window is shown

#### Expected Behavior

No error message, and display the version information.

**Comment by engelgabriel** [comment] 2017-05-11 03:38
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/427

**Closed by engelgabriel** 2017-05-11 03:38 UTC
