### ISSUE TITLE
Remove annoying popup after minimizing to system tray

### ISSUE THREAD

**Issue by gmnevton** [RocketChat/Rocket.Chat.Electron#1816] opened 2020-10-15 08:01 UTC
## My Setup

- Operating System: Windows 10
- App Version: 3.0 +
- Installation type: exe

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
Same as in title, please do something about it quickly, thanks.

### Current Behavior
When minimizing app to system tray the popup is displayed informing about the app is still running, when you click it, the app is restoring itself back to view, and now You can minimize it again and popup is shown again, and you can minimize it ......
It is stupid, please remove this popup, as I think when user is minimizing the app, it knows that it runs in background.

### Expected Behavior
Nothing at all, app should minimize and run in background as it was before update to version 3.0.

**Comment by lk3de** [comment] 2020-10-19 09:25
Duplicate of #1749

**Closed** 2020-10-19 14:11 UTC
Labels: stat: duplicate
