### ISSUE TITLE
3.11 and 3.10 stay always minimized in tray

### ISSUE THREAD

**Issue by robonuka** [RocketChat/Rocket.Chat.Electron#1935] opened 2021-01-02 04:10 UTC
OS: Xubuntu 20.04.1
App version: 3.1.X
Installation type: dpkg -i rocketchat_3.1.X_amd64.deb

## Description
Application 3.1.0 and 3.1.1 started successfully but always stay minimized in tray.
I can't open application window after that at all!
Application running but present in tray only as icon. That's it.

### Expected Behavior
Application version 3.0.7 doesn't have this bug.

**Comment by ekkipatang** [comment] 2021-01-04 09:40
Same for me.

OS : Kubuntu 20.04
App version : 3.1.1
Installation : flathub repo

**Comment by Xarkam** [comment] 2021-01-04 12:30
Same for me.

OS : KDE Neon
App version : 3.1.1
Installation : debian package

**Comment by tomas-chrastina** [comment] 2021-01-06 00:20
Same here (Xubuntu).

Also every time I change **View > Tray Icon** (on or off), application will crash. Then it will start with Tray icon displayed/hidden as it should (according to setting).

```
kernel: [ 7424.091337] rocketchat-desk[14439]: segfault at ffffcba1294ab7f9 ip 000055704083e32d sp 00007ffc3bd75020 error 5 in rocketchat-desktop[55704074b000+5f8d000]
kernel: [ 7424.091346] Code: c3 cc cc cc cc cc cc cc cc cc cc cc cc 55 48 89 e5 41 56 53 48 83 ec 20 48 8b 87 98 fc ff ff 48 8d b7 98 fc ff ff 48 8d 7d d8 <ff> 90 b8 00 00 00 48 8b 5d d8 4c 8b 75 e0 4c 39 f3 74 1a 48 8b 3b
kernel: [ 7652.225593] rocketchat-desk[14623]: segfault at 8 ip 00005579facf673c sp 00007ffeb22446c0 error 4 in rocketchat-desktop[5579fac02000+5f8d000]
kernel: [ 7652.225604] Code: 55 d8 48 8b 45 e0 48 8b 0e 48 8b 5e 08 48 89 df 48 29 cf 48 c1 ff 03 48 39 c7 48 0f 43 f8 48 39 fa 74 95 48 8b 3c d1 48 8b 07 <ff> 50 08 48 8b 75 d0 48 85 f6 0f 84 d5 00 00 00 48 8b 45 d8 48 8b
```

**Comment by leederFox** [comment] 2021-01-06 21:05
Same here,

OS: Fedora 33
App version : 3.1.1
Installation: RPM package
Window Manager: Openbox 3.6.1
Panel: lxpanel 0.10.0

Version 3.0.7 works well.

**Comment by atemp** [comment] 2021-01-07 09:50
same here, at first run all looks good, once the window is hidden and only the tray icon is visible, i found no way to recover - not even by restarting the client

OS: CentOS 7.9
App version: 3.1.1
Installation: RPM package
Desktop: MATE (mate-panel-1.16.2-1.el7.x86_64)

3.0.x worked fine, 3.1 is practically unusable.

**Comment by Romich777** [comment] 2021-01-12 11:17
Same for me with Linux Mint Cinnamon 20.1
Issue with 3.1.0 and 3.1.1.
3.0.7 - works fine

**Comment by pixxelspotter** [comment] 2021-01-13 12:13
Same Problem here

OS: Ubuntu 16.04.7
Desktop: MATE
3.0.7 worked fine but had some other problems

**Comment by 29ggf** [comment] 2021-01-14 21:47
Same for me. Also the icon doesn't update to show the notification red dot. One shouldn't count on it to see if you have missed messages.
RC Version 3.1.1
AUR Package
Manjaro 20.2.1
XFCE 4.14
Works after downgrading to 3.0.7

**Comment by Mates** [comment] 2021-01-15 18:13
Same here. The icon is also "frozen" for me and doesn't update with new messages.

OS: Linux Mint 20.1 Ulyssa
App version: 3.1.1
Installation: DEB package
Desktop: MATE 1.24.0

Downgrading to 3.0.7 works.

**Comment by paulz1** [comment] 2021-01-25 12:14
Still nothing on this issue ?

I have the same :
OS: Fedora 33
App version : 3.1.1
Installation: Flatpak (Rocket.Chat                               chat.rocket.RocketChat                        3.1.1    stable  system )
Desktop: XFCE

**Comment by tomas-chrastina** [comment] 2021-01-25 12:19
I suggest to stick with version `3.0.7` until next release (let's hope they'll correct this).

Latest rocket won't reach orbit, I guess...

**Comment by pixxelspotter** [comment] 2021-01-25 12:20
We Reverted back to 2.16.2 as Jitsi calls are still broken in 3.0.7

**Comment by h1pp13p373** [comment] 2021-01-26 18:28
Same here, Ubuntu 20.04 with kubuntu-desktop installed, 64bit.  I tried both the .deb package and building from source and both disappear as soon as I check "tray icon" in the menu.  Reverting to 3.0.7 fixed it for me as well.

**Comment by tomas-chrastina** [comment] 2021-02-03 00:38
FYI, I tested latest snapshot from snap => still not working.

OS: `Xubuntu 20.04.1`
Installation Type: `snap`
Version: `3.2.0-snapshot` `(2021-02-01)`
Channel: `latest/edge`

**Comment by nicoroeser** [comment] 2021-02-08 07:02
I have done a git bisection with good=3.0.7 (dcf7a9c0a6f78ac87a1006d835b990055af56d1c), bad=current master (3b2d0aaa51eaf96442c3084eaeb8621465d40cee).

Result: this is an intermittent problem. Main window did not open with 3b2d0aaa5 in my first test, but opened with the exact same revision in my last test.

The source of the problem is not directly related to Rocket.Chat.Electron version 3.1.1 vs. 3.0.7. It possibly rather happens due to some dependency on a networking connection (like reported in #1950). While I was running the tests, I had some problems with network connections to the networks of GitHub, Google and some others (but not to the network in which my target Rocket.Chat server was located, I think).

**Comment by tomas-chrastina** [comment] 2021-02-11 03:18
I installed version 3.1.1 in Windows 10.
When I left click on tray icon (Windows behavior) =>> window will appear => OK
When I right click tray icon, and select **Show** from menu (Linux behavior) => Doesn't work 

It looks like **Show** from tray menu is not working in Windows/Linux, rather than some network related problem(which would be strange).

**Comment by adocampo** [comment] 2021-02-17 12:50
Same here on Arch Linux + Plasma. RC 3.1.1
I've opted to not show the tray icon and let RC run in the taskbar, when I close the application, though, I really close it and I need to open it back, so, sometimes I'm missing some chats until I realize I don't have the application opened.

**Comment by vimu86** [comment] 2021-02-23 10:21
Same issue here: Ubuntu 20.04 with RC 3.1.1.

**Comment by vimu86** [comment] 2021-02-23 10:45
I deleted all files in `.config/Rocket.Chat/` and was able to use the app again. Certainly not the best solution, but at least a work-around.

**Comment by Xarkam** [comment] 2021-02-23 10:56
> I deleted all files in `.config/Rocket.Chat/` and was able to use the app again. Certainly not the best solution, but at least a work-around.

Just edit your _config.json_ and modify these two keys:
```json
"isTrayIconEnabled": true,  // => change this for false
"visible": false,   // => change this for true
```
The first key, disable systray icon and second key, restore the window from tray minimized.

**Comment by neonardo1** [comment] 2021-03-02 15:58
Same issue here.

**Comment by minusHysteria** [comment] 2021-03-02 16:02
Same happening for me, rly annoying.

**Comment by KeiroD** [comment] 2021-03-03 11:44
Can confirm this issue persists for me as well. This makes using the app extremely difficult if you want to manage how much of your screen estate is taken up.

**Comment by imifarago** [comment] 2021-03-03 20:55
Happening the same here for a while.

OS : Arch Linux with KDE Plasma 5
App version : 3.1.1
Installation : aur/rocketchat-desktop 3.1.1-1

When set / unset tray from the menu, the app crashes:
```
[Wed Mar  3 21:40:56 2021] electron[1750]: segfault at 8 ip 000055d17d2c6605 sp 00007ffe8878c820 error 4 in electron[55d17d136000+5e77000]
[Wed Mar  3 21:40:56 2021] Code: 43 d6 48 39 55 98 75 09 e9 87 00 00 00 48 8b 4d 90 48 8b 55 c8 48 39 c8 75 06 48 3b 55 98 74 74 48 8b 00 48 8b 3c d0 48 8b 07 <ff> 50 08 48 8b 45 c0 48 85 c0 74 88 48 8b 4d c8 48 8b 7d d0 48 8d
[Wed Mar  3 21:49:39 2021] electron[17826]: segfault at ffffec8518ee78d6 ip 00005641476b015f sp 00007ffd1adcc160 error 5 in electron[564147521000+5e77000]
[Wed Mar  3 21:49:39 2021] Code: 57 41 56 53 48 83 ec 28 64 48 8b 04 25 28 00 00 00 48 89 45 e0 48 8b 87 68 fc ff ff 48 8d b7 68 fc ff ff 4c 8d 75 c8 4c 89 f7 <ff> 90 b8 00 00 00 49 8b 1e 4d 8b 76 08 4c 39 f3 74 1f 4c 8b 3d 90
```

**Comment by peylight** [comment] 2021-03-18 09:37
Same problem for KDE Debian 10

**Comment by herod2k** [comment] 2021-04-13 17:48
Same here:
Arch linux
Awesome WM
Every thing updated to the latest version.

Once you activate the tray icon and minimize it, the only way to restore it is to change de config file manually.

**Comment by TibboddiT** [comment] 2021-04-14 11:31
The problem seems to come from #1700, [this change](https://github.com/RocketChat/Rocket.Chat.Electron/pull/1700/files#diff-07e5ceb88228a04db4a76648c120a91e55da6de3fa66830c2a6aa4c79ed395d0) to be specific.

![image](https://user-images.githubusercontent.com/1615839/114703070-21b82880-9d25-11eb-8bf3-943ad63a7461.png)

@tassoevan As the author of the PR, is there a reason to use the focused state to determine the window visibility ?

I can make a PR, I currently use a custom build with the aforementioned change reverted, and everything works.

**Comment by senpl** [comment] 2021-04-14 11:47
@TibboddiT PR that fix issues for many users is always good to have. It also allows other to easly check if this solve issue for them and not search own solutions.

**Comment by pixxelspotter** [comment] 2021-04-14 12:16
@TibboddiT A PR is a good thing, but it also has to be merged into the new version and thats the bigger Problem...

**Closed** 2021-04-19 22:21 UTC
