### ISSUE TITLE
Login Issue with Github Two-Factor Authentication

### ISSUE THREAD

**Issue by RyanWoodward84** [RocketChat/Rocket.Chat.Electron#1163] opened 2019-03-30 21:52 UTC
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The app errors when attempting to sign in from a GitHub account secured with two-factor authentication

### Current Behavior
Attempting to sign into a new server using a 2-factor authenticated github account. Successfully enter login name and password. Screen then moves to the next screen asking for the two-factor authentication password. Before I even have a chance to input the password the whole process errors and the screen immediately states connection to server failure.

### Expected Behavior
I should be able to enter my two-factor password and login successfully.

**Comment by itchison** [comment] 2019-03-31 04:29
This issue is not present on the 2.14.7 client.

**Comment by tassoevan** [comment] 2019-03-31 21:25
I couldn't reproduce it with 2.15.1. @LostCatalyst, are you using multiple servers?

**Comment by cvarjao** [comment] 2019-04-01 15:01
@tassoevan , yes. We have multiple servers. We are hosting RocketChat and MongoDB in OpenShift with minimum of 3 replicas each.

**Comment by filiy** [comment] 2019-04-01 19:21
Yes I believe the issue is more around Custom OAuth

**Comment by fspijkerman** [comment] 2019-04-16 09:09
> Yes I believe the issue is more around Custom OAuth with redirect login style and 2.15.1

I believe so too, I'm having the same issue.
I'm using Keycloak in combination with 2FA, when changing the Login Style from Redirect to Popup it works again. My Rocketchat is a single server setup running in docker.

**Comment by mheistermann** [comment] 2019-07-03 21:04
There is a possible fix in https://github.com/RocketChat/Rocket.Chat.Electron/pull/1275 (or https://github.com/RocketChat/Rocket.Chat.Electron/pull/1274 on master instead of develop branch)

**Comment by jeanfbrito** [comment] 2022-01-12 00:19
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:19 UTC
Labels: type: bug, feat: web view
