### ISSUE TITLE
Update installer dialog buttons do not work

### ISSUE THREAD

**Issue by sunergeo** [RocketChat/Rocket.Chat.Electron#1207] opened 2019-05-02 13:26 UTC
## My Setup
- Operating System: MacOS High Sierra 10.13.6
- App Version:2.15.0
- Installation type: dmg

- [ ] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
The buttons on the update installer window do not work, preventing me from applying the latest update.

### Current Behavior
I am prompted by the update checker with a window asking if I want to update.  The only response button that does anything is the "Skip This Version" button

### Expected Behavior
All buttons should work

**Comment by tassoevan** [comment] 2019-05-02 13:40
Duplicate of #1141. The workaround is to manually download and install the newest version.

**Closed by tassoevan** 2019-05-02 13:40 UTC
