### ISSUE TITLE
Permalink in direct messages does not work

### ISSUE THREAD

**Issue by c-hoeger** [RocketChat/Rocket.Chat.Electron#842] opened 2018-08-27 08:47 UTC
Version 2.11.0
macOS High Sierra

Reproduce:

- In a direct chat, create a permalink.
- paste the permalink
- click on the permalink as poster of that link -> works
- click on the permalink as chat partner -> opens a direct chat with yourself

**Comment by JakubJachym** [comment] 2020-04-06 07:41
Yeah. That is really annoying. Was just about to open a new issue and I'm unpleasantly surprised it's here since 2018. 😂 It would be really great if someone can fix it.

I'll add some details to @c-hoeger's reproduce instructions, so it is really clear what is going on:

- Say we have two users `USER_A` and `USER_B`. 
- `USER_A` sends a direct message to `USER_B`
- `USER_B` creates a permalink to the `USER_A`'s message and posts it back into the chat
- The link will look like: `https://URL/direct/USER_A?msg=1234567890abcdef`.
- When you then click at the link as `USER_B`, it works, because it opens DM with `USER_A`.
- However, if you are `USER_A` and click the link, it opens direct message to `USER_A` (yourself) and obviously fails to show the message.

I guess the URL needs to contain both parties in the URL or neither party and just search the message by ID and open particular DM without specifying the parties involved explicitly.

**Comment by jeanfbrito** [comment] 2022-01-10 18:22
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 18:22 UTC
