### ISSUE TITLE
@ not working when used at the beginning of a message

### ISSUE THREAD

**Issue by AureNP** [RocketChat/Rocket.Chat.Electron#1425] opened 2019-12-03 03:47 UTC
## My Setup
- Operating System: Win 10
- App Version: 2.17.0
- Installation type: exe
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![image](https://user-images.githubusercontent.com/58455091/70018834-771beb80-15af-11ea-82e4-2bd777841681.png)

### Current Behavior
whenever @ followed by a username or shortcut is used at the beginning of a message, the mention is not working
### Expected Behavior
We should have the @ being acknowledged as a mention and trigger the email without the need to add a space before.

**Comment by ankar84** [comment] 2019-12-03 04:26
My setup is the same, but I don't have that bug. All mentions are working at the beginning of any message. And in a middle @ works fine.
@ do not work after \ sign and I think it is by design (escape sign)

**Comment by AureNP** [comment] 2019-12-03 04:32
Humm interesting, @ works fine in the middle of the message but not at the beginning like shown in the new screenshot. Are you running the latest RC windows version? 

![image](https://user-images.githubusercontent.com/58455091/70020745-04623e80-15b6-11ea-8cd2-976597cc415f.png)

**Comment by ankar84** [comment] 2019-12-03 05:52
> Are you running the latest RC windows version?

Yes, latest Electron RC version 2.17.0 and latest RC server version 2.3.0
![image](https://user-images.githubusercontent.com/4023037/70023939-fad2d980-15a9-11ea-8e70-6fa730d1acad.png)
![image](https://user-images.githubusercontent.com/4023037/70023969-0920f580-15aa-11ea-8361-1ede092e4e63.png)

**Comment by AureNP** [comment] 2019-12-03 05:53
Interesting, and when you do press enter and submit the message, does it come up automatically as a mention? (Underlined in bold and trigger the email?)

**Comment by ankar84** [comment] 2019-12-03 07:53
Yes. But we don't use email notofocation on mention.
![image](https://user-images.githubusercontent.com/4023037/70030839-15fa1500-15bb-11ea-9135-8c9dc44bbb8d.png)

**Comment by jeanfbrito** [comment] 2022-01-12 01:39
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:39 UTC
