### ISSUE TITLE
New version available (windows) never installs

### ISSUE THREAD

**Issue by jesperordrup** [RocketChat/Rocket.Chat.Electron#2233] opened 2021-11-19 08:11 UTC
**Describe the bug**
Sometimes Rocket chat windows client tells that there is a new version available. I chose install every time and dialog informs me that downloading will start and then i will be notified. 

I've never seen it progress from there

What operating system and which version?
This time its windows 11 but it also happened on windows 10
Which version of Rocket.Chat.Electron (Electron/Desktop)?
All 3.5.x and probably before that. Latest is 3.5.7 to 3.6.0

**To Reproduce**
Restart computer and start rocket chat (it autostarts)

**Expected behavior**
After pressing install I expect that it installs immed or notifies me when downloaded. Neither happens

**Screenshots**

**Additional context**

**Comment by ankar84** [comment] 2021-11-19 09:05
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
Closing this in favor of original issue.
You can comment there.

**Closed by ankar84** 2021-11-19 09:05 UTC
