### ISSUE TITLE
tray icon default disabled on linux

### ISSUE THREAD

**Issue by xgdgsc** [RocketChat/Rocket.Chat.Electron#1729] opened 2020-09-22 03:27 UTC
## My Setup

- Operating System: Ubuntu 16.04
- App Version: master
- Installation type: deb

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
why is https://github.com/RocketChat/Rocket.Chat.Electron/blob/00435e1930d7f032c58334877f3af1b0b47f74fa/src/ui/reducers/isTrayIconEnabled.ts#L12 

tray icon default disabled on linux? 

### Current Behavior
default disabled 

### Expected Behavior
default enabled on linux.

I 'm really tired of having to turn on this for all my colleague.

**Comment by tiagoevanp** [comment] 2020-10-02 02:30
Hi @xgdgsc!

In some operating systems that use GNOME, like the latest Ubuntu releases is not default the usage of tray icons.
BTW, exists an extension for that.

https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray

**Comment by xgdgsc** [comment] 2020-10-03 12:05
Would default to enabled tray icons cause problems on those? If not, why not default to enabled tray icon?

**Comment by tiagoevanp** [comment] 2020-10-03 19:14
The problem is that in GNOME, if there is no extension that allows the display of tray icons, and this functionality is enabled by default, when closing the program it will remain active and in no place will it be possible to notice this. Don't you agree?

**Comment by xgdgsc** [comment] 2020-10-04 03:03
Can you use https://www.npmjs.com/package/is-xfce to check and set default?

**Comment by paolostivanin** [comment] 2020-10-05 06:32
Since the update to v3.0.0 tray icon disappeared on GNOME 3.36 (opensuse tumbleweed). All other tray icons are working fine, just RC is gone.

**Comment by kklimczak** [comment] 2020-10-23 06:56
@paolostivanin just go to the `View` menu and check the `Tray icon` option.

**Comment by frac6969** [comment] 2020-12-10 03:17
I want the opposite behavior for Windows 10. With Tray Icon option checked, when users close the main window Rocket.Chat minimizes to the tray, then they never notice incoming messages. With Tray Icon option uncheck, when main window is closed it will minimize to task bar and not the tray. Incoming messages will blink the icon on the task bar.

It defaults to checked and I can't figure out how to uncheck the option for all users. There should be an easy configuration somewhere.

**Comment by jeanfbrito** [comment] 2022-01-12 02:09
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 02:09 UTC
