### ISSUE TITLE
Unable to get channel/private group/DM link

### ISSUE THREAD

**Issue by d-gubert** [RocketChat/Rocket.Chat.Electron#1202] opened 2019-04-29 23:51 UTC
Currently, as there is no "address bar" in the Electron app, it is not possible to copy the URL address for the current channel/private group/DM I am at.

Maybe a good way to solve it would be adding a button in Rocket.Chat's toolbar to copy the link for the room? A keyboard shortcut would be really neat also 🙂

**Comment by Maqsyo** [comment] 2019-04-30 05:33
I dont know if this is a real needed feature..
i mean.. if you have the electron-client, do you really need the browser? And do you so need the URL?
Doesn't it fill your needs, that you could search a channel/user ?

**Comment by d-gubert** [comment] 2019-04-30 14:28
Not having the address makes it impossible for me to share the link to any channel with anyone, or even to save the link to anything in a doc elsewhere.

It is a really useful feature

**Comment by pH142857** [comment] 2021-12-03 09:42
Very surprised that this feature doesn't exist yet. It should be in the channel info. How am I to share a room link when I'm not in a browser?

**Comment by jeanfbrito** [comment] 2022-08-04 21:11
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-08-04 21:11 UTC
Labels: type: enhancement

**Comment by pH142857** [comment] 2022-08-11 13:36
> Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

Hello, two questions:
1) do you refer to latest desktop client (Electron) release, or latest server version? If the former, I'm on Ubuntu and the snapcraft website states the latest is 3.8.6, but I see a branche 20 here on github, so I'm a bit confused.
2) where am I supposed to look for the channel link to check if the issue is solved?
Thanks.
