### ISSUE TITLE
app update

### ISSUE THREAD

**Issue by Gorelskiy** [RocketChat/Rocket.Chat.Electron#1916] opened 2020-12-14 07:01 UTC
Good afternoon! When you try to update the app, the app doesn't update and displays a message on Snapshot 2

![Снимок](https://user-images.githubusercontent.com/75970088/102050126-44781600-3df3-11eb-8213-6ac355aba783.PNG)
![Снимок2](https://user-images.githubusercontent.com/75970088/102050137-493cca00-3df3-11eb-9922-27225e231600.PNG)

## My Setup

- Operating System:
- App Version:
- Installation type: 

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by ankar84** [comment] 2020-12-14 08:47
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871 and https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670 and many others

**Comment by teak421** [comment] 2020-12-18 17:31
Any idea when this issue will be resolved as it been reported by a ton of folks?  Is there some sort of published road map of fixes that are being worked on?

**Comment by ankar84** [comment] 2021-09-08 07:44
Closing in favor of #1670

**Closed by ankar84** 2021-09-08 07:44 UTC
