### ISSUE TITLE
[3.0.2] "Rocket.Chat is set to stay running in the system tray/notification area"

### ISSUE THREAD

**Issue by Commifreak** [RocketChat/Rocket.Chat.Electron#1808] opened 2020-10-13 04:27 UTC
## My Setup

- Operating System: Won10 x64
- App Version: 3.0.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Everytime I close the chat window, a tray notification pops up "Rocket.Chat is set to stay running in the system tray/notification area"

### Expected Behavior
Should come max. 1x per run or should be an option in settings..

**Comment by vandreytrindade** [comment] 2020-10-13 14:30
I came here for the same reason. Is really annoying that notification.

**Comment by vega1970** [comment] 2020-10-14 09:28
I'm also very annoyed to get this notification each time.

Even if you minimize to tray without clicking the close button (by clicking the tray icon for instance), you get the notification.

I was so fed up that I disabled Rocket.Chat notifications through Windows setup. Anyway, you still get the red point on the tray icon when a new message is posted.

**Comment by alc123ng** [comment] 2020-10-14 10:59
Duplicate of #1749

**Closed** 2020-10-19 14:10 UTC
Labels: stat: duplicate
