### ISSUE TITLE
Active Rocket.Chat aplication when receive new message

### ISSUE THREAD

**Issue by helderam** [RocketChat/Rocket.Chat.Electron#772] opened 2018-07-12 23:56 UTC
## My Setup
- Operating System: Microsoft WIndows 10
- App Version: 2.7.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

First is very good the program congratulations to the authors and to all who keep this open source project. We are using the company with about 20 employees and everyone praises.

But when a message comes and the program is only running in background (user clicked the close red button), it happens that it does not see the rapid notification and ends up not responding the message.

Would you like to deploy a feature that activates in ROCKET.CHAT IN FOREGROUND immediately as soon as it receives a new message, placing over the other windows including?

I would be very grateful.

### Current Behavior

The message comes and go and the user not see.

### Expected Behavior

When the message comes the rocket.chat appear in foregroud over the others windows.

**Comment by Anguel** [comment] 2018-08-01 09:16
It is ridiculous that every few days a user reports this problem and nobody cares. Just look at the other issues...

**Comment by tassoevan** [comment] 2018-08-01 20:28
@Anguel While the team is aware of the issue with notifications, some changes in the latest version of Rocket.Chat server are degrading user experience for desktop users too. We ask to the users to be patient and/or to do code contributions.

**Comment by Anguel** [comment] 2018-08-02 15:52
@tassoevan Thank you for the feedback and the confirmation that you are aware of the problem.

**Comment by tassoevan** [comment] 2018-09-19 21:47
Duplicate of #213.

**Closed by tassoevan** 2018-09-19 21:47 UTC
