### ISSUE TITLE
any manual pls !

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat.Electron#279] opened 2017-01-07 00:32 UTC
iwant start to intergate my server to Rocket.Chat.Electron with standalone server
i mean my owne server
i have http://rc.example.com
and iwant make desktop client for my server with auto load without server showng server list or add server for my members

My server Centos 6x
RC Manual setup
Dir >opt/RC

I need step 1.2.3 to start bcs idont understand any thing from her https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/README.md

**Comment by engelgabriel** [comment] 2017-01-11 03:03
this is duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/267

**Closed by engelgabriel** 2017-01-11 03:03 UTC
