### ISSUE TITLE
Unable to update Desktop client from 3.0.3 to 3.0.4

### ISSUE THREAD

**Issue by Vkat14** [RocketChat/Rocket.Chat.Electron#1837] opened 2020-10-21 02:18 UTC
This was an OLD problem in version 2 of the App where you could not update the Client using the Built in update feature. You had to manually download the executable file for the NEW version from Git. I was hoping version 3 fixed this problem.

## My Setup

- Operating System: Windows 10
- App Version: 3.0.3
- Installation type: .exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
- Go to **Help** > **About Rocket.chat**
- Window appears with the Version Number and Check for Updates.
- Clicking **Check for Updates** does nothing.

### Current Behavior
See link: https://i.gyazo.com/657528bfd3146242e30ebc1460b59663.mp4

### Expected Behavior
Offer the install for version 3.0.4

**Comment by apaarfus** [comment] 2020-10-21 17:49
As for as I understand, when clicking "install update", the installer _is_ downloaded to `%localappdata%\rocketchat-updater`; but as soon as the download finishes, the file is removed.  To my limited knowledge, this behavior has been pretty constant since the issue initially arose.

In any event, this appears to be a duplicate of #1670 & #1205.

**Comment by Vkat14** [comment] 2020-10-21 18:18
I remember 1670. I see that post has been updated with version 3 fails.

**Comment by Vkat14** [comment] 2020-10-21 18:24
[![Image from Gyazo](https://i.gyazo.com/6ba4dd68055f1497081f3df893674c52.gif)](https://gyazo.com/6ba4dd68055f1497081f3df893674c52)

Same issue with Startup check. Here you get a confirmation but that doesn't mean anything. Same as like it was reported in #1670

**Comment by AlbyGNinja** [comment] 2020-11-25 09:08
@Vkat14 workaround solution here: [https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871#issuecomment-733569302)

**Comment by ankar84** [comment] 2021-09-08 07:45
Closing in favor of #1670

**Closed by ankar84** 2021-09-08 07:45 UTC
