### ISSUE TITLE
Logging out on every restart

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#414] opened 2017-04-07 02:51 UTC
Windows 7 32bit and 64bit exiting the app or restarting the computer logged out of server.  

Server list remains, but login state is not kept.

**Comment by tqkruger** [comment] 2017-04-09 13:12
The same on MacOS

**Comment by alexbrazier** [comment] 2017-08-18 19:44
@tqkruger Is this still an issue on the latest version?

**Comment by mairastorch** [comment] 2017-08-18 22:43
Unfortunately it is :(

**Comment by alexbrazier** [comment] 2017-08-18 23:03
@mairastorch Do you sign in with a username and password, or with facebook/google etc.?
If you login, the restart the app, does it always start logged out?

**Comment by mairastorch** [comment] 2017-08-19 03:22
I sign in with an username and password, but I believe my company uses LDAP
for authentication.

If I login, switch to another app, receive a notification and tap it,
rocketchat opens showing the login screen.

**Comment by devastator126** [comment] 2019-11-30 23:58
Having the same issue here on windows 10 1803 - windows 10 1909. We use local usernames and passwords.

**Comment by athlonUA** [comment] 2020-02-14 19:47
Hello! The issue is still exists. When I restart my computer the Rocket.chat logged out me from the server.

**Comment by athlonUA** [comment] 2020-02-17 08:01
It's not safe but I use `Object.keys(sessionStorage).forEach(k=>localStorage.setItem(k,sessionStorage.getItem(k)))` script to be able to login next time after reboot my laptop

**Comment by jeanfbrito** [comment] 2022-01-10 17:09
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-10 17:09 UTC
Labels: type: bug, plat: windows, stat: needs testing
