### ISSUE TITLE
Rocket.Chat App on macOs crashing just after just after installation 

### ISSUE THREAD

**Issue by carpecodeum** [RocketChat/Rocket.Chat.Electron#1431] opened 2019-12-06 07:46 UTC
## My Setup
- Operating System: macOs v-10.14.6 
- App Version: 3.00
- Installation type: dmg

- [x] I have tested with the latest version

## Description
steps to reproduce-
1.install the app from the website.
2.copy the the installed dmg file to the applications folder

### Current Behavior
the app quits unexpectedly 
<img width="620" alt="Screenshot 2019-12-06 at 1 03 20 PM" src="https://user-images.githubusercontent.com/43586052/70305458-70e57380-182a-11ea-9dcf-426e23dc8f64.png">

### Expected Behavior
the app should open.

**Comment by thilo20** [comment] 2019-12-06 09:17
same behavior for:
-     Operating System: macOs v-10.15.1
-     App Version: 2.17.0
-     Installation type: dmg

**Comment by TarasHots** [comment] 2019-12-06 10:32
same behavior for:

- OS: MacOS Catalina 10.15.1
- App Version: 2.17.0
- Installation type: dmg

`System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000080582e02040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x80582e02040:
    Memory Tag 255         0000080582e01000-0000080582e02000 [    4K] ---/rwx SM=NUL  
--> Memory Tag 255         0000080582e02000-0000080582e3f000 [  244K] r-x/rwx SM=COW  
    Memory Tag 255         0000080582e3f000-000008058adbc000 [127.5M] ---/rwx SM=NUL  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x0000080582e02040 0 + 8819763585088
1   com.github.Electron.framework 	0x0000000108c8ebc6 0x107b89000 + 17849286
2   com.github.Electron.framework 	0x0000000108c99ce3 0x107b89000 + 17894627
3   com.github.Electron.framework 	0x0000000108c9866a 0x107b89000 + 17888874
4   com.github.Electron.framework 	0x0000000108ce29a2 0x107b89000 + 18192802
5   com.github.Electron.framework 	0x0000000109301279 0x107b89000 + 24609401
6   com.github.Electron.framework 	0x000000010933f0e1 0x107b89000 + 24862945
7   com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
8   com.github.Electron.framework 	0x0000000109280ab9 0x107b89000 + 24083129
9   com.github.Electron.framework 	0x00000001093101c6 0x107b89000 + 24670662
10  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
11  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
12  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
13  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
14  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
15  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
16  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
17  com.github.Electron.framework 	0x00000001092873a1 0x107b89000 + 24109985
18  com.github.Electron.framework 	0x000000010928497a 0x107b89000 + 24099194
19  com.github.Electron.framework 	0x0000000109284758 0x107b89000 + 24098648
20  com.github.Electron.framework 	0x00000001089fdae5 0x107b89000 + 15157989
21  com.github.Electron.framework 	0x00000001089fd64e v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 206
22  com.github.Electron.framework 	0x0000000108804c33 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 435
23  com.github.Electron.framework 	0x000000010d47248e 0x107b89000 + 93230222
24  com.github.Electron.framework 	0x000000010d472a66 0x107b89000 + 93231718
25  com.github.Electron.framework 	0x000000010d472bd8 0x107b89000 + 93232088
26  com.github.Electron.framework 	0x000000010d41d315 node::BootstrapEnvironment(node::Environment*) + 21
27  com.github.Electron.framework 	0x0000000107c3761b 0x107b89000 + 714267
28  com.github.Electron.framework 	0x00000001096d29ca 0x107b89000 + 28613066
29  com.github.Electron.framework 	0x00000001096d637b 0x107b89000 + 28627835
30  com.github.Electron.framework 	0x00000001096d21d6 0x107b89000 + 28611030
31  com.github.Electron.framework 	0x00000001095906f2 0x107b89000 + 27293426
32  com.github.Electron.framework 	0x000000010959030e 0x107b89000 + 27292430
33  com.github.Electron.framework 	0x000000010b6a44f9 0x107b89000 + 61977849
34  com.github.Electron.framework 	0x0000000108739a04 0x107b89000 + 12257796
35  com.github.Electron.framework 	0x0000000107b8bb94 AtomMain + 84
36  chat.rocket                   	0x0000000107b519e0 0x107b51000 + 2528
37  libdyld.dylib                 	0x00007fff64fe52e5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff651ee56c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff651ee56c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff651ee56c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff651ee56c start_wqthread + 0

Thread 5:: ThreadPoolServiceThread
0   libsystem_kernel.dylib        	0x00007fff651362da kevent64 + 10
1   com.github.Electron.framework 	0x0000000109f4e67a 0x107b89000 + 37508730
2   com.github.Electron.framework 	0x0000000109f4e4e6 0x107b89000 + 37508326
3   com.github.Electron.framework 	0x0000000109efaa88 0x107b89000 + 37165704
4   com.github.Electron.framework 	0x0000000109eceb07 0x107b89000 + 36985607
5   com.github.Electron.framework 	0x0000000109efdb87 0x107b89000 + 37178247
6   com.github.Electron.framework 	0x0000000109f0a036 0x107b89000 + 37228598
7   com.github.Electron.framework 	0x0000000109f503f7 0x107b89000 + 37516279
8   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
9   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 6:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	0x00007fff6512e166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6512e6cc mach_msg + 60
2   com.github.Electron.framework 	0x0000000109ee7135 0x107b89000 + 37085493
3   com.github.Electron.framework 	0x0000000109f059cd 0x107b89000 + 37210573
4   com.github.Electron.framework 	0x0000000109f05d7c 0x107b89000 + 37211516
5   com.github.Electron.framework 	0x0000000109f05c94 0x107b89000 + 37211284
6   com.github.Electron.framework 	0x0000000109f503f7 0x107b89000 + 37516279
7   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
8   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 7:: ThreadPoolBackgroundWorker
0   libsystem_kernel.dylib        	0x00007fff6512e166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6512e6cc mach_msg + 60
2   com.github.Electron.framework 	0x0000000109ee7135 0x107b89000 + 37085493
3   com.github.Electron.framework 	0x0000000109f059cd 0x107b89000 + 37210573
4   com.github.Electron.framework 	0x0000000109f05d7c 0x107b89000 + 37211516
5   com.github.Electron.framework 	0x0000000109f05c04 0x107b89000 + 37211140
6   com.github.Electron.framework 	0x0000000109f503f7 0x107b89000 + 37516279
7   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
8   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 8:: Chrome_IOThread
0   libsystem_kernel.dylib        	0x00007fff651362da kevent64 + 10
1   com.github.Electron.framework 	0x0000000109f4e67a 0x107b89000 + 37508730
2   com.github.Electron.framework 	0x0000000109f4e4e6 0x107b89000 + 37508326
3   com.github.Electron.framework 	0x0000000109efaa88 0x107b89000 + 37165704
4   com.github.Electron.framework 	0x0000000109eceb07 0x107b89000 + 36985607
5   com.github.Electron.framework 	0x00000001096dbf94 0x107b89000 + 28651412
6   com.github.Electron.framework 	0x0000000109f0a036 0x107b89000 + 37228598
7   com.github.Electron.framework 	0x0000000109f503f7 0x107b89000 + 37516279
8   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
9   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff6513498a kevent + 10
1   com.github.Electron.framework 	0x000000010d593fea 0x107b89000 + 94416874
2   com.github.Electron.framework 	0x000000010d583991 uv_run + 497
3   com.github.Electron.framework 	0x000000010d4ff8f6 0x107b89000 + 93808886
4   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
5   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff65131916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff651f2040 _pthread_cond_wait + 701
2   com.github.Electron.framework 	0x000000010d58f369 uv_cond_wait + 9
3   com.github.Electron.framework 	0x000000010d4ffa08 0x107b89000 + 93809160
4   com.github.Electron.framework 	0x000000010d4fd67b 0x107b89000 + 93800059
5   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff65131916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff651f2040 _pthread_cond_wait + 701
2   com.github.Electron.framework 	0x000000010d58f369 uv_cond_wait + 9
3   com.github.Electron.framework 	0x000000010d4ffa08 0x107b89000 + 93809160
4   com.github.Electron.framework 	0x000000010d4fd67b 0x107b89000 + 93800059
5   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff65131916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff651f2040 _pthread_cond_wait + 701
2   com.github.Electron.framework 	0x000000010d58f369 uv_cond_wait + 9
3   com.github.Electron.framework 	0x000000010d4ffa08 0x107b89000 + 93809160
4   com.github.Electron.framework 	0x000000010d4fd650 0x107b89000 + 93800016
5   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 13:
0   libsystem_kernel.dylib        	0x00007fff6512e1a2 semaphore_wait_trap + 10
1   com.github.Electron.framework 	0x000000010d58f8d0 uv_sem_wait + 16
2   com.github.Electron.framework 	0x000000010d54a752 0x107b89000 + 94115666
3   libsystem_pthread.dylib       	0x00007fff651f1d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff651ee58f thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000080582e02001  rbx: 0x0000080582e02040  rcx: 0x00002a701bb840de  rdx: 0x00002a701bb840d8
  rdi: 0x00002a701bb840c9  rsi: 0x0000000000000000  rbp: 0x00007ffee80ad650  rsp: 0x00007ffee80ad5d8
   r8: 0x00000001106ad324   r9: 0x0000000000000004  r10: 0x00007fdec4800000  r11: 0x00000000548dbe7c
  r12: 0x00002a701bb840c9  r13: 0x00006000022c0750  r14: 0x00007fdec4825400  r15: 0x00000001106a3000
  rip: 0x0000080582e02040  rfl: 0x0000000000010212  cr2: 0x0000080582e02040
  
Logical CPU:     6
Error Code:      0x00000015 (invalid protections for user instruction write)
Trap Number:     14`

**Comment by nephix** [comment] 2019-12-06 10:48
Duplicate of #1422

**Comment by jeanfbrito** [comment] 2022-01-11 12:38
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-11 12:38 UTC
