### ISSUE TITLE
Message: "user123 and you reacted with :thumbsup_tone2:" no disappear. 

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Electron#896] opened 2018-09-26 08:09 UTC
## My Setup
- Operating System: ubuntu 18
- App Version: 2.13.0-907
- Installation type: deb

- [no] I have tested with the latest version
- [no] I can simulate the issue easily

## Description
I've got a notification in top left corner: "user123 and you reacted with :thumbsup_tone2:".

### Current Behavior
Message is persistent and I can't dismiss it. App restart is required.

### Expected Behavior
Message disappear after some time or on click.

### Related log

I don't really know this logs are related to this problem but my console contains:

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
dbf476557969259fcab32811a59bbfb0704d8196.js:209 Uncaught TypeError: Cannot read property 'match' of null
    at i (dbf476557969259fcab32811a59bbfb0704d8196.js:209)
    at u (dbf476557969259fcab32811a59bbfb0704d8196.js:209)
    at dbf476557969259fcab32811a59bbfb0704d8196.js:209
dbf476557969259fcab32811a59bbfb0704d8196.js:209 Uncaught TypeError: Cannot read property 'match' of null
    at i (dbf476557969259fcab32811a59bbfb0704d8196.js:209)
    at u (dbf476557969259fcab32811a59bbfb0704d8196.js:209)
    at dbf476557969259fcab32811a59bbfb0704d8196.js:209
```

**Comment by tassoevan** [comment] 2018-09-26 15:18
Is it easily reproducible? Also, which server version is running?

**Comment by piotrkochan** [comment] 2018-09-27 09:32
I can't reproduce it because I do not receive anymore these notifications - my friend tried to react to my direct message and my message on private group when I was browsing even different group. 

So I think this is not just a bug with persistent reaction notification but with whole mechanism of these.

**Comment by tassoevan** [comment] 2018-10-11 18:14
I'm closing since it appears to be a bug in the web client of Rocket.Chat server.

**Closed by tassoevan** 2018-10-11 18:14 UTC

**Comment by piotrkochan** [comment] 2018-10-11 18:16
I only once got reaction notification, not even once more anymore so I think someone else should confirm this.
