### ISSUE TITLE
Rocket never auto-update

### ISSUE THREAD

**Issue by MC-PM** [RocketChat/Rocket.Chat.Electron#1786] opened 2020-10-05 13:40 UTC
The auto-update option is checked, and every time when I start rocket the new update notification appear, but it never run or works, even when it´s requested manually.

**Comment by ankar84** [comment] 2020-10-05 14:06
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670#issuecomment-703348457

**Comment by KeithStreeter** [comment] 2020-10-06 12:32
Same for me. Just tells me 3.0.0 is available, then 3.0.1 now this morning 3.0.2. Give me the option to skip or install. When I select install it does not. I get this error message every morning and I'm on version 2.17.11

**Comment by ankar84** [comment] 2021-09-08 07:47
Closing in favor of #1670

**Closed by ankar84** 2021-09-08 07:47 UTC
