### ISSUE TITLE
Install Update does not respond at all

### ISSUE THREAD

**Issue by Anigif** [RocketChat/Rocket.Chat.Electron#1197] opened 2019-04-24 07:23 UTC
## My Setup
- Operating System: Windows 10 Pro
- App Version: 2.15.0
- Installation type: rocketchat-setup-2.14.5.exe

- [ ] I have tested with the latest version _(does not makes sense to do)_
- [x] I can simulate the issue easily

## Description
This has happened both when trying to update to 2.15.1 (which I in the end ignored) and 2.15.2

If "Check for Updates on Start" is checked:
1. Open Rocket from cold start
2. Try clicking "Install Update" or "Remind Later"

And/or:
1. Go to "Help" / "About Rocket.Chat"
2. Click "Check for Updates"
3. Try clicking "Install Update" or "Remind Later"

### Current Behavior
Nothing happens. No updates seems to start and no new visual changes at all.

Note that when update for 2.15.1 came I in the end clicked "Remind me later" which responded and worked.

### Expected Behavior
The update starts.

**Comment by tassoevan** [comment] 2019-04-24 18:45
Duplicate of #1141. The workaround is to manually download and install the newest version.

**Closed by tassoevan** 2019-04-24 18:45 UTC

**Comment by franckadil** [comment] 2019-04-29 03:06
@tassoevan Hi! Do you know if the automatic update have been fixed with 2.15.2 ? If so please can you point me with the files I need to update or the commits ? I have done some customization and don't want just to replace the files without tracking the changes. Thanks in advance for your guidance.

**Comment by tassoevan** [comment] 2019-04-29 11:33
@franckadil Here is the patch: https://github.com/RocketChat/Rocket.Chat.Electron/pull/1123/files

**Comment by franckadil** [comment] 2019-04-29 16:21
@tassoevan Thank You ! I'll test this asap!

**Comment by franckadil** [comment] 2019-04-29 16:41
@tassoevan I am a bit confused, the files contained in the official repo differ from those in the pull/repo
Original:
![image](https://user-images.githubusercontent.com/42721509/56911844-da87ed00-6aa5-11e9-92d0-f42790398cdf.png)

Modified:
![image](https://user-images.githubusercontent.com/42721509/56911900-fc816f80-6aa5-11e9-93ba-2805e5d7b96c.png)

What the difference ? ad how can I merge this with my base code ?

**Comment by franckadil** [comment] 2019-04-29 16:52
@tassoevan  I already have this fix in my codebase, but when testing, The update still don't work, I ca see a dialog box saying that I will be notified when the update is ready to be installed, then nothing ever happen.

Does it have something to do with cleaning user files completely from the system ?

**Comment by tassoevan** [comment] 2019-04-29 16:59
@franckadil If you deployed some version with a broken update code, there is nothing you can do. The update works *on the old version trying to get the new one*.

**Comment by franckadil** [comment] 2019-04-29 17:17
@tassoevan  I understand, but here is what I tried: 

- I used the new version and changed version number to example 1.0.1
- Made some cosmetic changes and released 1.0.2

And as described before the update notification on 1.0.1 is triggered, I can click on the update button, the dialog vox that confirms I will be notified after update is ready works. But nothing else happens from this point on. Is that a normal behaviour until we get an official code bump to 2.15.3 ? Or is it supposed to work even for internal tests and releases ?

**Comment by tassoevan** [comment] 2019-04-29 17:19
It must work. Any error is logged on stdout or even DevTools console?

**Comment by franckadil** [comment] 2019-04-29 17:20
@tassoevan I couldn't check the errors I will test properly and share any log here.

**Comment by franckadil** [comment] 2019-04-29 17:37
@tassoevan  Here we go:

![image](https://user-images.githubusercontent.com/42721509/56915184-c7791b00-6aad-11e9-9d14-bab4d52f9f2d.png)


```
Checking for update
Found version 16.0.1 (url: rocket-setup-16.0.1.exe)
Downloading update from rocket-setup-16.0.1.exe
updaterCacheDirName is not specified in app-update.yml Was app build using at le
ast electron-builder 20.34.0?
updater cache dir: C:\Users\franc\AppData\Local\JungleWP rocket
No cached update info available
Download block maps (old: "https://api.github.com/repos/junglewp/rocket.App.Elec
tron/releases/assets/12285524.blockmap", new: https://api.github.com/repos/jungl
ewp/rocket.App.Electron/releases/assets/12285524.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowe
d size is 5 MB
    at Object.responseHandler (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\D
evelopment\rocket.Dev.Electron\node_modules\electron-updater\node_modules\builde
r-util-runtime\src\httpExecutor.ts:207:26)
    at ClientRequest.request.createRequest.response (C:\Users\franc\OneDrive\Doc
uments\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron-updat
er\node_modules\builder-util-runtime\src\httpExecutor.ts:267:17)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\franc\OneDrive\Documents
\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron\dist\resour
ces\electron.asar\browser\api\net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at ElectronHttpExecutor.downloadToBuffer (C:\Users\franc\OneDrive\Documents\
JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\node
_modules\builder-util-runtime\src\httpExecutor.ts:178:60)
    at C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\rocket.Dev.El
ectron\node_modules\electron-updater\src\NsisUpdater.ts:145:46
    at Generator.next (<anonymous>)
From previous event:
    at downloadBlockMap (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Develop
ment\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:144:29
)
    at C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\rocket.Dev.El
ectron\node_modules\electron-updater\src\NsisUpdater.ts:166:51
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadInstaller (C:\Users\franc\OneDrive\Docume
nts\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\
src\NsisUpdater.ts:134:173)
    at Object.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Devel
opment\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:34:4
2)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\
rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\rocket.Dev.El
ectron\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\A
pps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater
.ts:545:68)
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\A
pps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\BaseUpdate
r.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\
Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdat
er.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Ap
ps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater.
ts:420:19)
    at downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Developme
nt\rocket.Dev.Electron\app\src\main\updates.js:69:21)
    at EventEmitter.electron.ipcMain.on (C:\Users\franc\OneDrive\Documents\Jungl
eWP\Apps\Development\rocket.Dev.Electron\app\src\main\updates.js:186:37)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\
Development\rocket.Dev.Electron\node_modules\electron\dist\resources\electron.as
ar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
Error: Error: Cannot download "https://api.github.com/repos/junglewp/rocket.App.
Electron/releases/assets/12285524", status 404: Not Found
    at ClientRequest.request.createRequest.response (C:\Users\franc\OneDrive\Doc
uments\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron-updat
er\node_modules\builder-util-runtime\src\httpExecutor.ts:247:26)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\franc\OneDrive\Documents
\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron\dist\resour
ces\electron.asar\browser\api\net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at ElectronHttpExecutor.download (C:\Users\franc\OneDrive\Documents\JungleWP
\Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\electron
HttpExecutor.ts:23:73)
    at Object.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Devel
opment\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:35:3
5)
From previous event:
    at Object.task (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\
rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\rocket.Dev.El
ectron\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\A
pps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater
.ts:545:68)
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\A
pps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\BaseUpdate
r.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\
Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdat
er.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Ap
ps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater.
ts:420:19)
    at downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Developme
nt\rocket.Dev.Electron\app\src\main\updates.js:69:21)
    at EventEmitter.electron.ipcMain.on (C:\Users\franc\OneDrive\Documents\Jungl
eWP\Apps\Development\rocket.Dev.Electron\app\src\main\updates.js:186:37)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\
Development\rocket.Dev.Electron\node_modules\electron\dist\resources\electron.as
ar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
Error: Error: Cannot download "https://api.github.com/repos/junglewp/rocket.App.
Electron/releases/assets/12285524", status 404: Not Found
    at ClientRequest.request.createRequest.response (C:\Users\franc\OneDrive\Doc
uments\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron-updat
er\node_modules\builder-util-runtime\src\httpExecutor.ts:247:26)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\franc\OneDrive\Documents
\JungleWP\Apps\Development\rocket.Dev.Electron\node_modules\electron\dist\resour
ces\electron.asar\browser\api\net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at ElectronHttpExecutor.download (C:\Users\franc\OneDrive\Documents\JungleWP
\Apps\Development\rocket.Dev.Electron\node_modules\electron-updater\src\electron
HttpExecutor.ts:23:73)
    at Object.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Devel
opment\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:35:3
5)
From previous event:
    at Object.task (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\
rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\rocket.Dev.El
ectron\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\De
velopment\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\De
velopment\rocket.Dev.Electron\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\D
evelopment\rocket.Dev.Electron\node_modules\electron-updater\src\NsisUpdater.ts:27:17)

    at NsisUpdater.downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Dev
elopment\rocket.Dev.Electron\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at downloadUpdate (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Development\Tri
bes.Dev.Electron\app\src\main\updates.js:69:21)
    at EventEmitter.electron.ipcMain.on (C:\Users\franc\OneDrive\Documents\JungleWP\Ap
ps\Development\rocket.Dev.Electron\app\src\main\updates.js:186:37)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\franc\OneDrive\Documents\JungleWP\Apps\Develo
pment\rocket.Dev.Electron\node_modules\electron\dist\resources\electron.asar\browser\a
pi\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

**Comment by franckadil** [comment] 2019-04-29 17:45
It seems that a downgrade solves the problem:

Info my electron-builder.yml :

```
publish:
- provider: github
  owner: owner
  repo: repo
  private: true
  token: token
```

Sources: 

- https://github.com/electron-userland/electron-builder/issues/3851

- https://github.com/electron-userland/electron-builder/issues/3564


Downgrade solve this problem
"electron": "4.0.6",
"electron-builder": "20.34.0",
"electron-updater": "3.2.3"

**Comment by franckadil** [comment] 2019-04-29 17:55
@tassoevan I can confirm the downgrade of package.yml works!

![image](https://user-images.githubusercontent.com/42721509/56916223-51c27e80-6ab0-11e9-826d-b6a796748d40.png)
