### ISSUE TITLE
All the ZIP Donwloads of the RocketChat Client are invlaid ZIP files!

### ISSUE THREAD

**Issue by pimisen** [RocketChat/Rocket.Chat.Electron#2211] opened 2021-10-20 06:21 UTC
## My Setup

- Operating System: Windows 10 with winzip 21
- App Version: not relevant, issue with ZIP package itself
- Installation type: ZIP (portable?)

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
Go to https://github.com/RocketChat/Rocket.Chat.Electron/releases/
Try to download and open any ZIP Version. BTW: Why are 3.5.7 and 3.5.6 twice as big (~145 MB) as the releases before (~78MB)?

### Current Behavior
![grafik](https://user-images.githubusercontent.com/60874062/138038821-a5803e65-bd55-495c-9af6-f63636ce275f.png)

### Expected Behavior
ZIP can be downloaded and extracted

**Comment by jeanfbrito** [comment] 2021-12-04 20:48
The problem didnt reproduce in any other program? Seems like a Winzip Issue like @ankar84 said.
I will be closing the issue that seems to be external from Rocket.Chat.Electron.

**Comment by pimisen** [comment] 2021-12-06 17:56
A Winzip Issue. On my Android. Your ZIP File is coruppted. Accept it.

**Comment by jeanfbrito** [comment] 2021-12-06 18:06
Absolutely not a Winzip problem. Only in MacOS I can open the ZIP. Windows and Android are giving error. I think that the building process has mixed the files.

**Comment by jeanfbrito** [comment] 2021-12-14 20:45
I mentioned it in a PR but is not solved yet. Sorry, my mistake. We are working on this solution yet.

**Comment by jeanfbrito** [comment] 2022-04-18 15:42
Hello @pimisen I found the problem. You was using the zip file that was only for MacOS installations.
Now we have the OS on the file names and you will find the right ZIP for windows.

**Closed by jeanfbrito** 2022-04-18 15:42 UTC
Labels: plat: windows, subj: release building
