### ISSUE TITLE
Search function not working Linux/3.5.3

### ISSUE THREAD

**Issue by jalbstmeijer** [RocketChat/Rocket.Chat.Electron#2163] opened 2021-09-10 11:01 UTC
**Describe the bug**
When in a channel and trying to search a message. I get no matches.

What operating system and which version? Fedora 34
Which version of Rocket.Chat (Server)?  3.18
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.3
Is there any setting relevant changed? no

**To Reproduce**
1. Go to a channel
2. Go to options
3. Select "Search messages"
4. Search for something that is in a message

**Expected behavior**
a search match

**Additional context**
Came from 3.4.0, which had the same issue.

**Comment by ankar84** [comment] 2021-09-10 11:48
Web version works fine for that caser?

**Comment by jalbstmeijer** [comment] 2021-09-10 11:57
> Web version works fine for that caser?

Yes, both web gui and android app can search.

**Comment by jalbstmeijer** [comment] 2021-09-10 12:19
I see no errors  in the log of  the RocketChat server

The nginx proxy before it logs;

For the desktop app:

xx - - [10/Sep/2021:12:03:57 +0000] "POST /api/v1/method.call/rocketchatSearch.search HTTP/2.0" 200 98 "https://xx/channel/general/rocket-search" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Electron/13.2.2 Safari/537.36" xx"

response size seems to be always 97/98

via web gui:

xx - - [10/Sep/2021:12:04:10 +0000] "POST /api/v1/method.call/rocketchatSearch.search HTTP/2.0" 200 325 "https://xx/channel/general/rocket-search" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" "xx"

**Comment by ggazzo** [comment] 2021-09-10 13:07
@jalbstmeijer did you have this issue in versions previous < 3.3 ? this kinda odd, but since we updated electron on 3.4 MAYBE there is something happening

**Comment by ggazzo** [comment] 2021-09-10 13:13
could open your devtools (inside electron) and check if the payloads are "ok"?
![image](https://user-images.githubusercontent.com/5263975/132858162-7b789041-1aab-4967-843e-5ed86f122130.png)

**Comment by jalbstmeijer** [comment] 2021-09-10 13:18
> @jalbstmeijer did you have this issue in versions previous < 3.3 ? this kinda odd, but since we updated electron on 3.4 MAYBE there is something happening

I'm a new user. So 3.4.0 was my first version. Downgraded now to 3.2.4, that one works.

**Comment by jalbstmeijer** [comment] 2021-09-10 13:35
> could open your devtools (inside electron) and check if the payloads are "ok"?
> ![image](https://user-images.githubusercontent.com/5263975/132858162-7b789041-1aab-4967-843e-5ed86f122130.png)

I'm not very handy with devtools.
Seems to be a bit inconsistent the network capture. Sometimes it catches something other times even a hard reload does not show anything.
Not been able to check the post data yet.

**Comment by tmartincpp** [comment] 2021-09-10 14:33
Cannot be reproduced on my side :| (Debian 10)

**Comment by jalbstmeijer** [comment] 2021-09-10 18:52
I decided to checkout the flatpak version to rule out possible OS library issues.

With the flatpak version 3.5.3 search worked again.

Then I went back to the rpm based install and first moved ~/.config/Rocket.Chat away, as flatpak also started with a clean config.
Now search also works in the rpm version 3.5.3.

So not sure what resided in my ~/.config/Rocket.Chat that could cause this issue.
It was populated initially by version 3.4.0 on which search also did not work.
Strangely enough it did not affect version 3.2.4 which I downgraded to as test.

well hope some else is helped with this if that encounter the same.

**Comment by jalbstmeijer** [comment] 2021-09-10 19:31
That was short lived.

I can reproduce it now consistently both with the rpm and flatpak version of 3.5.3 on Fedora 34.

1. remove ~/.config/Rocket.Chat for the rpm  or ~/.var/app/chat.rocket.RocketChat for the flatpak version
2. start rocketchat (supply credentials again)
3. find search is working
4. exit  rocketchat
5. start rocketchat
6. find search stopped working
7. start again with 1

**Comment by jalbstmeijer** [comment] 2021-11-05 14:31
Hi, Still facing the same issue on Client 3.5.7 on Fedora 34 and Server 4.0.3.

Simplified the way I can reproduce it;

1. Start rocketchat for the first time and see search is working
2. Exit and start rocketchat or just reload with ctrl+R to see search stopped working 
3. Exit rocketchat and remove  ~/.config/Rocket.Chat/ config.json
4. Start rocketchat , fill in the preferred server,  search is working again
5. start again at 2.

Tried again to capture anything with devtoos. But it only seems to catch traffic on ctrl+R .

Gr, J

**Comment by jeanfbrito** [comment] 2022-08-04 22:00
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-08-04 22:00 UTC
Labels: plat: osx

**Comment by WebsliceNL** [comment] 2022-08-05 07:45
I have not seen the issue anymore.
