### ISSUE TITLE
2.15.0 Win10 issue - Taskbar-Counter and "Orange background" doesn't work anymore

### ISSUE THREAD

**Issue by johnyb0y** [RocketChat/Rocket.Chat.Electron#1104] opened 2019-02-25 11:01 UTC
## My Setup
- Operating System: Win10 1809
- App Version: 2.15.0 Release
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
In 2.14.7 while Rocketchat.Electron is minimized/maximized (not minimized to tray) the Taskbar Icon would show a counter for unread messages + the background color would change (Orange in Case of Windows 10).
Screenshot:
![screen](https://user-images.githubusercontent.com/12081528/53332946-cf251380-38f4-11e9-84a7-fa82a8dff876.jpg)

This doesn't happen anymore with 2.15.0.
 Only way to spot unread messages after the notification disappeared is by monitoring the tray icon.

### Current Behavior
No change in taskbar icon at all.

### Expected Behavior
Like 2.14.7: taskbar icon indicates amount of new messages and background changes color as well.

**Thanks!**

**Comment by tassoevan** [comment] 2019-02-25 14:19
Disabling the tray icon (`View > Tray Icon`) wouldn't be a better option for you? The taskbar icon will show the notification counter instead.

**Comment by johnyb0y** [comment] 2019-02-25 14:21
Any way to roll out this setting globally? It’s a rather huge change in default behavior.

**Comment by tassoevan** [comment] 2019-02-25 14:25
Unfortunately, there is no option for it available yet; deployed settings are a planned feature though.

**Comment by MIKI785** [comment] 2019-02-26 18:02
> Disabling the tray icon (`View > Tray Icon`) wouldn't be a better option for you? The taskbar icon will show the notification counter instead.

That doesn't work for me. Disabled the tray icon and it still doesn't show the counter (even after restarting it).

**Comment by johnyb0y** [comment] 2019-02-26 18:26
I didn't test it, so maybe it's not working for me, too. Happy to test if that would help.
@tassoevan I'd like to suggest a return to the previous behavior in a future update - at least for the Windows client.
For non-techy users the sudden change in how you monitor the client for new messages will be quite irritating.
Personally I'd choose the taskbar icon over the tray icon any day. 
Other frequently used Windows applications like Outlook handle it the same way.

**Comment by tassoevan** [comment] 2019-02-26 20:07
@johnyb0y We've no plans to revert this experimental behavior. The choice between taskbar and tray is utterly personal given the degree of intrusion for notifications, but it doesn't make sense for us to display the same information twice. If you enabled the tray icon, you should expect to see your notification counter only in the tray icon.

**Comment by johnyb0y** [comment] 2019-02-26 21:26
@tassoevan That makes sense. I understand. 
What about setting `View > Tray Icon` to Disabled by Default on Windows.
For three reasons: 

**1.** By default the tray icon is hidden, you have to manually drag it to your task bar for it to be permanently visible. Only 1 in 5 casual users knows how to do that.
**2.** I can't think of a single Windows app which doesn't change the taskbar icon in some way when it's minimized and new messages arrive (Slack, Outlook, Thunderbird, Skype, Jabber Clients, Telegram etc). It's the default behavior on Windows.
**3.** Other Rocketchat.Electron releases till now have handled this differently. 
In my opionen this change might cause major headaches for deployments with non-techie users who won't understand the new behavior and haven't even noticed the tray icon till now. It will break day-to-day workflows.

That's just my opinion though - Maybe someone will really like this change :)
Thanks.

**Comment by marcosmolinamaxicon** [comment] 2019-05-21 19:22
When you click the close button on the windows bar after that icon does not turn orange.

![image](https://user-images.githubusercontent.com/39923299/58124234-211fc180-7be4-11e9-9d6b-7d967792bf1d.png)

but, when click em close button of program 
![image](https://user-images.githubusercontent.com/39923299/58124291-47456180-7be4-11e9-8819-8104a5c717b3.png)

![image](https://user-images.githubusercontent.com/39923299/58124343-63490300-7be4-11e9-96d3-c2a931f4e9d2.png)

**Comment by brandonharshe** [comment] 2019-07-31 17:57
The default behavior of View > Tray icon is not good at all. Imagine rolling out Rocket.Chat to an organization of hundreds of people and having to tell everyone to disable the application from going to **hidden icons** (notice how it's called hidden). Unfortunately I don't have to imagine this because we're currently dealing with this. This isn't user-friendly. I can understand having this as a _non-default option_, but not to make it the default. It doesn't make sense because most applications don't behave this way. It's not intuitive at all.

Then we have the issue that stems from this. If you disable View > Tray icon:
1. If you minimize the application by clicking the app icon from the task bar, the app icon won't turn orange when you receive a notification.
2. If you minimize the application by clicking the X on the app, the app icon will turn orange when you receive a notification.

I can't even tell if the second issue is expected or not, but it's not friendly behavior at all. I strongly urge that you reconsider the default interactive behaviors.

**Comment by johnyb0y** [comment] 2019-07-31 18:01
We're still on 2.14.7 because of this. I hope that in the long run they will provide a way to deploy a default config for the client which allows us to set this in a certain way for all users.

**Comment by Xarkam** [comment] 2019-11-26 14:07
I do not know if this is part of the same problem, but we noticed that beyond 3mn the orange background disappears from the icon in the taskbar with windows 7. (desktop client 2.16.2)

As for the notification in the systray, I know (but I do not remember the name) a software that was returning the icon of the appplication in the taskbar when we receives a new message. (window return to minimized state)

Why not see if i'ts possible to reproduce this comportment ?

**Comment by mano87** [comment] 2020-07-08 13:04
In the current version, no badget is displayed in the Windows taskbar for unread messages. When will this happen?

**Comment by tassoevan** [comment] 2020-10-02 05:20
Maybe related to #1395.

**Comment by xgdgsc** [comment] 2020-11-03 13:25
Hope this would never be fixed. I don' t want any task bar icon change. I only want tray icon change. 😄

**Comment by jeanfbrito** [comment] 2022-01-11 23:55
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-11 23:55 UTC
Labels: type: bug, plat: windows, stat: need more info, feat: tray icon / dock / taskbar
