### ISSUE TITLE
Jitsi: call already ended

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.Electron#2343] opened 2022-03-18 08:17 UTC
**Describe the bug**
When opening a video call via call icon the "click to join" icon appears in the message window. That icon works just for 10s or so. After that one gets the message "call already ended". This is not happening when Rocketchat runs inside Firefox. The "click to join" icon stays functional in that case.

There is already a bug issue in the rocketchat repo but I guess it's not the right place so I open this ticket here for tracking this issue.
https://github.com/RocketChat/Rocket.Chat/pull/23904#issuecomment-1047728542

1. Go to chat window
2. Click on call icon
3. Wait 30s
4. Click on "click to join" icon
5. See "call already ended" message

**Expected behavior**
It should be possible to enter the still running jitsi room even after minutes.

cheers, t.

**Comment by himpierre** [comment] 2022-03-21 12:31
Interesting fact. The error only occurs when the jitsi conference was started by the desktop app. When i start a conference via mobile app or browser I can stil join the conference after minuts even from the desktop app.

**Comment by MCMicS** [comment] 2022-03-27 13:23
seem like issue https://github.com/RocketChat/Rocket.Chat/issues/11649

**Comment by himpierre** [comment] 2022-04-05 14:23
@jeanfbrito Sorry Jean for mentioning you but I'm to curious. Is that issue on some kind of todo list already? I'm asking because this worked a while and suddenly it didn't any more. It's a kind of a deal breaker when you cannot rely on the "click to join" button working. It prevents users from using it because they think it will not work half of the time anyway.

cheers, t.

**Comment by emikolajczak** [comment] 2022-06-03 06:41
Stil in latest `3.8.7`
I have noticed that calls started from Electron Client sent `jitsi-update-timeout` only once.
Web (browser) client repeat it during call.

Electron client:
![image](https://user-images.githubusercontent.com/50440047/171801111-12752960-665f-4f8c-ab27-73f63de74f14.png)


Browser client:
 
![image](https://user-images.githubusercontent.com/50440047/171801053-e5ef9060-3a8d-4085-a12e-790afeebd1c2.png)

**Comment by himpierre** [comment] 2022-06-03 07:38
Thanks for debugging this @emikolajczak 
Does that help @jeanfbrito?

cheers, t.

**Comment by jeanfbrito** [comment] 2022-10-05 20:14
Rocket.chat version 5.2 will be released soon and video calls will be handled in a proper way.
This kind of issue will not happen anymore.

**Closed by jeanfbrito** 2022-10-05 20:14 UTC

**Comment by Aghiles97** [comment] 2022-12-29 01:33
The issue is still happening, when i launch a video/phone call then I end it, it still shows 'ongoing' in the chat.

**Comment by 14droplets** [comment] 2024-10-29 18:20
In 2024 still?
