### ISSUE TITLE
Desktop updates never seem to install

### ISSUE THREAD

**Issue by binarydad** [RocketChat/Rocket.Chat.Electron#2151] opened 2021-09-08 15:16 UTC
Running any newer version of the Windows desktop client (3.X or more I suppose), whenever a prompt is shown for an update, and I choose "Install Update", it will notify me when it is ready to install, but it never happens. I've had to manually install each update from GH instead. 

Is this expected behavior? Can the client install the update when asked to install? Thanks.

**Comment by ankar84** [comment] 2021-09-09 00:58
Closing this issue as duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Closed by ankar84** 2021-09-09 00:58 UTC
Labels: stat: duplicate
