### ISSUE TITLE
In version 3, authorization on the server does not work

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.Electron#1750] opened 2020-10-01 07:08 UTC
Server version 3.6
Client 3.0

Returns an error no suitable server found at this address, but if you add a space at the end (https://rocket.chat/_) then the server finds.

**Comment by plmorpheus** [comment] 2020-10-01 07:09
I confirm, same in my case.

**Comment by DirkR** [comment] 2020-10-01 07:52
This issue seems to be a duplicate of some earlier filed ones. See  #1743

**Closed** 2020-10-02 04:10 UTC
Labels: stat: duplicate
