### ISSUE TITLE
Black screen and frozen frame

### ISSUE THREAD

**Issue by thiemol** [RocketChat/Rocket.Chat.Electron#150] opened 2016-03-22 08:44 UTC
In the Windows version of the client (Client version: 1.2.0 prerelease and 1.20;  Server version: 0.21 - 0.23) I get after some time a black screen in the inner frame of the client. The menu and the servermenu is still working. After selecting "Reload server" i can see the normal screen but it is impossible to interact with the frame - no clicking or typing works.
The web interface and the mobile app work without any issues at the same time.

"Application reload" solves the problem, till the black screen appears.
##

**Comment by stevenhfotofix** [comment] 2016-03-22 20:05
Same exact issue here - Client Version 1.2.0, Server 0.21 - Windows 10 Pro build 10586

**Comment by Vulg** [comment] 2016-03-24 20:07
Same here:
Windows 10 x64
client 1.2.0
server: latest dev

**Comment by Ruuudi** [comment] 2016-03-29 07:16
Exact the same issue here:
Windows 10 x64
client 1.2.0
server: latest dev

**Comment by msklywenn** [comment] 2016-03-30 15:58
Same here with windows 10 x64, client 1.2.0, serveur 0.24

**Comment by NioTeX** [comment] 2016-03-31 09:17
same for us :+1:

**Comment by twhiting** [comment] 2016-03-31 15:09
Same here w/ 1.2.0 on Win 10.  Black screen of death. 
![capture](https://cloud.githubusercontent.com/assets/10718586/14180452/3b4850f0-f720-11e5-8830-28d825e94acd.JPG)

**Comment by rodrigok** [comment] 2016-04-04 14:11
This is an electron bug, I will update the electron version before the next release to see if we can fix that.

**Comment by rodrigok** [comment] 2016-04-05 19:58
Depends on https://github.com/electron/electron/issues/3871 to update our electron version

**Comment by Megatronic79** [comment] 2016-04-18 16:23
similar to this:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/173

**Comment by Sing-Li** [comment] 2016-04-25 17:35
Very likely to be a problem of Chromium compositor GPU optimization.

Can we please report some information on the Video Card hardware and Video driver version on the system(s) that have this problem. Thanks.

**Comment by stevenhfotofix** [comment] 2016-04-25 17:40
Nvidia Quadro K620 - Driver version: 10.18.13.5382

**Comment by Megatronic79** [comment] 2016-04-25 17:49
Windows 10
Nvidia Quadro FX1800
9.18.13.4195

Windows 10
Nvidia Geforce GT 335M
9.18.13.4192

**Comment by msklywenn** [comment] 2016-04-25 17:52
Le 25/04/2016 à 19:49, Megatronic79 a écrit :
>
> Windows 10
> Nvidia Quadro FX1800
> 9.18.13.4195
>
> Windows 10
> Nvidia Geforce GT 335M
> 9.18.13.4192
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RocketChat/Rocket.Chat.Electron/issues/150#issuecomment-214458605>
>

Windows 10
Nvidia Geforce GTX 960
10.18.13.6175

**Comment by stevenhfotofix** [comment] 2016-04-25 18:06
I **CAN NOT** repeat the bug on an Intel HD 4000 video card - Laptop - 10.18.10.2476 (reporting to help narrow down the issue)

**Comment by Poil** [comment] 2016-04-25 18:37
Same bug on Windows 10 x86_64 and an Intel HD Graphics 4000

**Comment by msklywenn** [comment] 2016-04-25 20:34
Le 25/04/2016 20:37, Poil a écrit :
>
> Same bug on Windows 10 x86_64 and an Intel HD Graphics 4000
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RocketChat/Rocket.Chat.Electron/issues/150#issuecomment-214473660>
>
Also reproduced on HD 4000 with 10.18.10.4276


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by Lonewolff** [comment] 2016-04-26 11:09
I can also confirm this issue on my lenovo laptop with Windows 10 x64 and Intel HD 3000 at work. But I dont have this issue at home running Windows 10 x64 with ATI 7950 HD on my desktop.

**Comment by Vulg** [comment] 2016-04-26 20:58
Windows 10 x64 GeForce GTX 560Ti driver 359.00

**Comment by Sing-Li** [comment] 2016-04-27 14:17
Good news.    Please help test this version with GPU optimization disabled. 

Please uninstall existing version, install this one, and run it for a few days on problematic system(s).

Please let us know if it solves the problem on those systems.

[installer for test solution to black squares problem](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

**Comment by stevenhfotofix** [comment] 2016-04-27 15:24
Been running the new software for the last hour - no blackouts (and it used to take under 10 minutes for it to happen) - Nvidia Quadro K620 - Driver version: 10.18.13.5382

**Comment by Vulg** [comment] 2016-04-27 18:57
Application run for about an hour. No black screen for now.

**Comment by thiemol** [comment] 2016-04-28 15:08
Runs perfectly since 2 h.

**Comment by geekgonecrazy** [comment] 2016-04-28 19:27
Ok guys i've released fixed version of the clients that should have this issue fixed.

New build updated: [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.1)

If you're seeing graphical glitches other then just full blackout try out the build @Sing-Li Posted: [GPU-Accel Disabled Windows Build](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

Please let me know if this fixes it for you guys!

**Comment by popiolek** [comment] 2016-05-13 07:28
@geekgonecrazy with official build from your website (v1.3.1) we were getting frozen black screen from time to time on windows 10 x64. Now I've tried the above version posted by you from Sing-Li for couple of days and it seems to work just fine. I'll probably install it on other PCs and message you if any of them run into trouble.

**Comment by geekgonecrazy** [comment] 2016-05-14 00:40
@poplolek awesome!  Sorry I'll get with someone and get the website version update!  Thanks for letting me know

**Comment by cbajohr** [comment] 2016-05-27 08:43
We had the same black screen problem. And I can confirm that it is fixed with the nogpu-version.

**Comment by mm-jatkins** [comment] 2016-08-05 12:14
We've been experiencing the same issue with both non-GPU and normal versions (Win7 and Win10). Not sure but it might be related to the amount of animated GIFs/images within the channel? Since when we enabled "Collapse embedded media by default" the issue goes away.

**Comment by geekgonecrazy** [comment] 2016-08-18 17:18
yeah it sounds like the render thread gets locked up...  Does this happen after you've had it open for a while?   Or do you have a ton of gifs that load with the channel load?   Thinking we might be able to do a couple of things.  

* Unload gifs from the dom when further back in history out of view.  
* Also pause gifs until hovered.  Created an issue here: https://github.com/RocketChat/Rocket.Chat/issues/4055

**Comment by mm-jatkins** [comment] 2016-08-30 15:24
It happens pretty much straight away if you're in a channel that has lots of gif spam ;) 
Some channels have quite a few gifs within the channel, collapsing embedded media was the only way to avoid black screen issues. Unloading sounds like a sensible approach, thanks for creating an issue :)

**Comment by Disar** [comment] 2016-09-02 12:15
So my friend was experiencing the same the way I solved it is by opening the URL to the server in chrome. Create an application shortcut and add it to the taskbar. Downside is of course that it will only work for one server. The sidebar you would normally get isn't there. So If you need this quick "fix"  and you have multiple servers simply create multiple application shortcuts or simply run each of them in separate tabs.

**Comment by LXSysadmin** [comment] 2016-09-20 06:43
Issue is active on 1.3.1 version. We have 25 users and every morning everyone get blank screen, application reload helps. So... i just installed nogpu version, lets see tomorrow.

**Comment by tomash1111111111111** [comment] 2016-09-20 10:11
Same problem here, it happens when uploading files to teammate.
It's not important if you drag the file or select it from file explorer.
Win10x64

**Comment by nina2cool** [comment] 2016-10-04 22:40
I also have the black screen problem.  Just uninstalled and reinstalled version 1.3.1.  I have to quit the app and reopen it.

**Comment by saatomic** [comment] 2016-10-05 14:06
Windows 10 x64, Client version 1.3.1, Intel HD 520.
Still getting black screens.

**Comment by tyrel** [comment] 2016-10-11 19:51
Getting black screens here as well.

- Windows 10 x64
- Client version 1.3.1
- Intel HD Graphics 4600

**Comment by krnlde** [comment] 2016-10-12 09:00
Black screen here, too:
* Windows 10 x64
* Client version 1.3.1
* NVidia Geforce 310m (with latest driver 341.96)

**Comment by graywolf336** [comment] 2016-10-17 06:58
This is an issue with Electron, see the GitHub issue here: https://github.com/electron/electron/issues/4380#issuecomment-198445455

**Comment by brady-young** [comment] 2016-10-25 18:14
Sames issue here with Windows Surface Pro 4s
Windows 10 x64
Client: 1.3.1
Server: 0.44.0
Intel Graphics

**Comment by unassassinable** [comment] 2016-11-10 18:27
I'm using the above posted 1.3.1 version of the client on Windows 10 aniv. update (Version 1607, build 14393.51) and I still get the black screen.

Dell Precision M6800 with:
AMD FirePro M6100 FireGL V - Driver version 15.200.1045.0
Intel(R) HD Graphics 4600 - driver version 20.19.15.4454

**Comment by graywolf336** [comment] 2016-11-18 18:04
@RocketChat/core Any chance we can have this looked into again? As it's becoming an extremely common situation

**Comment by unassassinable** [comment] 2016-11-18 18:51
we went back to an early version of 1.3.1, (rocketchat-v1.3.1-win32-x64.exe) with a file size of 36,715KB.  We downloaded it months ago, and it was still in one guy's downloads folder.  It works for us.  Over 25 users verified fixed.

**Comment by ExaltedJim** [comment] 2016-11-24 02:51
Also experiencing this issue wit version 1.3.1 on Windows 10. Have seen the black screen twice now in last 2 days.

**Comment by BarnumD** [comment] 2016-11-28 17:36
@Sing-Li Is that installer for nogputest based on itanium architecture?  Is there one for x64?

**Comment by BarnumD** [comment] 2016-11-29 21:27
We have several windows 10 users with Dell machines & intel graphics having this issue.

**Comment by mkenyon2** [comment] 2016-11-30 14:01
Downloaded the 1.3.1 installer, and still have this issue.

**Comment by unassassinable** [comment] 2016-11-30 16:50
You gotta try the old 1.3.1 installer.  That's the only thing that worked for us. You can download at:

http://www.filedropper.com/rocketchat-v131-win32-x64

I don't SUPER trust file sharing sites, so I am providing the hash:

SHA256          EC9097183EA65D1D0F2097E2A6A51DEE4F2E4B1572EC1E1DE783EB6F16D34D66

In powershell, do "get-filehash <file>

It would be good if the vendor also provided the hash of all download files.

**Comment by BarnumD** [comment] 2016-11-30 17:02
I tried the older 1.3.1 version but every time I try to drag the window on the screen I get an error.  I also saw this with another version I tried.  I haven't seen any black screen yet.  I'll update this if I do.
![image](https://cloud.githubusercontent.com/assets/2438253/20762572/cdad89e4-b6f4-11e6-9dae-32fceeb0d188.png)

**Comment by Poil** [comment] 2016-11-30 18:18
Personnaly I have switch to Rambox which is a multiclient that's support RocketChat and are doing the job

**Comment by BarnumD** [comment] 2016-12-01 14:04
Rambox didn't work for me because we're using SSO. (they state they don't support it.)

**Comment by brady-young** [comment] 2016-12-01 15:13
Rambox worked for us and we use SSO.  And Rambox also doesn't give the javascript error either.

**Comment by ryanaverill** [comment] 2016-12-02 15:20
+1

**Comment by stevenhfotofix** [comment] 2016-12-02 16:01
+1, forced to use rocketchat-v1.3.1-nogputest-win32-ia32.exe, which works most of the time, but is not foolproof to prevent a black screen (especially with sending photos)

**Comment by sgerritse** [comment] 2016-12-23 07:01
I posted a bounty for this: https://api.bountysource.com/badge/issue?issue_id=32130646

**Comment by LFCavalcanti** [comment] 2017-01-05 00:08
Was the Electron Update to address this? Anyone tested it?

I will rebase tomorrow and test directly from source tomorrow since for us this problem happens very often.

**Comment by geekgonecrazy** [comment] 2017-01-05 00:21
@LFCavalcanti the newest release __should__ fix it

**Comment by imsamthomas** [comment] 2017-01-05 11:56
Latest version [1.3.1](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-win32-x64.exe)

Not fixed yet. Our team is still facing this problem. 

On releases tab, I can see [V2.0.0](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.0.0) but there is no Windows, Mac version.

@geekgonecrazy any idea?

**Comment by LFCavalcanti** [comment] 2017-01-05 12:03
@imsamthomas I opened #272 for exactly this reason.

I'm trying to install and start with NPM from source, but lot's of errors.

**Comment by LFCavalcanti** [comment] 2017-01-05 13:35
OK, I give up, I updated NPM, NVM, Node, reinstalled Python 2.7, even looked at how to fix the "node-gyp rebuild" error, but even following this: https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

I just can't get NPM to install the 2.0.0 client from source.

Can someone from the DEV team give us a little attention please? Maybe build the installers for 2.0.0?

**Comment by LXSysadmin** [comment] 2017-01-05 13:50
LFCavalcanti, yes this would be really nice to get V2 for testing!

**Comment by geekgonecrazy** [comment] 2017-01-05 16:46
https://github.com/RocketChat/Rocket.Chat.Electron/pull/273 Work is being done to automate the releases.

**Comment by geekgonecrazy** [comment] 2017-01-05 21:54
@LFCavalcanti @LXSysadmin can you guys give the latest released binaries a try?  Thanks!

https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.0.1

**Comment by LFCavalcanti** [comment] 2017-01-06 11:30
@geekgonecrazy , I installed on Windows 10 so far... couple hours using, no more black screen and oh boy is it faster now!

**Comment by engelgabriel** [comment] 2017-01-11 02:30
Fix by https://github.com/RocketChat/Rocket.Chat.Electron/pull/278

**Closed by engelgabriel** 2017-01-11 02:30 UTC
Labels: plat: windows, type: bug
