### ISSUE TITLE
[Bug] Downloaded attachment has different content than the uploaded one.

### ISSUE THREAD

**Issue by krystiangorecki** [RocketChat/Rocket.Chat.Electron#948] opened 2018-10-25 22:37 UTC
## My Setup
- Operating System: reproduced on Windows 7, Windows 10, Ubuntu 18.04.
- App Version: 2.14.1
- Installation type: 
    - Windows rocketchat-setup-2.13.3.exe + update 
    - Ubuntu: rocketchat_2.14.1_amd64.deb

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Text file containing HTML uploaded as an attachment and downloaded again has different content.
[before.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/2518437/before.txt) [after.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/2518440/after.txt)

Steps to reproduce:
![steps to reproduce](https://user-images.githubusercontent.com/10375973/47533893-c32d3480-d8b5-11e8-986e-9e436f008485.gif)

### Current Behavior
File content is modified/destroyed. 

### Expected Behavior
Keep original file contents without modification.

**Comment by tassoevan** [comment] 2018-10-26 00:38
This looks like a Rocket.Chat server configuration issue; I couldn't reproduce it in https://open.rocket.chat. Could you please attach the uploaded and the downloaded file here?

**Comment by krystiangorecki** [comment] 2018-10-26 08:50
Files attached.

**Comment by xbiafra** [comment] 2018-10-26 17:44
We've been using Amazon S3 as a storage and have enabled option to proxy upload file transmissions through our server.

**Comment by tassoevan** [comment] 2018-11-19 06:29
I forgot to give a small update: I reported this issue to our back end team and they couldn't replicate it. However, it was suggested that this can be a proxy configuration issue, therefore a Rocket.Chat server issue. I'd like to ask you to file a [new issue in the server repo](https://github.com/RocketChat/Rocket.Chat/issues/new).

**Comment by jeanfbrito** [comment] 2022-08-04 20:55
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Closed by jeanfbrito** 2022-08-04 20:55 UTC
Labels: type: bug, feat: web view
