### ISSUE TITLE
invisible tray icon

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat.Electron#921] opened 2018-10-11 06:21 UTC
## My Setup
- Operating System: Windows 7
- App Version: 2.14.0
- Installation type: exe

- [x ] I have tested with the latest version
- [ x] I can simulate the issue easily

## Description
<a href="https://imgbb.com/"><img src="https://image.ibb.co/jYR8op/icon.jpg" alt="icon" border="0"></a><br /><a target='_blank' href='https://poetandpoem.com/Gabriela-Mistral/poems'>tiny feet by gabriela mistral</a><br />

### Current Behavior

Installed an updated version of the program 2.14.0, where they promised to solve the problem with the invisible tray icon. Problem still exists.

### Expected Behavior
I would like to see the shadow or contour of the icon.

**Comment by tassoevan** [comment] 2018-10-11 16:52
Duplicate of #804.

**Closed by tassoevan** 2018-10-11 16:52 UTC
