### ISSUE TITLE
Moving the application window throws error dialog

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#187] opened 2016-05-11 01:37 UTC
Originally posted from @nmummau at https://github.com/RocketChat/Rocket.Chat/issues/3181
Your Rocket.Chat version: 1.3.1
Windows 7 Professional

When I click and drag the title bar of the application to move the window, I get an error window. Literally whenever I move the window a few inches it throws the error. If I acknowledge the error dialog, and then move the application, the error is thrown again.

![image](https://cloud.githubusercontent.com/assets/10524529/15119206/d0d89806-15dd-11e6-96b2-c34eab4592bb.png)
##

**Comment by geekgonecrazy** [comment] 2016-05-11 01:37
@nmummau does this happen immediately after starting the application up?

Like if you kill it completely (make sure its not in task bar, or there aren't more then on in task bar) then start it.  How long before this happens?

**Comment by StefanAtUeber** [comment] 2016-05-11 12:50
same on windows10. Error appears right after application start.

**Comment by nmummau** [comment] 2016-05-11 12:55
@geekgonecrazy no it doesn't happen immediately for me. It requires me to try to move the window around.

**Comment by StefanAtUeber** [comment] 2016-05-11 12:58
@nmummau you are right. You need to move the window to trigger the error.

**Comment by nobodyshome** [comment] 2016-07-08 15:26
I'm getting the same issue, it also happen when minimising it

**Comment by idchlife** [comment] 2016-09-15 08:29
Many of my colleagues have this issue. Any update on resolving it?

**Comment by nobodyshome** [comment] 2016-09-15 13:48
I believe i solved my issue by adding an exception to my antivirus(mcafee), and it now works perfectly!

On 15 Sep 2016, at 9:29 am, idch <notifications@github.com<mailto:notifications@github.com>> wrote:


Many of my colleagues have this issue. Any update on resolving it?

-

**Comment by richardwlu** [comment] 2016-10-24 16:55
Similar to @nobodyshome, with McAfee, we allowed for `C:\Users\*\AppData\Roaming\Rocket.Chat+\window-state-main.json` to be excluded and we no longer have this issue.

**Comment by stephan2012** [comment] 2016-11-28 09:39
Confirmed, with an exception in the McAfee on-access scanner the client stops throwing JavaScript exceptions.

**Comment by engelgabriel** [comment] 2017-01-19 17:43
@geekgonecrazy can you test this again?

**Comment by engelgabriel** [comment] 2017-01-19 17:44
Maybe we should add @richardwlu fix on our documentation?

**Comment by engelgabriel** [comment] 2017-01-19 18:08
Dup of https://github.com/RocketChat/Rocket.Chat.Electron/issues/181

**Closed by engelgabriel** 2017-01-19 18:08 UTC

**Comment by geekgonecrazy** [comment] 2017-01-20 03:10
> @geekgonecrazy can you test this again?

Last build I tested on windows I never had this happen.  So I think it might be solved other then the edge case with McAfee

**Comment by nmummau** [comment] 2017-02-03 12:32
I agree, I think we can close this out. I haven't seen it since I reported it in May 2016.
