### ISSUE TITLE
Windows: Clicking tray icon makes window disappear, clicking again does not bring it back

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.Electron#944] opened 2018-10-24 12:24 UTC
## My Setup
- Operating System: Windows 10 Build 1809
- App Version: 2.14.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The apparent functionality of clicking the tray icon is to completely hide or show the window. This works great if the window is not minimized. However, if the window is minimized and you click the tray icon, it first disappears from the taskbar, as it should, but when you click on the tray icon to bring it back, it does not come back. The only way to bring it back is to receive a new message desktop notification (and to click it), or to quit the program through the context menu, and reopening it.

### Current Behavior
Described above.

### Expected Behavior
Clicking on the tray icon should always hide or bring back the window, regardless of minimized state (if anything, the window should reappear minimized in the taskbar).

[![Video](https://i.ytimg.com/vi/9q5kNmytq34/hqdefault.jpg)](https://youtu.be/9q5kNmytq34 "Video")

**Comment by tassoevan** [comment] 2018-10-25 18:07
Duplicate of #925.

**Closed by tassoevan** 2018-10-25 18:07 UTC

**Comment by bkraul** [comment] 2018-10-26 00:45
Not sure it was said on #925,but this appears to have been effectively fixed in 2.14.1.
