### ISSUE TITLE
Could you please use Windows Notifications API for notifications about messages

### ISSUE THREAD

**Issue by drweb86-work** [RocketChat/Rocket.Chat.Electron#702] opened 2018-04-05 18:47 UTC
This API can be easily configured by user and all messages of certain types can be easily disabled

**Comment by gdelavald** [comment] 2018-04-05 20:29
This would require a refactor on our notifications, it's doable, might be in the roadmap when we focus on the Windows Store features. Thanks for your suggestion!

**Comment by angelorodem** [comment] 2018-10-31 20:24
Current notifications are easy to overlook, the taskbar icon should blink, it would help a lot.

**Comment by tassoevan** [comment] 2018-10-31 21:04
Duplicate of #775.

**Closed by tassoevan** 2018-10-31 21:04 UTC
Labels: feat: notifications, type: enhancement
