### ISSUE TITLE
URL drag bug still occurring. 

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat.Electron#351] opened 2017-02-09 11:32 UTC
## My Setup

 - __My OS name and version__: Fedora 25 
 - __My current app version__: 2.4.0

- [*] I have tested with the latest application version
- [*] I can simulate the issue easily

## Description

To simulate this issue, you need to drag a URL into rocket chat  it happens only sometimes now.

#### Current Behavior

When a URL is dragged into rocketchat it then loads the dragged url. There is now no way to get back from this without deleting the config folder for rocket chat for mac, you have to removed the application and configs. 

![rocketbug](https://cloud.githubusercontent.com/assets/7502243/22781609/28e66364-eebb-11e6-97d4-b5fa8909f45a.png)

Previous open issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/308

Supposed Fix: https://github.com/RocketChat/Rocket.Chat.Electron/pull/345

#### Expected Behavior
This is reproachable and is clearly not fixed.

**Comment by alexbrazier** [comment] 2017-02-09 20:05
@oliver-bowman I am unable to reproduce this on the Mac version, but I will try again with Linux. Is there anywhere in particular where you drag the url for this to happen?

Also you say it only happens sometimes, how often can you get it to happen, and is there anything you do differently?

Can you also try clicking `View -> Application -  Reload` when it happens, as this should reload your original server back up without having to clear any data.

**Comment by oliver-bowman** [comment] 2017-02-10 09:50
So I can confirm that if reload the application it reloads the the correct original state.

**Comment by oliver-bowman** [comment] 2017-02-10 09:57
By sometimes I mean that it can get maybe 1 out of every 3 times I try.

**Comment by alexbrazier** [comment] 2017-05-06 16:14
@oliver-bowman is this still an issue, I'm still struggling to recreate it?

**Comment by oliver-bowman** [comment] 2017-05-11 08:20
I cannot recreate it easily, I have only had one of my colleagues come to me with this issue still.

**Comment by reitzig** [comment] 2017-08-31 11:15
Can confirm with Ubuntu 16.04, Firefox 54, Rocket 2.9.0. I dragged an image out of the browser with the intend of sending it in a Rocket chat, instead the client loaded the image. Can reproduce after restart.

**Comment by gdelavald** [comment] 2017-08-31 16:37
@reitzig if it isn't much trouble, could you try and get a gif/video of you reproducing the issue? (I use recordit.co do record and upload automatically)
I tried to reproduce this issue on a VM running Ubuntu 16.10 and Rocket.Chat 2.9.0 and the popup for sending image showed up preventing any navigation from happening.

**Comment by reitzig** [comment] 2017-09-26 06:35
[Sure](https://imgur.com/SYJkWMW). Can not reproduce with local files dragged in from Nautilus, by the way.

(`gtk-recordmydesktop`, by the way -- simple, free and local.)

**Comment by ttepatti** [comment] 2018-11-14 19:54
I'm unable to reproduce this behavior on Debian Stretch 9.5 on the latest version of Rocket Chat (2.14.1)

Due to the age of this issue, unless anyone else can still reproduce this issue, I believe it can be closed. It appears to have been fixed in the past year.

**Closed** 2018-11-14 21:11 UTC
Labels: type: bug

**Comment by reitzig** [comment] 2018-12-11 07:48
FWIW, can not reproduce with FF 63.0.3 on Ubuntu 18.04 with RocketChat 2.7.0 / 0.70.1. (That's the latest I get from snapcraft.io -- is that maintained?!)

Not that the behaviour is correct: Rocket _ignores_ the image dropped from FF.

**Comment by tassoevan** [comment] 2018-12-11 17:05
@reitzig Publishing the snap is anunfinished work (#682) :disappointed: Could you please open an issue about your drag-and-drop issue?
