### ISSUE TITLE
Client Update failed 2.17.10 -> 2.17.11

### ISSUE THREAD

**Issue by amathar** [RocketChat/Rocket.Chat.Electron#1665] opened 2020-07-22 06:01 UTC
This bug is still not fixed, I think.
Going to Help -> About Rocket Chat -> check for updates I see. that a new version is available:
![Update-problem](https://user-images.githubusercontent.com/10864160/88140018-35e55400-cbf1-11ea-9d16-03985c744d4d.jpg)

When I want to install this update, I only get a message, that I will be notified when the update is ready to install:

=> No Update.
![grafik](https://user-images.githubusercontent.com/10864160/88140063-4bf31480-cbf1-11ea-9fc6-84a32ba2dc0e.png)

This problem occurs not only in 2.17.10, but in older versions too.
Can you fix this? Thank you

**Comment by pRieStaKos** [comment] 2020-07-22 06:17
Same here. I have to download it from Releases

**Comment by JackNWeems** [comment] 2020-07-22 13:32
I think this is a Duplicate of #1205

**Comment by Fosol** [comment] 2020-08-19 12:43
I'm stuck on 2.17.3.  I get this message to upgrade to 2.17.11 every day.  It never installs...

**Comment by tassoevan** [comment] 2020-09-02 22:54
Closing in favor of #1670.

**Closed by tassoevan** 2020-09-02 22:54 UTC
Labels: stat: duplicate
