### ISSUE TITLE
rocket.chat will not properly close when closing through the window manager on linux mint 20 ulyana mate

### ISSUE THREAD

**Issue by tuxcrafter** [RocketChat/Rocket.Chat.Electron#2328] opened 2022-03-01 15:14 UTC
Somewhere in the last few months on all our rocket.chat systems, rocket.chat will stay running in the background when telling the mate windows manager to close rocket.chat (red cross window), however rocket.chat will close properly when going to the menu and then choosing close. The rocket.chat windows will go away but the progress stays running in the background and the users can not restart rocket.chat to get the main window back. We have to kill the rocket.chat process and then you can start the application again to get the main window.

A workaround is `"isTrayIconEnabled": true,` when closing the rocket.chat window it will disappear and in the tray icon you can get the application back...	

I have tested the latest few release in the hopes the issue would go away, but it persists, so I am writing this bug report now.
	
```
# dpkg -l rocketchat
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  rocketchat     3.7.8        amd64        
```

```
# cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana" 
MATE
```

**Comment by jeanfbrito** [comment] 2022-03-01 15:46
Thanks for notifying us about it. I think that the problem is the way we handle closing it on Linux. On Windows and Mac Os works differently. 
I will create a Linux Mint machine to reproduce this.

**Comment by JanBartels** [comment] 2022-03-01 18:34
Not specific to Mint. Same on Ubuntu. ps still lists PIDs after closing the client application window.

**Closed** 2022-03-17 19:57 UTC
