### ISSUE TITLE
The Rocket.Chat button is multiplied at the entrance

### ISSUE THREAD

**Issue by Masterstop** [RocketChat/Rocket.Chat.Electron#757] opened 2018-07-02 09:45 UTC
## My Setup
- Operating System: Windows 10
- App Version:   2.11.0

## Description
Just open application

### Current Behavior
I have 4 Rocket.Chat buttons on the left buttons. They disappear, when I point on the first

### Expected Behavior
Only 1  Rocket.Chat button

![clipboard - july 2 2018 12-22 pm](https://user-images.githubusercontent.com/11866691/42157231-d238b06e-7df5-11e8-916b-9b6db848eff0.png)

**Comment by kaiiiiiiiii** [comment] 2018-07-02 10:42
Duplicate of #744

**Comment by gdelavald** [comment] 2018-07-02 21:29
The issue has been fixed, and will be on the next relased version.

**Closed by gdelavald** 2018-07-02 21:29 UTC
