### ISSUE TITLE
High memory usage - members list

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Electron#1555] opened 2020-03-20 06:36 UTC
#735  My Setup

- Operating System: WIndows 10
- App Version: 2.17.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
We are observing very high memory usage during show "Members list" in big channel (2600 users).
When scroll down and click "Show more" computer slows down and RAM usage grow to 1,7 GB, it is very high value.

![image](https://user-images.githubusercontent.com/50440047/77141475-55bb0e80-6a7d-11ea-9d1a-b997d28f802d.png)

### Current Behavior
RAM usage is to high.

### Expected Behavior
RAM usage should be reduced.

**Comment by gabriellsh** [comment] 2020-04-27 15:17
Couldn't reproduce this in Catalina. I think this is more related to the app than Electron itself. We recently fixed a couple memory leaks, but I'm not certain any of those were related to this. Could you try joining https://open.rocket.chat/ and testing the user list on either `#general` or `sandbox`? The general channel currently has 311664 users, and it's on the latest version. Thi way we can isolate better the problem.

**Comment by emikolajczak** [comment] 2020-04-28 06:07
Hi, I have tested on https://open.rocket.chat/ and `#sandbox` and same behavior, RAM usage is increasing.

**Comment by gabriellsh** [comment] 2020-04-28 23:29
Thanks a lot for the help triaging this @emikolajczak!

**Comment by piotrkochan** [comment] 2020-10-02 22:17
Hello there 

![image](https://user-images.githubusercontent.com/5632761/94974103-d28b7280-050d-11eb-80a6-272aea024967.png)

**Comment by algonza** [comment] 2020-10-05 14:56
I was able to reproduce the high memory consumption easily. Seems to affect mostly a single proc. 
I can make it happen by opening every unread PG room (~20 out of 40). 
Fresh launch after a reboot was about at 250MB. After ~20 unread rooms opened, it increased to ~800MB and settled down to about 500MB and pretty much stays there.
It's almost as if it loads into memory the entire contents of each room as opened and keeps some portion of each in memory there despite switching to a different one. The client mem usage never makes it back down to anywhere near the freshly opened client's usage - ever.
It's bogging down management's desktops and other power users like myself. We are starting to get the ol' raised single eyebrow from the wrong user base.

User base: 500+
RC Win clients: 2.17-3.0.2
Win Desktops: Win 7 and 10
RC ver: 3.62 (latest Ubuntu Snap)

**Comment by algonza** [comment] 2020-10-05 15:25
**Update:** Whatever it is using the memory looks like it may cache related. 
I was able to reduce the memory usage back down to the newly opened client amount by using the the Reload ignoring cache option.
Is there a way to call this reload outside of the menu?
Also, creating a room consumed less than ~200KB of mem.

**Comment by WillGoGithub** [comment] 2020-10-08 05:52
![image](https://user-images.githubusercontent.com/45837931/95419783-dd5e6100-096c-11eb-8f61-568f0c60bddf.png)

We have the same problem. RAM usage constantly increasing from 400M to almost 2800MB. (one night)

---

Operating System: Windows 10
App Version: 3.0.2
Installation type: msi

**Comment by OliverMD15** [comment] 2021-08-21 03:52
![image](https://user-images.githubusercontent.com/81589421/130309660-178d9d35-f7c9-414b-8983-12e8dbc372b9.png)
Leaks are still an issue, to say the least.

Operating System: Windows 10
App Version: 3.2.3
Installation type: msi

**Comment by ggazzo** [comment] 2021-09-23 13:02
is this still an issue?

**Comment by OliverMD15** [comment] 2021-09-23 13:19
Not sure about 3.5.6, but high memory usage was still an issue for me on 3.5.5, when I let it run for a longer time (6+ hours).

**Comment by jeanfbrito** [comment] 2022-01-12 01:45
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 01:45 UTC
Labels: plat: windows, subj: performance
