### ISSUE TITLE
Error gets raised when opening About Rocket.Chat+

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.Electron#444] opened 2017-05-11 11:37 UTC
## My Setup
 - macOS 10.12.4
 - 2.7.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

Open Rocket.Chat+ > About Rocket.Chat +

#### Current Behavior

JavaScript error gets raised

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at Event.set (/Applications/Rocket.Chat+.app/Contents/Resources/electron.asar/browser/api/web-contents.js:252:22)
    at EventEmitter.electron.ipcMain.on (/Applications/Rocket.Chat+.app/Contents/Resources/app.asar/app/src/background/autoUpdate.js:124:26)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/Rocket.Chat+.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

#### Expected Behavior

About Rocket.Chat+ window should appear with version informations.

**Comment by engelgabriel** [comment] 2017-05-11 13:05
duplicate of #427

**Closed by engelgabriel** 2017-05-11 13:05 UTC
