### ISSUE TITLE
Screenshare support

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#188] opened 2016-05-11 01:53 UTC
We need to add screenshare support into electron.  Unfortunately we can't just drop the chrome extension in, but we should be able to port it over.

**Comment by xenithorb** [comment] 2016-06-07 04:07
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/65

**Closed** 2016-06-07 05:28 UTC
Labels: type: new feature
