### ISSUE TITLE
Unidentified Developer on Mac 10.15

### ISSUE THREAD

**Issue by nghtstr** [RocketChat/Rocket.Chat.Electron#1269] opened 2019-06-26 21:07 UTC
## My Setup
- Operating System: Mac OS 10.15 PB1 (Catalina Public Beta 1)
- App Version: 2.15.3
- Installation type: App Store

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

Every time I try to launch the application, it is saying it is from an unidentified developer, and then throws up a Javascript error that does not go away. I have uninstalled and re-installed it multiple times.

### Current Behavior
Pictures tell the whole story
When I open it (either by Double Clicking, Right-Click->Open, or Open from App Store):
<img width="421" alt="Screen Shot 2019-06-26 at 2 01 48 PM" src="https://user-images.githubusercontent.com/51501/60214967-80907300-981b-11e9-8046-72d2b2b994ea.png">

Then it does this weird error that cannot be removed (probably because it does not have access rights):
<img width="434" alt="Screen Shot 2019-06-26 at 2 06 56 PM" src="https://user-images.githubusercontent.com/51501/60215059-b5042f00-981b-11e9-8f4a-dee56e146356.png">

### Expected Behavior
Launch the application

**Comment by Jack3113** [comment] 2019-07-16 12:14
On macOS Catalina, all apps have to be notarized by Apple
[Source](https://developer.apple.com/news/?id=06032019i)

**Comment by abonillasuse** [comment] 2019-07-30 18:03
Is there a workaround?

**Comment by regetskcob** [comment] 2019-08-09 05:33
> On macOS Catalina, all apps have to be notarized by Apple
> [Source](https://developer.apple.com/news/?id=06032019i)

Are you already working on getting it notarized? Catalina launch will be very soon.

**Comment by nghtstr** [comment] 2019-08-13 21:48
I am confused. You have the app in the Mac App Store already. I don't see how this would be at all difficult to handle.

**Comment by lazyants** [comment] 2019-08-15 06:35
i found the workaround, for now download the app directly from the website instead installing from the app store

**Comment by nghtstr** [comment] 2019-08-20 21:38
@lazyants, worked like a charm!

**Comment by gcommit** [comment] 2019-10-08 12:13
i think this is still not resolved, isn't it? I had to download the app once more from the website, because the one from the app store doesn't work anymore.

**Comment by abroadwin** [comment] 2019-10-08 18:38
Confirmed, a fresh download from the app store still fails with this error.

**Comment by dyohan9** [comment] 2019-10-09 11:40
downloading directly from the site, works on current version of MacOS Catalina 10.15 (19A583)

**Comment by xboston** [comment] 2019-10-09 11:44
My temporary solution:
```
sudo xattr -cr /Applications/Rocket.Chat.app
sudo codesign --force --deep --sign - /Applications/Rocket.Chat.app
```

**Comment by lgerhardt45** [comment] 2019-10-15 12:42
https://developer.apple.com/news/?id=06032019i Here's the press release concerning this issue.

**Comment by jeanfbrito** [comment] 2022-01-12 00:41
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:41 UTC
Labels: type: bug, plat: osx
